### ISSUE TITLE
Clean up and document angular bindings

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#104]
The current angular binding is messy and undocumented:
- [x] When the library is used in angular we need to clean up the global `ERMrest` library. 
- [x] For the revised API sketch we do not need the factory, we just need `ERMrest` to be the factory.
- [x] We need documentation. Ideally this can be generated from jsdocs but it may not be possible and may have to be manually written.

**Comment by jrchudy** [comment]
Merged the PR #107. Closing this issue.
