### ISSUE TITLE
Packaging of third party dependencies

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#135]
We have recently introduced a third party dependency into ermrestjs, namely the "markdown-it" library. At present we have simply concatenated it into our `ermrest.js` as a bundle effectively. While this may be sufficient for now, this is probably not the right way to do it or the advisable way to do it. For instance, what if we bundle a library but our client (like Chaise or other applications) needs that same library but a different version of it and it therefore conflicts.

We should explore advice from the javascript world and see what other suggested approaches are out there. For instance, one might instead just:
- declare the prerequisites for ermestjs in its documentation
- let users of ermrestjs (like the Chaise UI) include ermrestjs and its prerequisites independently.

If we did the above, we would need to make changes to Chaise's installation and deployment scripts.

**Comment by robes** [comment]
@hongsudt I think this is pretty important (but maybe not urgent) and if he had time @chiragsanghvi could be a good person to look into this.

**Comment by hongsudt** [comment]
@robes Pull request #136 is waiting for your review.

**Comment by chiragsanghvi** [comment]
This was done in PR #148 and is in Master. So closing it.
