### ISSUE TITLE
foreign key alias to foreign key ref look up functionality

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#137]
We need the ability to look up a foreign key reference based on its different aliases. The plan is to implement a `foreignKeyRefMap` object for each schema. 

@RFSH  Please note that, the schema can sometimes have an empty string. So the code should deal with this.

**Comment by hongsudt** [comment]
@karlcz what cause ermrest to return an empty string schema name? E.g. how should @RFSH set up the table to test this case?

**Comment by chiragsanghvi** [comment]
@hongsudt We can mock the server response for testing this case.

**Comment by karlcz** [comment]
The empty string schema name is used for psuedo foreign key constraints which cannot be manipulated through the REST API alone.

Normally they would only be involved if you use REST API to define a foreign key constraint involving two SQL views or a SQL view and table. The view would have to be defined directly through the RDBMS since we provide no REST API to define views at this point.

**Comment by RFSH** [comment]
@hongsudt Since we decided to add `ForeignKeyMap` to schema, I am using the schema string to find the schema and add `ForeignKeyRef` to its corresponding `ForeignKeyMap`. What should I do In case of an empty schema string? Should I just ignore it?

**Comment by karlcz** [comment]
You should keep one additional special map somewhere in the model to store the constraints qualified by empty string schema name. This is an important feature we'll encounter in several of our use cases where we've customized our catalogs with SQL views that are presented to users via Chaise, and these are involved in the pseudo foreign key constraints to link them to related tables and views.

**Comment by hongsudt** [comment]
Will this be simpler if we implement the map as an equivalence of 2D lookup
table e.g. foriengKeyMap[schema-name][alias-name] and attach the map at the
catalog level?

**Comment by RFSH** [comment]
We decided to add the constraint lookup function to Catalog;
```javascript
Catalog.prototype = {
  byConstraintName(schemaName, constraintName){
    ...
 }
}
```

**Comment by karlcz** [comment]
I think there should be a trivial way to lookup by what is in the annotations, either making this method more clever or making another wrapper like:

   function constraintByNamePair(pair){
     return constraintByName(pair[0], pair[1]);
   }

so you don't have code all over the place picking out the array elements to put them as separate parameters...

**Comment by robes** [comment]
@karl are these _blank named_ schemas still represented as a Schema resource  in ERMrest?

**Comment by karlcz** [comment]
No, the `""` schema name is being used to qualify psuedo constraints
that don't exist in a real schema.  The empty string is not a valid
schema name in PostgreSQL so it cannot collide with any possible
catalog content...

**Comment by robes** [comment]
Should we give it a name like `_ermrest` so that we could represent it consistently?

Just a thought, but if not, then I can see why we have push this interface up to the Catalog. Makes sense to me.

**Comment by karlcz** [comment]
`_ermrest` is also not present in the schemas reported by introspection.

No matter what, you're going to have a special name that does not correspond to a schema name that is part of the model that a model-driven client would want to encounter or present to users.
