### ISSUE TITLE
Referece.related should handle pure binary association table

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#139]
* `binary` : Has 2 outbound foreign keys. 
* `pure`: The table has only one composite key constraint. This key includes all the columns from both foreign keys.
(As an exception, the table can have one extra key that is made of one serial type column.)

One way to implement this is to set a flag `._isPureBinaryAssociation` flag to indicate whether the table is a pure binary association. Then while the Reference.related is created, add the logic that will update the related entities' `display_name`, `uri`, and `columns` appropriately. See diagram below.

![img_20160805_164444](https://cloud.githubusercontent.com/assets/414732/17453248/938922be-5b2d-11e6-97e4-7abd9861e14c.jpg)

**Comment by hongsudt** [comment]
For now, I would like to make this flag reflect the strict definition above. 

Note: The binary association table could have other literal columns such as rank in protocol_author scenario. However, until we know how to merge tables together, let's not include this scenario.

**Comment by RFSH** [comment]
I changed the definitions accordingly:
* `binary` : Has 2 outbound foreign keys. The table has only one composite key constraint. This key includes all the columns from both foreign keys.
(As an exception, the table can have one extra key that is made of one serial type column.)
* `pure`: All its columns are part of some key constraints.

**Comment by RFSH** [comment]
#167 changed the definitions based on the previous comment and resolved this issue.
