### ISSUE TITLE
update Tuple.value according to the markdown_pattern (e.g. url) annotation  

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#140]
Tuple.value should handle the url annotation defined in informatics-isi-edu/ermrest#93.  

If the annotation is defined, the value should be formatted accordingly. We also need a method that the app can check whether to treat the string as an html or not.

**Comment by hongsudt** [comment]
@chiragsanghvi you mentioned a couple of template plugin. Can you list them here?

**Comment by chiragsanghvi** [comment]
[Mustache](https://github.com/janl/mustache.js/) is a lightweight templating library. 
A heavy version with more set of features is [Handlebars](http://handlebarsjs.com/)

**Comment by hongsudt** [comment]
@karlcz @robes can you check these templating libraries? For now, I will assume that we will continue to use the same template that we have been using.

**Comment by chiragsanghvi** [comment]
@hongsudt 

Yes, just to ennumerate…the 4 cases are

1. **Normal Link** : `[Chaise](https://dev.isrd.isi.edu/chaise/search)`

2. **Normal Image**: `![Image](http://assets.barcroftmedia.com.s3-website-eu-west-1.amazonaws.com/assets/images/recent-images-11.jpg)`

3. **Image with size**: `![ImageWithSize](http://assets.barcroftmedia.com.s3-website-eu-west-1.amazonaws.com/assets/images/recent-images-11.jpg =200x150)`

4. **Download Link**: `<a href="http://https://code.jquery.com/jquery-3.1.0.js" download>Download</a>`


Copy following javascript code [here]() to check for their appearance.

```javascript
var md = require('markdown-it')({ html: true }).use(require('markdown-it-imsize'));

console.log(md.renderInline("[Chaise](https://dev.isrd.isi.edu/chaise/search)"));

console.log(md.renderInline("![Image](http://assets.barcroftmedia.com.s3-website-eu-west-1.amazonaws.com/assets/images/recent-images-11.jpg)"));
            
console.log(md.renderInline("![ImageWithSize](http://assets.barcroftmedia.com.s3-website-eu-west-1.amazonaws.com/assets/images/recent-images-11.jpg =200x150)"));   


console.log(md.renderInline("<a href='http://cdn.appacitive.com/sdk/js/appacitive-js-sdk-v1.0.10.min.js' class='btn btn-primary' download>Download</a>"))
```

**Comment by chiragsanghvi** [comment]
@hongsudt @karlcz  Will this syntax work ?

```sh
# Iframe with height and width
::: iframe [Chaise](https://dev.isrd.isi.edu/chaise/search){width=800 height=300} \n:::

# Link
[ChaiseLink](https://dev.isrd.isi.edu/chaise/search)

# Download Link
[Jquery Download](https://code.jquery.com/jquery-3.1.0.js){download .btn .btn-primary}

# Image
![ImageWithSize](http://assets.barcroftmedia.com.s3-website-eu-west-1.amazonaws.com/assets/images/recent-images-11.jpg)

# Image with size
![ImageWithSize](http://assets.barcroftmedia.com.s3-website-eu-west-1.amazonaws.com/assets/images/recent-images-11.jpg){width=800 height=300}

```

You can see the output [here](https://tonicdev.com/chiragsanghvi/57b36c60150dc61300d37918/branches/master)

**Comment by hongsudt** [comment]
I like it.. The syntax is consistent..

**Comment by karlcz** [comment]
Yeah this seems like good notation but the output HTML needs a little work...

`<div style='clear:both'><div class='caption'>Chaise</div><iframe src=https://dev.isrd.isi.edu/chaise/search width=800 height=300 ></iframe></div>`

The quotes around the div.style and div.class should be `"` not `'`. And the quotes are missing around iframe.src, widht, and height...

**Comment by robes** [comment]
Syntax looks good 👍

**Comment by chiragsanghvi** [comment]
@karlcz Yes, I will make  the changes in formatting.

**Comment by hongsudt** [comment]
Can we make it so that I can leave any number of spaces after ::: e.g. `:::  iframe`?

**Comment by hongsudt** [comment]
@chiragsanghvi The link above no longer points to the markdown usecases, so I can't easily test this.
Does iframe support any number of white space prior to that keyword?

**Comment by chiragsanghvi** [comment]
Yes, it supports any number of whitespaces after the iframe keyword, but not before it.

```sh
# This will work
:::iframe     [cap](http://www.example.com) \n:::
```

```sh
# This won't work
     :::iframe     [cap](http://www.example.com) \n:::
```

**Comment by hongsudt** [comment]
It is a lot of work to make it support any number of white space before
iframe?

**Comment by chiragsanghvi** [comment]
There's just a change needed in the **regexp**. But do we really need to allow that. Its actually wrong syntax. Markdown will never allow to have a space between the caption and the href for the anchor syntax `[caption] (http://www.google.com)`

**Comment by hongsudt** [comment]
I just tested it on github and I was able to put space between `[]` and `()` e.g. [ test ]  ( http://dev.isrd.isi.edu )

**Comment by karlcz** [comment]
The [Commonmark spec](http://spec.commonmark.org/0.26/) says that the
"link text" i.e. `[My anchor]` is supposed to be followed immediately by
the open paren.  I don't see why we want to code in support for sloppy
markdown and encourage our users to learn bad markdown habits...

Similarly, it says that a fenced code block can have at most three
spaces before the code fence (the opening three characters ` ``` ` or
` ~~~ `).  I think our custom containers are based on this and probably
need to follow the same rules before their opening ` ::: `?

**Comment by hongsudt** [comment]
For clarification, I meant supporting white spaces between `:::` and the word `iframe`.

**Comment by karlcz** [comment]
Spaces between the ` ::: ` and `iframe` should be allowed if these containers behave like a code fence.  The commonmark spec says that space around the "info string" is allowed and stripped.

**Comment by chiragsanghvi** [comment]
Ok, we can do that. They do actually act like code fence but our specification needs it to be single line. So adding the space handling just makes it more error friendly, but adds no purpose or feature.
