### ISSUE TITLE
Add 'location' property to 'Reference'

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#141]
Now that clients will be using `Reference` objects they will know less (or nothing) about the manipulation of the underlying URI, yet they will need _part of_ the URI to use in the Permalinks.

For example, the Chaise recordset app starts up, passes the ERMrest URL to `ERMrest.resolve(uri)`. At this point, the client knows what the permalink should look like (chaise resource reference + catalog and "data path" URL components).

But, let's say the user of the recordset sorts on a column or pages to the next page of results, they will now need access to a "data path" and other URL components in order to form the Permalink.

But also keep in mind that the client needs the URL parsed not just the full string. So giving clients direct access to `Reference._uri` is not enough. What we probably really need is a _location_ property with an interface (something) like this.

A property `Reference.location`:
```
Location
  .uri // getter that returns the full ermrest uri
  .catalog // getter that returns just the catalog name ?
  .path // getter that returns the rest of the path ?
```

This object should make it easy for clients like Chaise to build the Permalink with minimal effort.

**Comment by shinyichen** [comment]
While working on the sorting, I needed the uri up to the filter (@sort and ?limit removed). Should we keep that in Location as well?

**Comment by robes** [comment]
I think the answer is yes, but I'd have to look at an example to be sure.

**Comment by robes** [comment]
Just to add some notes here after discussion.

1. we can clean up the `Reference` a bit. Seems like we don't really need: `_tableName`, `_schemaName`, or `_schema`.
2. the parser function (in js/parser.js) can return the (new) `Location` instance rather than the `context` object it currently returns
3. therefore the `Reference(...)` constructor will take the `location` instead of the `context`, and it might need other parameters (like the `table`?)
4. the `Location` can include the parsed _sort object_ needed internally and can have a getter to serialize the sort object into the `@SORT(...)` form
