### ISSUE TITLE
Pre-format column values for int, float, blooean

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#146]
This is related to #52.
- Int/float
  - [ ] pre_format annotation to use format string conversion specifiers
  - [ ] units specifier for numbers
- boolean
  - [] mapping of true/false to different terms (e.g. yes/no)

**Comment by karlcz** [comment]
@hongsudt I need some kind of support for the pre_format feature above or another way to adjust the display precision for floating point numbers.  it's currently a problem for synapse.

**Comment by hongsudt** [comment]
Take a look at #299 for formatting requests.
