### ISSUE TITLE
functionality to support form data entry app

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#15]
1. Whatever ermrest API functions are needed to support introspection, data validation, and row insertion for informatics-isi-edu/division#35
2. Whatever ID generator library routines and/or dispatch logic to compute derived ID values from partial content for a new row.

Please consult with @robes and @karlcz on the needs.

**Comment by hongsudt** [comment]
@shinyichen when you have a chance, please update this issues with detail tasks needed for this..

**Comment by howdyjessie** [comment]
As far as I can tell, I have everything I need from ermrestjs for now. I'm rewriting the data entry app again so if I need something new, I'll reopen this issue.

**Comment by shinyichen** [comment]
These methods were added.
.all() for container classes
ForeignKeyRef.getDomainValues() -> get the possible values from the referenced table.
.colsets and get(colset) for _ForeignKeys

**Comment by robes** [comment]
could you add those to the wiki for the api sketch?
