### ISSUE TITLE
Support `2016 Table Display: set_presentation

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#153]
We should figure out how to use this to support iframe using a markdown syntax specified in the annotation doc.

**Comment by chiragsanghvi** [comment]
@robes @karlcz After having a discussion with @hongsudt this is the API proposition that we came up with.

The reference object will have a `display` property with a getter function as follows.
```js
 /*
  *  An object which contains row display type for this reference. 
  *  Will be populated on basis of  "table-display" annotation. 
  *
  *  The object has following properties
  *  {
  *    type: "markdown",  // Possible values are table/markdown/module(Default is "table")
  *
  *    // If type is "markdown" then you will get these properties 
  *    separator: "\n",  // Default is new line "\n"
  *    suffix: "SOME_MARKDOWN",  //Default is empty string ""
  *    prefix: "SOME_MARKDOWN",  //Default is empty string ""
  *  
  *    // If type is "module" then you will get these properties
  *    modulePath: "pathsuffix"
  *  }
  * ```
  *
  * Usage :
  * ```
  * var displayType = reference.display.type; // the displayType
  *  if ( displayType === 'table') {
  *    // go for default rendering of rows using tuple.values
  * } else if (displayType === 'markdown') {
  *    // Use the separator, suffix and prefix values while rendering tuples
  *    // Tuple will have a "tuple.content" property that will have the actual markdown value
  *    // derived from row_markdown_pattern after templating and rendering markdown
  * } else if (displayType ===  'module') {
  *   // Use modulePath to render the rows
  * }
  * ```
  * @type {Object}
  */  
  get display() {
     // ...
     // ...
  }
```


In addition the `tuple` object will have a `content` property that will contain all the markdown generated as a result of the `row_markdown_pattern` property of the annotation.


Does this works ? Or should we add a `content` property to `tuples` object that will compute the final HTML generated for each tuple based on `row_markdown` and combining the separator, prefix and postfix markdown to be displayed for a page depending on the display type ?

**Comment by hongsudt** [comment]
@chiragsanghvi Let's try to have `Page.display` return the composition of all rows associated with a page.

**Comment by robes** [comment]
This seems fine to me. The only real question I have is what happens when you have Reference to an ERMrest URL using the `attribute` interface rather than an `entity` interface? In that case, we should probably default to display type of `table`, for default rendering of the results, right?

**Comment by karlcz** [comment]
I don't see why the attribute api would imply tabular display.  The result set has the same semantics of one row per entity with just a customized projection of which attributes are present.

With attributegroup it's a little fuzzier since each row summarizes a group of entities.  But, I'm still not sure that implies tabular display since you might still look at one group as a detailed record-level view?

What would be difficult from any custom projection would be to interpret any markdown patterns since they might reference column names which are not present in the projection. Should all markdown expansions be disabled, or should we just do a best effort attempt and treat the missing columns as nulls?

**Comment by chiragsanghvi** [comment]
@karlcz @hongsudt 
I had a doubt, what values should I use in the template for table-display annotation ? Should I use the formatted `markdown_pattern` values or just basic formatted values depending on type or raw values.
