### ISSUE TITLE
support gene_sequence use case

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#157]
This will either be specified through a markdown syntax or a different annotation syntax. We need this to support gpcr and maybe facebase.

**Comment by hongsudt** [comment]
@karlcz @robes I am going to suggest creating a different custom type gene_sequence and get the pretty_print to deal with the formatting.. Any objection?

**Comment by karlcz** [comment]
Should this be able to be composed with markdown features?  I.e. will we ever expect to have a markdown_pattern that expands gense sequence column data into a formatted presentation?

Basically, I am pondering whether gene-sequence should be another special markdown container that we can wrap around the raw sequence string.

**Comment by howdyjessie** [comment]
Do gene sequences always come in increments of 10? If not, what should I do with the remainder?

**Comment by howdyjessie** [comment]
This is currently under review in PR #168.

**Comment by howdyjessie** [comment]
PR #168 has been merged.
