### ISSUE TITLE
Datapath API

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#16]
@robes Can you please fill in the scope of this task?

**Comment by karlcz** [comment]
I think this assignment is backwards from what has been discussed in meetings, so flipping it around...

**Comment by robes** [comment]
The Datapath API could be a large and complex piece of work. I think I/we need to review this with jennifer and jessie (for her inputs on what we need for downstream apps that use it) so that we can break this into units that can be complted in ~week time units.

**Comment by hongsudt** [comment]
@shinyichen if this is done, can you please put it in review and assign someone else to review it?

**Comment by hongsudt** [comment]
@robes can you review this?

**Comment by robes** [comment]
ok
