### ISSUE TITLE
Should we (continue to) implicitly add @SORT when Reference.read(...) is invoked

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#160]
One open question has to do with the `Reference.read(limit)` function which implicitly adds a sort key to the uri if none existed in the reference. This therefore carries through to the resulting `page` because the sort key is necessary for the `Page.next` or `.previous`. For instance, `@AFTER(...)` can only be used in combination with `@SORT(...)`. This seems a bit questionable but may be okay for now. The issue is that we are implicitly and covertly altering the effective URI used in the read, and subsequently we are implicitly and overtly modifying the next/previous URIs to have the sort key on them. This "works" under current assumptions, that the client will just keep reading from the next/previous manner and doesn't mind having the sort key added implicitly.

What if the client calls a delete on the altered reference? I'm not sure what ERMrest does when a delete URL includes a `@SORT` or `@BEFORE` parameter. Maybe it doesn't matter. Maybe it does and if so we can strip them off (again implicitly)? Just something to note and look into.

**Comment by karlcz** [comment]
Hmm, a reference to a recordset using paging and a reference to a single record should not get mixed up. I think it would be a mistake to call DELETE on a recordset from our apps until we get something much more sophisticated as far as UX.

The logic about adding sort and paging could check for whether we have a unique key predicate and treat that case differently, i.e. don't offer prev/next references and don't add paging modifiers to the URL.

We need that sort of unique entity reference test anyway, in order for recordedit to know whether it should be in record submission, record edit, or exception case.

**Comment by robes** [comment]
stale
