### ISSUE TITLE
Reference.related should return a sorted set of references

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrestjs#161]
Reference.related needs to return a set of references that is sorted based on a default heuristic.

Assigning to @hongsudt to fill in the default order that we want to use. It was discussed to have it alphabetical with some other circumstances when two related references have the same displayname.

**Comment by RFSH** [comment]
When visible-foreign-keys annotation was not defined in the table, we should sort related references using the following steps:
1. Sort by display name.
2. Sort by position of key columns in the table.
3. Sort by position of foreign key columns in the related table.

**Comment by RFSH** [comment]
This issue was resolved by #167 PR. This should be closed when PR is merged.
