### ISSUE TITLE
isHTML and Tuple.value should be in sync 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#165]
The code shouldn't assume that isHTML will be called after the Tuple.value is called. It should check wiether Tuple._value is defined, if not, it should call Tuple.value to have both set appropriately.

**Comment by hongsudt** [comment]
@howdyjessie can you review this issue?

**Comment by howdyjessie** [comment]
@hongsudt I've already commented on the PR associated with this issue.
