### ISSUE TITLE
mustache template documentation

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#169]
@chiragsanghvi are you working on documentation of how to use mustache template to support null handling?

**Comment by chiragsanghvi** [comment]
Yes, I was working on the same. Karl suggested me to change the samples which I need to do.

https://github.com/informatics-isi-edu/ermrestjs/wiki/Using-%22Column-display%22-Annotation

**Comment by chiragsanghvi** [comment]
@hongsudt can we merge the PR #163  ?
