### ISSUE TITLE
Expose column type in Columns

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/ermrestjs#17]
Is it possible to find the type of a column from ERMrest? Right now, Columns have `displayName`, `hidden`, and `name`, but it'd be nice to have `type` as well for the data entry app.

**Comment by karlcz** [comment]
+1 I think you'd need this in most other apps to choose type-specific presentations too, right?

**Comment by howdyjessie** [comment]
@karlcz Yeah definitely.

**Comment by robes** [comment]
This is probably already in the revised ermrestjs api. We just need to get that in Jessie's hands.

**Comment by howdyjessie** [comment]
It works! Thanks :)
