### ISSUE TITLE
Use attribute group api instead of entity api when making a call to ermrest

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#171]
The attribute group api will allow all the foreign keys to be fetched together with the main entity. 
Currently, it is assumed that all foreign keys are not null. @karlcz will extend the API to support null foreign keys. 

The purpose of this issue is to re-factor the ermrest call without impacting the rest of the apps. So `Tuple._data` should remain the same. Let's save other outbound linked data in Tuple._linkedData. 

![img_20160826_143923-1](https://cloud.githubusercontent.com/assets/414732/18022399/61529506-6ba3-11e6-9b50-df5035133b44.jpg)

**Comment by RFSH** [comment]
`Related.read()` uses the url that users specify by `ERMrest.resolve(url)`. So it can be "entity", "attribute", "attributegroup", or "aggregate" ermrest api call ([parser](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/parser.js#L82) allows all these api names). However the current "reference.js", only supports "entity" ermrest api and it doesn't understand the value that other apis return.

Based on these, it was assumed that ermrestjs is only using "entity" api; which is not correct and this decision is made by the user (e.g. chaise apps).

After discussion with @hongsudt, we decided that as a temporary solution for this issue, we change the api to "attributegroup" and ignore the api (service) that user has specified.
