### ISSUE TITLE
Refactor Tuple.displayName to use row-name context

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#179]
Currently, the code looks explicitly for `row_name` property in 2016 Table Display Annotation, use the old templating library and doesn't support markdown.  Table Display annotation has been updated to unify the use of `row_markdown`. So Tuple.displayName should be looking into the `row_name` context and support the markdown specified in `row_markdown`. 

If the `row_name` context is not specified, it should implement a heuristics to derive the displayName in this order (case-insensitive): 
* use column named `title`, if it exists and not null,
* use column named `name`, if it exists and not null, 
* use column named `term`, if it exists and not null,
* use column named `label`, if it exists and not null,
* use column named `id`, if it exists, a text field, and not null,
* use the shortest unique not null keys that are not serial column only. In the case of composite keys, append the column value with `:` as a separator.

**Comment by hongsudt** [comment]
@karlcz @robes does the heuristics make sense?

**Comment by robes** [comment]
This makes sense to me. Only comments:
* Although I think this is totally subjective, I might favor an order of `id` -> `name` -> `title` instead
* I assume "if it exists" implies "_and not null_"

But I would agree with it as is.

**Comment by chiragsanghvi** [comment]
@hongsudt If the table doesn't has a key, `shortestkey` returns all columns. How should I handle this case ?

**Comment by hongsudt** [comment]
What about we just set it to empty string. 
* Under record, it doesn't make sense to show all columns when you see all of them on the page.   
* Under recordset, this will be in the context of foreign keys. If the row_name is empty, we can use other heuristics e.g. use the foreign key value.  
@robes @karlcz What do you think? 

@chiragsanghvi I added "term" as one of the column names to accommodate for vocabulary tables. See the updated issue above.

**Comment by robes** [comment]
@hongsudt I suppose that's fine.
