### ISSUE TITLE
Reference.contextualize.compact behaves oddly

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrestjs#184]
When I contextualize a reference with the `detailed` context, I can verify that the references are very similar with slight variations. When I use the compact context in `record2`, all of my related references are contextualized to the same reference.

The request for reference.related does in fact return `x` number of distinct references, but once I start contextualizing them, each of my related references are the same. One oddity is that it ends up being the 10th related reference in the set of 27 that are returned, in the case that I'm testing.

**Comment by RFSH** [comment]
`contextualize.detailed` and `contextualize.compact` use the same function and the only difference is the context string they use. So they should behave the same.

Are you sure for compact you're using `compact` and not `compact/brief`? The `contextualize.compact` in reference is using `compact` as the context name but the chaise issue is about `compact/brief` (which is not implemented in reference).
