### ISSUE TITLE
Page.content support for compact/brief

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#188]
If the context is compact/brief, at the end of the table display, if there are more elements to be displayed (e.g. Page.next is not null), there should be a navigational link to guide user to the recordset or search app. 

`Click here to access more records` 

This issue is pending on #186, and https://github.com/informatics-isi-edu/chaise/issues/563 for search app. The test should cover both recordset and search.

**Comment by karlcz** [comment]
Also, the navigation link should be to the **entire** dataset in that other app, **not** something that starts at the next page.  So the presence of the Page.next reference tells us we need to provide a link, but we do not use that reference to get the actual link information!

**Comment by chiragsanghvi** [comment]
@hongsudt Should I be using the permalink for that reference to build the link  ?

**Comment by hongsudt** [comment]
@chiragsanghvi @jrchudy I am wondering whether this should be done at the app level since it already has to do the same for the tabular display type? This way, the text and the link can come from the same logic. Is there any strong reason not to do this? 

As for the app to use, it should look for the 2016 app_links annotation and if doesn't exist, the default should be recordset.

**Comment by jrchudy** [comment]
This should be done in chaise rather than ermrestJS as we discussed in standup this morning (Friday).

**Comment by hongsudt** [comment]
@chiragsanghvi I am closing this issue..
