### ISSUE TITLE
Update Tuple.values return object

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/ermrestjs#189]
Right now Tuple.values return and array of values. Chaise apps have to check whether each value is HTML with Tuple.isHTML for display. Update Tuple.values to return an array of {value, isHTML} objects.

**Comment by hongsudt** [comment]
Let's not focus on this at the moment though.

**Comment by robes** [comment]
@hongsudt can we all discuss this?

**Comment by robes** [comment]
Is the `isHTML` flag possibly different for different tuples of the same relation (reference)? Then I could see it might need to be on the tuple and not on the column definition.

**Comment by robes** [comment]
I took a look at where `isHTML` is assigned. It is essentially a function of the column type (is col type is markdown, ishtml is true) with the exception that if the tuple value is empty or null then ishtml is false. I don't understand why that exception is important. This really seems like a function that belongs in the `Column` object.

**Comment by karlcz** [comment]
Would be a nice time to change it to isMarkdown if we're refactoring...
