### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#19]
We need to develop a set of `Error` subclasses. Initially, we can create a shallow hierarchy that directly maps to the errors returned by ERMrest (e.g., 403 Forbidden, 409 Conflict, etc.), plus any additional error subclasses for things specific to the client API as needed.

Then we need to update our error reporting:
- `throw` instances of these error classes from functions that return immediately, like `Schemas.get(name)`
- pass instances of these error classes as the `reason` parameter in the `reject(reason)` callback of our APIs that return promises, like `Entity.get(filter, limit, columns, sortie)`

The error classes themselves could be defined in a new module like `ERMrest.Errors` in a new `errors.js` script in the repo. (I don't have a strong opinion on this.)

**Comment by karlcz** [comment]
How do we plan to handle errors in async/promise scenarios?  Are we going to be able to reuse the same exception models to represent an error that has to be caught/interpreted later via some callback?

**Comment by robes** [comment]
If I understand this correctly. Errors that are reported by promises are passed as the parameter to the client via the anonymous `failure` function. Like this:

```
var p = some promis
p.then( function(...) { /* success case */ },
function(error) {
  /* the parameter list could be anything we want it to be here 
  but for example a single parameter to report the error */
});
```

What I might suggest exploring is:
- define a set of classes to represent errors
- throw the error in a synchronous call
- return it as the parameter of the failed side of the promise callback

Actually according to Angular's style, they call this the reject function with a reason parameter, e.g., `reject(reason)`.

https://docs.angularjs.org/api/ng/service/$q

And I don't think there's anything special about the classes that can be used in an exception or a reject/reason (of a promise). We should be able to use a common error model.
