### ISSUE TITLE
Parse URL with related tables

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/ermrestjs#190]
Right now ermrestjs only parses simple URL with the projection schema and table. Now it needs to handle complex URL with related tables so that when record-two links related tables to recordset, recordset can show the right table.

**Comment by hongsudt** [comment]
This should have been taken care of by Reference.related. Please also take
a look at the alternative tables and app_links before you do any work on
this.

**Comment by hongsudt** [comment]
The current recordset assumes that the table to be displayed is the left most S:T in the url, which is not the case when tables are joined. 

 `S:T1/k1=v1/k2=v2/.../(k1,k2,...)=(S:T2:fk1,fk2,...)` will return S:T2 as the context of the request.

If we split path on "/", then 
- items[0] is the base table 
- items[1]...items[n-2] are filters for key (composite conjunction) 
- items[n-1] is a join to related table where - LHS: columns from base table - RHS: colums from related table where the first column is in the form `S:T:C`, and 2nd column is in the form `C`. 

In this case, ermrest will return the right most table. Ermrestjs needs to set up the right table for the above url.

**Comment by hongsudt** [comment]
@robes should the plan be to check for the pattern above and if so, set the correct table for the reference. We probably need to work on a parser soon, but in the meantime I want the apps to support a simple url.

**Comment by karlcz** [comment]
It's worth noting that the URL structure described above is true only under limiting assumptions for how the record and recordset apps will navigate between each other:

1. The entity reference is always of the form `S:T/k=v`.
2. The related-entities reference is always of the form `S:T/k=v/(k)=(S:T2:fk)` (where the joining columns MAY be other than the entity's key constraint columns in the general case).
3. A single related-entity reference is then of the form `S:T2/k=v`.

We will not build deeply nested joins as we navigate between entity and related-entities references since we can always form a canonical reference using the primary key constraint.

**Comment by robes** [comment]
Right, I think there are these simplifying assumptions based on the URLs that will be generated by the record(-two) and recortset apps.

However, the parser is only really needed to support URLs that are passed to the app by the client. That does not seem to be the case for related references? The only URL structures we need to support in the parser are those URLs that would be inputs from Chaise to the `ERMrest.resolve(...)` function. The litmus test here is "do you expect these URLs to be formed from the fragment ID of the Chaise Recordset app?" More concretely, will a Chaise fragment ID contain a data path like the one given above `S:T1/k1=v1/k2=v2/.../(k1,k2,...)=(S:T2:fk1,fk2,...)`?  That wasn't my expectation.

So I kind of imagine maybe we are building this URL internally and then using our own parser? That may not be necessary.

(Correct me if I'm wrong...)

**Comment by karlcz** [comment]
@robes: If we expose the "see all" link for a related-entities table, that
will be a link to the same joined path in the recordset app.  That app
then needs to expose the per-row link back to individual records again.
