### ISSUE TITLE
Test "tuple displayname should return 'id:label' column" sporadically fails

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrestjs#195]
The "tuple displayname should return 'id:label' column" test sporadically fails when the unit tests run locally and on the travis server.

**Comment by chiragsanghvi** [comment]
This is because the **displayname** is computed using the [shortestkey](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/core.js#L655) parameter of **table** class. 
The order of the columns returned by `shortestKey` getter keeps changing, which is the reason the testcase fails. 

 @shinyichen can you fix it ?

**Comment by hongsudt** [comment]
@shinyichen can you take a look at this?

**Comment by shinyichen** [comment]
I traced the problem all the way back to reading of the json payload of `keys` in the schema, 
```
"keys": [
  {
    "comment": null,
    "annotations": {},
    "unique_columns": [
      "id",
      "description"
    ]
  }
],
```
where the ordering of `unique_columns` is not preserved. I can't figure out why since json array ordering should be preserved.

**Comment by karlcz** [comment]
Note that keys are defined in ERMrest as a set of columns, **not** an ordered list.  So there is no guarantee that the JSON serialization will have the same order on individual introspection calls to the same catalog much less to different catalogs using the same schema.  If you want a canonical order, you need to do that yourself, e.g. by sorting lexicographically.

**Comment by shinyichen** [comment]
Will fix this issue by sorting the keys alphabetically.
