### ISSUE TITLE
implement Reference.create

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#197]

**Comment by robes** [comment]
Josh and I reviewed this in detail. For starters we'll have the create(...) function take an array of objects which should correspond to the columns _not_ set by defaults.

**Comment by robes** [comment]
It just occurred to me... @jrchudy Maybe we should extend that create signature to take the list of defaults as an array of column definitions. That way its up to the client to determine which columns they wish to use defaults for.

**Comment by jrchudy** [comment]
But aren't the defaults defined by which columns are not showing (i.e. the visible_columns annotation) and any columns that have a `type.name` property set to `serial`?

**Comment by jrchudy** [comment]
Or should we allow a column to be a default and shown in the UI for input. If they don't define a value for that input, use the default instead? 

That's the only case I can think of where the user would want to alter the defaults that are being used.

**Comment by karlcz** [comment]
Almost any field could support a "use default" decision by the user. Serials are just the most obvious case where they'd want to and where we might not even want to let them override the default behavior.

Whether the UX is to interpret blanks as "use default" or have something else like a checkbox, this decision is not something you can solely predict from the model content.  Therefore, the ermrestjs API needs a way to configure different possible requests.

**Comment by jrchudy** [comment]
PR #212 merged. Closing this issue.
