### ISSUE TITLE
make all won't work on mac if java is not already installed

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#207]
We include ccjs (google's closure compiler) as a dependency. It depends on java. The ccjs package seems to have a link to openjdk that is no longer valid...

A workaround is to get the official jdk from oracle and install it. Then the java dep is satisfied and it skips this. We should at least document this...

**Comment by robes** [comment]
There's probably not much we can do about this. The npm package maintainer should sort this out.

**Comment by hongsudt** [comment]
@RFSH can you document this and close the issue?

**Comment by RFSH** [comment]
Seems like the `closurecompiler` that we are currently using is deprecated. We should move to the new version of it. We have two choices:
- [google-closure-compiler-js](https://www.npmjs.com/package/google-closure-compiler-js): Dosen't need Java. But "It is an experimental release - meaning some features are not available and performance may not be on-par with the Java implementation. [Details Here](https://github.com/google/closure-compiler-js#transpilation)"
- [google-closure-compiler](https://www.npmjs.com/package/google-closure-compiler): Requires Java.

**Comment by robes** [comment]
Worth trying the js version to eliminate our java dependency.

**Comment by dhanashritidke** [comment]
1. [google-closure-compiler-js](https://www.npmjs.com/package/google-closure-compiler-js): The package successfully removes the dependency on Java. But the java-script version of the closure compiler is slower than the corresponding java version. i.e. [google-closure-compiler](https://www.npmjs.com/package/google-closure-compiler)
2. **Note** for the package "google-closure-compiler-js": This is an experimental release - meaning some features are not available and performance may not be on-par with the Java implementation - [details here](https://github.com/google/closure-compiler-js#transpilation).
