### ISSUE TITLE
Binary association table not recognized

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#209]
I could be wrong, but it appears that some pure binary association tables are not being recognized as pure binary association tables.

First, can you see if there is anything wrong with this definition of (what should be) a binary association table, in case I'm overlooking something wrong with it?

https://dev.isrd.isi.edu/ermrest/catalog/1/schema/legacy/table/dataset_mouse_age_stage

This should be an association table linking `dataset <- dataset_mouse_age_stage -> mouse_age_stage`.

However, if you look at the (new) record app what you see is that it shows dataset_mouse_age_stage instead of linking all the way to the mouse_age_stage table as it should have.

https://dev.isrd.isi.edu/chaise/record-two/#1/legacy:dataset/id=4672

**Comment by karlcz** [comment]
@robes what is missing is a unique key spanning the two foreign keys. Right now, it could store duplicates of the same foreign key combination and cause weird join results if interpreted as a pure association...

**Comment by robes** [comment]
ah, so that's what was missing. mystery solved.
