### ISSUE TITLE
Descriptions that might cause confusion

### ISSUE THREAD

**Issue by mashuaihh** [informatics-isi-edu/ermrestjs#21]
> <a name="ERMrest.Table+createEntity"></a>
> #### table.createEntity(data, defaults) ⇒ <code>Promise</code>
> Creating a new entity. If the promise is fullfilled a new entity has
> been created in the catalog, otherwise the promise is rejected.
> 
> **Kind**: instance method of <code>[Table](#ERMrest.Table)</code>  
> **Returns**: <code>Promise</code> - Returns a promise.  
> 
> | Param | Type | Description |
> | --- | --- | --- |
> | data | <code>Object</code> | The entity data. This is typically a dictionary of attribute name-value pairs essentially. |
> | defaults | <code>Object</code> | An array of default columns. |

I found this piece of description might be causing confusion. In the implementation (master branch of ermrest.js), both data and defaults parameters are of **Array** type.  The **Object** type of **data** parameter, combined with "a dictionary of attribute name-value pairs" might be misleading. 

I think something like **An array of dictionaries of attribute name-value pairs** might be a better description here.

**Comment by karlcz** [comment]
I don't know why this is assigned to me.  I agree with the comment that the input data is an array of per-row records mapping column name to value, and the defaults parameter is an array of column objects from the model.

**Comment by robes** [comment]
This looks like an issue related to the original and now deprecated API. If so, let's just close it with wontfix since we've moved to a new API.
