### ISSUE TITLE
Use association table name as Reference.displayName 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#210]
In the case of binary association, if the inbound `to_name` is not specified, can we set the default inbound name to be the association table display name instead of the end table name? E.g. I have an association table named `protocol_author` that links between `protocol` and `person`. Use `Protocol_Author` in the nested table is more meaningful than `person`.

**Comment by hongsudt** [comment]
Also see the detail from issue #215.

**Comment by RFSH** [comment]
#213 fixed this issue.
