### ISSUE TITLE
PUT and DELETE table entries

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/ermrestjs#22]
@shinyichen commented on [Fri Apr 01 2016](https://github.com/informatics-isi-edu/ermrest/issues/63)

**Comment by hongsudt** [comment]
@jrchudy I am assigning you as a reviewer of this issue since you will be using them.

**Comment by jrchudy** [comment]
I will make sure to note this when I am testing.

**Comment by jrchudy** [comment]
This is working probably for putting and deleting comments and annotations.
