### ISSUE TITLE
implement Reference.update

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#221]

**Comment by hongsudt** [comment]
The current version has a limitation that when the unique columns are updated, it will always throw a 409 conflict e.g. `Error 409 Conflict The request conflicts with the state of the server. Input data violates model. ERROR: duplicate key value violates unique constraint "experiment_pkey" DETAIL: Key (id)=(2) already exists.`

@jrchudy please make sure that the new version will support this case. The attribute group API needs to be used for this.

**Comment by robes** [comment]
it will

**Comment by hongsudt** [comment]
Make sure to use etag pre-condition in put and delete.

**Comment by jrchudy** [comment]
This is resolved by PR #238.
