### ISSUE TITLE
Fix lint warnings/errors

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#23]
I fixed the makefile. It wasn't fully linting the source so there is some lint output to be reviewed and fixed. To lint the project, just run this from the project directory:

```
$ make lint
```

This applies just to the `refactor` branch.

**Comment by shinyichen** [comment]
I fixed and removed the warnings.

https://github.com/informatics-isi-edu/ermrestjs/commit/364972cd57f7fbf02ceef7a374aeea97267fe68c
