### ISSUE TITLE
a function Column.inputDisabled that incorporate generated and immutable annotation

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#230]
provide a function `Column.getInputDisabled(context)` that takes the context as a parameter and depending on the context, return InputDisabled value based on generated and immutable annotation. 

Potential return values:
* `true` : do not allow user input 
* `false` : allow user input 
* `{message:"the message to show in place of the column value"}` : do not allow user input and the `message` should be shown in-place of the column value.  

Rules for setting the value: 
* When the context is create
  * if the column is generated, then inputDisabled={message:"automatically generated by the server"}
* when the context is update
  * if the column is generated, then inputDisabled=true
  * if the column is immutable, then inputDisabled=true

informatics-isi-edu/chaise#432 depends on this function.

**Comment by howdyjessie** [comment]
PR #237 has been merged; closing now.
