### ISSUE TITLE
How to attach Reference to PseudoColumn

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#242]
Currently we are attaching it before getting the values of the reference and therefore cannot use the direct link to the reference. Instead the reference that we create is just based on the correct table and without any filters. That is instead of pointing to just one row, the reference will point to all the rows of that table.

We might need to change this behavior based on different use cases.

**Comment by hongsudt** [comment]
I am closing this issue since it is being used as is in the recordedit. We can open a new issue when we have a different use case.
