### ISSUE TITLE
linked data is null

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#249]
@RFSH The psuedo-column is still buggy..  If you try to go to a few tables in gpcr with foreign keys, it will complain about linked data is null, and throw an error message.. 

Please revert your pull request and solves this problem. 

Check this link: 
https://data.gpcrconsortium.org/chaise/record/#1/experiments:analysis_sop/title=SEC%26%23x2F%3BSDS-PAGE%20%28Standard%20Analysis

https://dev.gpcrconsortium.org/chaise/record/#1/assets:sec then click any of the row to get to record page.

**Comment by RFSH** [comment]
The problem is that I didn't consider the case that foreign keys might be null. If the foreign key data is null, what should I do? return null as its value (ignore it)? or use the `show-nulls` context of the column to figure out what the value should be?

**Comment by RFSH** [comment]
Also the first link is not related to this issue, it's showing that error because there's no record with that criteria in [ermrest](https://data.gpcrconsortium.org/ermrest/catalog/1/entity/experiments:analysis_sop/title=SEC%26%23x2F%3BSDS-PAGE%20%28Standard%20Analysis).
