### ISSUE TITLE
Formatted dates are incorrect (off by one)

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#250]
I see this in Chaise apps but assume it is an ermrestjs problem.  I think this should be fixed asap @hongsudt 

Columns of type `date` are being displayed in recordset and record reformatted (e.g. using slashes instead of dashes) and having the day prior to the actual date in the table.  When I go to record-edit and see the existing value in an input field (which bypasses the formatting I think?) it shows the correct value.

It seems I missed this and it has been going on for quite a while, as I see it in production systems on an older tag as well as development systems.  For an example with latest master code: https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Subject

Note the `Issue Date` column has a day prior to the date encoded in the `ID` column.  But the `ID` was actually generated in the server using the `Issue Date`. View it in record: https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Subject/ID=ZfCza20160815A  and you see the same discrepancy. But view it in recordedit and it is correct: https://synapse-dev.isrd.isi.edu/chaise/recordedit/#1/Zebrafish:Subject/ID=ZfCza20160815A

**Comment by hongsudt** [comment]
@chiragsanghvi are you working on this issue?

**Comment by chiragsanghvi** [comment]
I have fixed this issue on last Thursday.

Sent from my iPhone

On 31-Oct-2016, at 7:26 PM, Hongsuda <notifications@github.com<mailto:notifications@github.com>> wrote:


@chiragsanghvi<https://github.com/chiragsanghvi> are you working on this issue?

-

**Comment by karlcz** [comment]
I can confirm that this is working for me now.
