### ISSUE TITLE
add accession_id in the hueristics

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#256]
Many of our tables are now using accession_id or accession_number for unique ids.. We should add these terms to the heuristics and they should have higher priority than id.

**Comment by RFSH** [comment]
@hongsudt Is this related to row name?

**Comment by hongsudt** [comment]
Yes. We might have to add some more heuristics to the row-name.

**Comment by hongsudt** [comment]
It is now working as expected on gpcr-dev. So I am closing this issue.
