### ISSUE TITLE
Reference.read() add alias needs to account for search filter in the URL

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/ermrestjs#263]
This piece of code was written while search capability was being written. Therefore it did not account for the URL having a search filter at the end. 
https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/reference.js#L618-L623

**Comment by hongsudt** [comment]
@shinyichen Do we need to support this for the first round of recordedit?

**Comment by shinyichen** [comment]
It's a very small change. Shouldn't doesn't affect anything right now because recordedit or record don't have search filter.

**Comment by RFSH** [comment]
@shinyichen Does it cause any problems? Urls such as [this](https://dev.isrd.isi.edu/chaise/recordset/#1/legacy:dataset/owner=Axel%20Visel/*::ciregexp::new@sort(id)?limit=15) will work which has both search and filter.
