### ISSUE TITLE
support generated and immutable annotation in pseudo column

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#265]
When a foreign key is defined as generated or immutable, these properties should be propagated the same way as the regular columns. Please check old issues #230 on how these properties should be mapped to.

**Comment by RFSH** [comment]
These are the heuristics for choosing the right value for `PseudoColumn.getInputDisabled()`:
  - If it's a simple foreign key, use the column's result.
  - If it's a composite foreign key,
    - In `create` context,
      - If all columns have `generated` annotation, return the "generated message".
      - else return`false`.
   - In `edit` context,
     - If one of the columns has `immutable` annotation, return `true`.
     - If all of them are generated, return `true`.
     - else return `false`.
  - In other contexts return `true`.
