### ISSUE TITLE
Support session login and logout

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/ermrestjs#28]

**Comment by shinyichen** [comment]
Reopend. Need to write login/logout the angular way and put them in the common module.

**Comment by robes** [comment]
We discussed this, and just adding comment here for the record. My vote is not to have login/logout in ermrestjs and leave that for the chaise common module.

**Comment by shinyichen** [comment]
Decided to remove session. Let authentication be a service in Chaise.
