### ISSUE TITLE
Refactor Reference.columns

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#290]
Currently `Reference.columns` returns a list of `Column` and `PseudoColumn` objects. Instead, we should introduce a new `ReferenceColumn` class and return a list of these objects. 

The `Reference.columns` calls the `Columns._contextualize` which returns the list. We can bring the logic that is used in `Columns._contextualize` outside of the `Columns`, remove the `PseudoColumn` class and let the `ReferenceColumn` constructor deal with PseudoColumn creation.

```javascript

// reference.js

// Reference:
get columns () {
  if (this._referenceColumns === undefined) {
    this._referenceColumns = [];
    /*
    * TODO: the whole logic of visible-columns will be here, 
    * adding a column:
    *   this._referenceColumns.push(module._createReferenceColumns(this, column));
    * adding a pseudo-column: 
    *   this._referenceColumns.push(module._createReferenceColumns(this, column, foreignKey));
    */
  }
  return this._referenceColumns;
}

/*-----------------------------------*/

// core.js

// If we want to reuse the Column class prototype and constructor, this class must be in core.js.
function ReferenceColumn(reference, column, foreignKey) {

  if (typeof foreignKey ==  "undefined") { // column
   
    // make sure all the properties of column are defined here by calling its constructor
    Column.call(this, column.table, column._jsonColumn);

  } else { // pseudo-column
    // make sure all the properties of column are defined here by calling its constructor
   Column.call(this, foreignKey._table, column._jsonColumn);

   // TODO the whole logic of PseudoColumn will be here.
  }

  // TODO define context-based or any other function that needs access to reference in here.
}
ReferenceColumn.prototype = Object.create(Column.prototype);
ReferenceColumn.prototype.constructor = ReferenceColumn;

module._createReferenceColumns = function (reference, column, foreignkey) {
  new ReferenceColumn(reference, column, foreignkey);
};

```

@robes Can you please take a look at this approach?

**Comment by robes** [comment]
@RFSH That is more like an inheritance approach. What we had in mind was a proxy or facade approach (technically, I think the OO community calls this approach "Composition"). You define `ReferneceColumn` independently of `Column` but you match its function and property interfaces, where needed. A limited example:

```javascript
function ReferenceColumn(reference, column) {
  this.reference = reference;
  this.base = column;
}

ReferenceColumn.prototype = {
  get name() {
    return this.base.name;
  }

  get displayname() {
    return this.base.displayname;
  }
}
```

And then of course you modify the above behavior based on contextualization. I do agree with your suggestion to replace the `PseudoColumn` with this new `ReferenceColumn`. We should definitely do that. HTH

**Comment by RFSH** [comment]
At first I thought about facade, but the problem with that is we should list all the attributes that we have in Column.
Is this is the intended behaviour to list all the apis rather than copying them automatically and change the ones that needs to be changed?

**Comment by robes** [comment]
I wouldn't say "list all the apis" rather list _just_ the APIs that are needed rather than copying them all.

**Comment by karlcz** [comment]
I don't think you necessarily want/need ALL column attributes and
methods to leak out of referencecolumn.

Rather, there is a core set of things we actually need that should be
proxied and other stuff remains hidden.  We can revisit that
distinction over time to add more proxy methods.

When things are contextualized, there really shouldn't be that many
reasons to do ad hoc access to other column properties from an app.
