### ISSUE TITLE
Reference.create creates a page instead of a url to be redirected to for multi-entry insert 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#297]
Currently at the end of the multi-entry creation, the app navigates to a recordset with specific set of entries newly created. Due to the url length limitation (2083 characters), the call might fail. 

To address this problem, instead of throwing away the data getting back from ermrest after the creation, this data should be used to create a Page, so that the newly created entries can be rendered using the resultset directive. 

This issue requires that the underlying psuedo-columns can handle the case when the foriegn key entries will not be available to create proper row-names #296  .

**Comment by jrchudy** [comment]
I can verify that this is returning a page object now with the data populated as we would expect for the resultset view of the `recordedit` app.
