### ISSUE TITLE
create a pseudo-column that contains a list of actions that users can do  

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#298]
- This column should be the first column (left most). 
- The column name should be "Actions". The value should be linkable icons (with tooptips) for `view`, `unlink` or `delete`, and `edit`.
- In the compact/brief context, if the related table is derived based on pure and binary association table, `unlink` should be provided, otherwise, `delete` should be provided. `Unlink` deletes an entry in the association table. `Delete` deletes the actual row in the table. 

@robes @karlcz I am making an assumption that we can determine whether the user can delete or create at the row level, which I am not sure whether it has to eventually be an asynchronous call or not.

**Comment by robes** [comment]
@hongsudt I think the reference api covers row-level security but of course that is not and cannot be implemented given the current mechanism that ermrest uses based on postgres row level security.

**Comment by hongsudt** [comment]
@shinyichen we decided to implement this in chaise. I am moving this issue to chaise repo.

**Comment by hongsudt** [comment]
Issue moved to [informatics-isi-edu/chaise #838](https://github.com/informatics-isi-edu/chaise/issues/838) via [**ZenHub**](https://www.zenhub.com/)
