### ISSUE TITLE
Column-display markdown_pattern ignored for foreign key consituents

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#302]
1. I put the bare column name in my visible columns list (not the constraint name)
2. I defined a column-display annotation with markdown pattern for this column

All of this was ignored, and the UI behaved as if I had put the constraint name in the visible column list. It should instead respect my instructions.

**Comment by hongsudt** [comment]
This is because we automatically derived foreign keys from the visible column list.

**Comment by hongsudt** [comment]
@RFSH we should take out the heuristics that automatically derive the forieng keys from regular columns in the visible list.

**Comment by RFSH** [comment]
@karlcz This should be fixed now. Can you please verify?

**Comment by karlcz** [comment]
I confirmed that this works now.
