### ISSUE TITLE
Cannot interpolate columns with "." in name

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#303]
I need to be able to interpolate all columns even if they have names that mustache does not like, e.g. with a `.` character (or any other that mustache might disallow).

- ideally, we should use a template system that does not make assumptions about names
- alternatively, we might use a workaround like string-replacing or otherwise "escaping" unsafe characters while producing the markdown environment, so someone writing an annotation can use this mangled name to access the column data

**Comment by chiragsanghvi** [comment]
I think we might need to get rid of Mustache as escaping also won't work. In addition other template languages also won't support it as `.` in javascript is a property of an object. 

We can use handlebars, but for it you need to explicitly enclose the column-name in quotes. 

```js
// Change this object to change your values
var obj = {
   ID: "Alice's Adventures in Wonderland \t what is this",
   "this.is": "some name"
};
console.log(mustache.render('{{ID}} - {{"this.is"}}', obj));

var handlebars = require("handlebars");
console.log(handlebars.compile('{{ID}} - {{"this.is"}}')(obj));
```

We can switch back to the old string replacement. Which I am sure supports it, but it won't have the encode and other escaping stuff.


https://runkit.com/chiragsanghvi/57b4b5f94c7bbd13004b43f6

**Comment by hongsudt** [comment]
#escape has been used in real deployments.. So we need to be careful about
turning off features.

**Comment by hongsudt** [comment]
@karlcz can you please describe the workaround here..

**Comment by karlcz** [comment]
@hongsudt  it's the second option I described in the original issue.  Mangle column names when producing the environment object passed to the mustache interpreter, i.e. replace `.` or any other disallowed character with `_` when forming the object keys for the environment dictionary.

Then, the DBA can mangle the names the same way in order to be able to use guards or interpolation based on that column.

Don't worry about collisions.  If a DBA uses column names that differ only in `.` versus `_`, they can suffer the consequences...
