### ISSUE TITLE
API for retrieving aggregate functions

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#304]
We need a way to retrieve aggregate values associated with a reference such as count, min, max, etc. Should this be something like Referece.getAggregate(aggregateList). 

This API is needed for informatics-isi-edu/chaise#878 and will be useful for faceting to retrieve a range of a number/date column. 

check the flow listed on https://github.com/informatics-isi-edu/chaise/wiki/Faceting

@karlcz can a list of aggregate be specified to ermrest or do we have to do this one at a time?

**Comment by karlcz** [comment]
ermrest has both aggregate and attributegroup APIs which support a list of aggregate function "projections".  The aggregate API projects one row of results from an entire table or query set (i.e. grand total count, min, or max) while the attributegroup API projects one row of results for each group key in a table or query set (i.e. group-local count, min, or max for rows sharing the same group key).

**Comment by karlcz** [comment]
In practice, aggregates are implemented as a table scan and it will be cheaper to gather all desired statistics from the same table or query set in a single request rather than via separate requests, each of which has to scan the whole table again.

This whole table scan is also a limiting factor on huge tables since you will eventually run into HTTP request timeouts with millions of rows to process.

**Comment by RFSH** [comment]
Sketch of the proposed api is as follows:
```javascript
Reference.prototype = {
  /**
  * @param{AggregateFn[]} aggregateList list of aggregate functions
  **/
  getAggergate = function(aggregateList) {
    // TODO use the list to make the request and return data
  }

  get rowCount() {
    // TODO return the appropriate aggregateFn corresponding to row count of current reference.
  }
 
  //TODO other aggregate functions
}

ReferenceColumn.prototype = {
  get min () {
    // TODO return the appropriate aggregateFn corresponding to min value of this column
  }

  get min () {
    // TODO return the appropriate aggregateFn corresponding to min value of this column
  }

  //TODO other aggregate functions
}

AggregateFn.prototype = {
 // TODO should have a mapping of function to the actual uri that ermrest understands
}

// usage:
reference.getAggregate(reference.rowCount, reference.columns[0].min);
```

**Comment by hongsudt** [comment]
@RFSH Should the getAggregate take any number of arguments?

**Comment by jrchudy** [comment]
[For aggregate API documentation](https://github.com/informatics-isi-edu/ermrest/blob/master/api-doc/data/rest.md#aggregate-retrieval)
[For aggregate names documentation](https://github.com/informatics-isi-edu/ermrest/blob/master/api-doc/data/naming.md#aggregate-names)

You are not required to specify the `schema-name` but it helps to be specific in case multiple tables with the same name exist in different schemas.

For `rowCount`:
`GET ../ermrest/catalog/<catalog-id>/aggregate/<schema-name>:<table-name>/<alias>:=cnt(*)`
Data returned:
`[{ "<alias>": <count> }]`

for `countDistinctValues`:
`GET ../ermrest/catalog/<catalog-id>/aggregate/<schema-name>:<table-name>/<alias>:=cnt_d(<column-name>)`
Data returned:
`[{ "<alias>": <count-of-distinct-values> }]`

For `min`:
`GET ../ermrest/catalog/<catalog-id>/aggregate/<schema-name>:<table-name>/<alias>:=min(<column-name>)`
Data returned:
`[{ "<alias>": <min-value> }]`

For `max`:
`GET ../ermrest/catalog/<catalog-id>/aggregate/<schema-name>:<table-name>/<alias>:=max(<column-name>)`
Data returned:
`[{ "<alias>": <max-value> }]`

For `array`:
`GET  ../ermrest/catalog/<catalog-id>/aggregate/<schema-name>:<table-name>/<alias>:=array(<column-name>)`
Data returned:
`[{ "<alias>": <array-of-all-values>[] }]`

**Comment by robes** [comment]
The sketch looks like it would work. Not sure I like the API but that's mere aesthetics. I'd prefer an API like this.
```javascript
var promise = reference.groupBy( reference.column[i]... ).count( reference.column[j] ).read();
```
where `groupBy` returns a new refernece instance that is not fully resolved (or not 'concrete' yet), and `count` (or `min`, `max`, etc) fully resolves the reference and then 'read' does what read does and returns a promise.

But Karl is absolutely right, these are going to result in expensive table scans, so we do need to minimize the times we execute the query. My sketch above could still work by chaining some more.

```javascript
var promise = reference.groupBy( reference.column[i]... ).count( reference.column[j] ) \
    .min( reference.column[k] ).max( reference.column[p] ).read();
```

Where we've now chained some additional aggergate functions. Both this example and the example above will return relations and will have (unnamed or rather system-named) attributes. Just as in SQL you may want to rename these and could do it like so.

```javascript
var promise = reference.groupBy( reference.column[i]... ) \
    .count( reference.column[j], "count of column i" ) \
    .min( reference.column[k], "min of column k" ) \
    .max( reference.column[p], "max of column p" ).read();
```

The `groupBy` function could alternately be named `aggregate`.

Also, I suppose JavaScript does not have variable argument lists? If not, those varargs could instead be replaced with lists `[ reference.column[i], ... ]`.

**Comment by karlcz** [comment]
I'm not sure that OOPy style of chaining method calls is actually helpful here.

I don't think we should be having lots of hard-coded calls like this in our apps, but instead more generic/meta-programming structures where we convert a list of column definitions into a list of projections.  This would idiomatically use functional mapping or loops to build the list, and seems kind of pointless to try to use some chaining object as the accumulator for that result instead of just a normal list...

**Comment by hongsudt** [comment]
We could breakdown the tasks into the following phases: 
- [ ] column aggregates for integer column
- [ ] column aggregates for all column types
- [ ] table-level aggregate
- [ ] url-length handling
