### ISSUE TITLE
Need a developer guide

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#31]
We need a developer guide to help a novice to ermrestjs understand the basics of how to develop ermrest clients using the js api. It should over at least:
- getting server session (not 'session' in the authN sense)
- getting a catalog
- looking up one or more schemas
- looking up one or more tables definitions
- getting entities of a table
- adding entities to a table
- building data path queries
- getting entities from data paths
- etc.

It should also demonstrate:
- error handling in both exception cases
- and from failure reasons of promises

**Comment by hongsudt** [comment]
We already have this documented..  @jrchudy did you have a chance to move it to the wiki (or the other way around?)

**Comment by hongsudt** [comment]
Opps.. wrong one. I thought this is the style guide.

**Comment by RFSH** [comment]
Some of the steps are for the old `datapath` API. I'll make sure to include the ones that are still applicable.
