### ISSUE TITLE
automatically create linkable column value for unique key constraint

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#310]
Ermrestjs should automatically create a linkable value for a unique key constraint, similar to what we have done for the foreign key constraint.
In other words, we want to add new `ReferenceColumn` object to the list of columns that is returned by `Reference.columns`. These new columns will represent a key. 

### How to choose a key
- If `visible-columns` annotation was defined, we should create "linkable column" for all the keys that are in the `visible-columns` annotation. 
  - Duplicate or invalid keys will be ignored.
  - If a key has columns that are html (`markdown` typed or has `markdown_pattern` annotation), instead of creating a `PseudoColumn`, add its constituent columns.
  - If a key has columns that has `nullok=true`, add its constituent columns.
  - In entry contexts (`entry/edit`, `entry/create`, and `entry`), instead of creating a `PseudoColumn` for key, add its constituent columns.
- Otherwise, we should choose the key that (in any context other than entry contexts):
  1. None of its columns are html (`markdown` typed or has `markdown_pattern` annotation).
  2. All of its columns are not null.
  3. Has shorter length than other candidates; i.e. prefer simple key to composite key.
  4. Has better presentational type (e.g. prefer `text` to `serial`).

If we couldn't find a key with these descriptions, we should not create a `ReferenceColumn` for that.

### Attributes
The instructions on how to derive this new column attributes:

- comment: underlying key's comment.
- displayname: key columns display names separated with space.
- formatPresentation (value of column): 
  - If any of the key columns are html (markdown type or has markdown_pattren in column-display) should return "null value".
  - Otherwise, use key columns values separated with space for caption. The URL should refer to the current reference.
- name: `constraint name` of the key (same as foreignkey).
- type: markdown.

**Comment by RFSH** [comment]
@hongsudt @karlcz Should we add this "linkable column" in all the contexts? I don't think we should add them in edit and create context.

**Comment by karlcz** [comment]
I agree they don't make sense in edit or create.

**Comment by hongsudt** [comment]
You are right.. No linkage in the create/edit context. In edit/create
context, they should be treated as other regular columns.
