### ISSUE TITLE
Type enumeration needed

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#32]
I believe we've decided that we want an enumeration of types. I'm not sure whether this is a public API? Probably.

We could also consider having a Type hierarchy, if that would be useful. Currently we have a `Type` class and it has a `name` (string) field. I think we need specific type representation for each supported type. The fallback can be the base `Type`.

```
Type
  |----Numeric
  |     |---Integer (with subclasses for Int2, 4, 8...)
  |     |
  |     ----Float (are there subclasses for this? not sure)
  |     
  |----Text
  |     |---we might invent ShortText and LongText types in ERMrest (TBD)
  |     
  |----Date
  |
```

and so on.

We might just start with making this a simple enumeration of types. But the hierarchy would be useful if for instance wanted to know if something `is_a_number` and its okay if its `int2`, `float4`, etc.

At a minimum, we at least want an enumeration, right?

**Comment by robes** [comment]
@howdyjessie and @jrchudy could you point me to some code that does column definition type checking? thanks

**Comment by howdyjessie** [comment]
@robes We check columns' types in recordedit [here](https://github.com/informatics-isi-edu/chaise/blob/master/recordedit/form.controller.js#L187-L226).

**Comment by robes** [comment]
This might be a co-requisite of #83.

**Comment by RFSH** [comment]
@robes 
Why do we need enumeration for types? Is this going to be used alongside the `Type` class?
Are we going to use this enumeration just for lookup?

**Comment by hongsudt** [comment]
@howdyjessie Do you need to define this to hook up the pretty print to columns?

**Comment by howdyjessie** [comment]
To recap what I said to @hongsudt earlier: No, I didn't need to define this to hook up pretty print utilities to Column.formatvalue. I just use a switch statement that checks `column.type.name` to decide which utility fn to use.

**Comment by hongsudt** [comment]
I am closing this issue since we don't seem to need to do this.
