### ISSUE TITLE
Iframe integrates poorly into recordset and record apps

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#324]
The markdown iframe seems to introduce a huge amount of padding and also messes with the background color in a way that doesn't work well with our core apps.

https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Cropped%20Image@sort(Extract%20Date::desc::,ID)?limit=25

https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Cropped%20Image/ID=CropImgZfZdu20160901A6A

These two examples have iframes as the only content in their respective table cells but introduce a lot of wasted padding around them.

(Ignore the fact that the iframe content in these examples isn't resizing properly.. that's a separate problem with the embedded viewer at the moment.)

**Comment by chiragsanghvi** [comment]
I think this is fixed now in Chaise.
