### ISSUE TITLE
Can't use column values to specify iframe dimensions

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/ermrestjs#325]
I tried specifying:

```
{"row_markdown_pattern" : "::: iframe [{{{Name}}}]({{{url}}}){width={{Width}} height={{Height}}} \n:::"}
```

This rendered as
```
<iframe src="/chaise/viewer/#2/HE_Images:HE_Slide/ID=100" width=""></iframe>
```

for a row with Width=800 and Height=400

When I changed it to 

```
{"row_markdown_pattern" : "::: iframe [{{{Name}}}]({{{url}}}){width=1024 height=600} \n:::"} 
```

it worked as expected; however, I'd like to be able to specify different dimensions for different rows in my table.

**Comment by karlcz** [comment]
try putting a blank space to separate the closing }} of {{Height}} from 
the closing } of the iframe payload?

    {"row_markdown_pattern" : "::: iframe [{{{Name}}}]({{{url}}}){width={{Width}} height={{Height}} } \n:::"}

I am guessing this has tripped up the mustache template renderer.

**Comment by chiragsanghvi** [comment]
I think it should work, unless either of those fields are null/undefined. https://runkit.com/chiragsanghvi/5887bb20373c05001465a44b

**Comment by hongsudt** [comment]
@ljpearlman please review and close the issue.

**Comment by hongsudt** [comment]
I am closing this issue.
