### ISSUE TITLE
Handling 412 Precondition Failed error

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/ermrestjs#329]
cc @hongsudt @jrchudy @robes @karlcz @RFSH @chiragsanghvi 

There are 2 places in ermrestjs that currently use the If-Match request config which could run into a 412 Precondition Failed error if ETags are mismatching:

*Reference.update*
- Already accepts `tuples` as an argument so it already has Old Data (data before changes were made) and New Data (the data that's about to be submitted to DB).
- If update encounters a 412, do a Reference.read to get the tuples of the Current Data (data currently in DB). Compare the Current Data with New Data. If they match, just resolve the promise as usual (there's nothing to update). If they don't match, return a 412 error with the Current Data.
- If a rejected promise with a 412 is sent to Chaise, what should I do with the 412 error and Current Data in Chaise?
    - Show a modal with options to Overwrite and Cancel (and will Cancel refresh the page?)?
    - Try to point out where the Current Data differs from New Data in the RecordEdit UI?
    - Something else?

*Reference.delete*
- Doesn't accept any arguments so a tuples arg should be added here to access tuples.data
- As in update case, we do a Reference.read to get Current Data and compare it with tuples.data. If they match, delete the row and resolve the promise. If not, reject the promise with a 412.
- If a rejected promise with a 412 is sent to Chaise, do we 
    - Show a modal that tells the user something is out of sync with the server and then refresh the page once the user clicks the 1 affirmative button?
    - Show a modal with 2 buttons, Delete (lets the user delete anyway) and Cancel? What does Cancel button do — refresh the page?
    - Something else?

Thanks @RFSH for helping me organize my thoughts on this.

**Comment by karlcz** [comment]
For update the ermrestjs flow should be:

1. Update called with tuples having old and new data
2. PUT request sent with If-Match header and ETag from *old* data
3. 412 error received
4. GET request sent to get current data
5. Compare *old* and *current* data
  - If *old* and *current* are same, go back to step 1 but start using ETag from *current* data
  - If *old* and *current* are different, raise 412 with *old*, *current*, and *new* so client application can decide what to do

**Comment by howdyjessie** [comment]
A sketch from @karlcz on how to deal with 412 errors in ermrestjs:

![](https://cloud.githubusercontent.com/assets/4585431/23228069/19f54304-f8f0-11e6-9ce2-cf69a68afba8.JPG)

**Comment by howdyjessie** [comment]
PR #362 has been merged, closing now.
