### ISSUE TITLE
Bad URL encoding in markdown pattern generated URLs

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#338]
This appears to be a bug as far as I can tell. There is a related issue here https://github.com/informatics-isi-edu/cirm-project/issues/87.

We have a column that has the following annotation:
```
"markdown_pattern": "[{{Experiment ID}}](/chaise/record/#1/Microscopy:Experiment/ID={{#encode}}{{Experiment ID}}{{/encode}})"
```

The data value for the `Experiment ID` column includes a special character `&` in it. The URL that gets generated from the above annotation has been HTML encoded and has `&amp;` in it.

Unless I'm mistaken, from what I can tell the annotation looks correct from looking at the wiki for this.

https://github.com/informatics-isi-edu/ermrestjs/wiki/Template-and-Markdown-Guide#encoding-variables-for-url-manipulation

**Comment by hongsudt** [comment]
No.. If you don't want to have url encoded, you need to use {{{}}} for your
experiment id.

**Comment by robes** [comment]
I _do_ want it to be URL encoded. Instead, it is getting HTML encoded.

**Comment by karlcz** [comment]
There should be three braces, not two, surrounding the column name:

  ...{{#encode}}{{{Experiment ID}}}{{/encode}}

the two braces mode is a feature of Mustache templates that make sense
when building HTML from templates but never really makes sense the
way we use templates to build markdown strings.

**Comment by robes** [comment]
So the examples and documentation on the wiki are incorrect? Or am I reading them wrong, because the wiki shows an example specifically of building an URL and shows just 2 curly brackets rather than 3.

**Comment by hongsudt** [comment]
According to Karl, we should never use 2 braces.. IN fact, there is a task
to automatically convert 2 braces to 3 automatically, but we never get
there...

So maybe we should just update the document.

**Comment by karlcz** [comment]
I repeat: you should NEVER use the two-brace mode.  That means HTML
escaping, which never makes sense since we are not producing HTML. The
three-brace mode turns off this HTML escaping.

I wish we could turn off this part of Mustache in our system, but when
I asked it seemed like this would be invasive.

To have correct templates, you should ALWAYS use triple braces on
column names and then wrap with either the encode or escape blocks
to transform that into either URL-encoded or Markdown-escaped text.

karl

**Comment by karlcz** [comment]
If an example builds a URL with two-brace expansions, that is wrong.

**Comment by robes** [comment]
seems this is a documentation bug not an implementation bug. #339 opened.
