### ISSUE TITLE
Bad documentation for markdown URL encoding

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#339]
Details can be found in #338 

It appears this may be a documentation bug.

**Comment by hongsudt** [comment]
@chiragsanghvi can you please update the documentation, especially the difference between 2 braces and 3 braces..

**Comment by karlcz** [comment]
More that just the difference, we should emphasize that 2 braces 
makes no sense in Chaise.  We are NEVER using mustache to produce HTML
strings and so should NEVER use the expansion mode that applies
HTML escaping.

Instead, the user needs to use 3 braces AND either the escape function
to apply proper markdown escaping or the encode function to apply
proper URL encoding.

Ideally, we'd just hack our copy of mustache to apply markdown 
encoding for the 2 brace mode...

**Comment by hongsudt** [comment]
@chiragsanghvi let's update the document and close this task. It has been in this lane for too long.. 

I updated the [Markdown wiki](https://github.com/informatics-isi-edu/ermrestjs/wiki/Template-and-Markdown-Guide) and put your name where I want you to do the update. Search on @chirag and fill in what I have asked.

**Comment by chiragsanghvi** [comment]
@hongsudt Updated the documentation.
