### ISSUE TITLE
Paging broken on nulls

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#340]
See https://github.com/informatics-isi-edu/cirm-project/issues/89

When an actual JS `null` value is to be included in a page key in the ERMrest URL, it needs to be written as `::null::` to disambiguate it from a string that happens to be spelled `null`.

**Comment by hongsudt** [comment]
@robes please review the fixes.

**Comment by robes** [comment]
Looks like its working. thanks
