### ISSUE TITLE
Table alternatives link should not be in default visible foreign keys

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#342]
I think there is a little problem in the default visible foreign keys list when using the table alternatives feature.

See example: https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Subject/ID=ZfDsy20170111A 

1. Define a base table ("Subject" in my example)
2. Define an alternative view over the base table ("Subject Summary" in my example)
3. Define a psuedo key and fkey from alternative view to base table
4. Annotate the base table as having table-alternative view for compact and compact/brief contexts
5. Visit record page for base table

At this point, I think we should be seeing the base table presentation as well as related entities.

The problem is, I am seeing a related entity at the bottom which seems like a self-link to the base table again. I don't think this should be present at all.

**Comment by RFSH** [comment]
@karlcz This should be fixed now.

**Comment by karlcz** [comment]
confirmed.
