### ISSUE TITLE
Date presentation not ISO 8601?

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#346]
I think this is a bug...  Dates and timestamps should always be in ISO 8601 format to match what we take as input rather than having sub-fields move around in different orders depending on locale settings.

I think we should be able to display in full (24 hr) format but I realize some people may want to use AM/PM instead so perhaps we need a configuration toggle to adjust on deployments:
- 2017-01-08 15:06:02
- 2017-01-08 03:06:02 PM

The digits should be in the correct order and always 2-digits wide even if having a leading zero.

**Comment by hongsudt** [comment]
@howdyjessie can you change the default format to be the ISO 8601 using 24 hours format?

**Comment by howdyjessie** [comment]
PR #349 has been merged into master, closing this now...
