### ISSUE TITLE
More Encoding Unit Test

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#352]
Add more unit test for encoding that have characters other than space, e.g., `(`, `%`.

**Comment by hongsudt** [comment]
@RFSH is this task done?

**Comment by RFSH** [comment]
@hongsudt Not completely. We only have some test cases for `/`.

**Comment by hongsudt** [comment]
@RFSH We should try to finish this. If it need to scope down for this iteration, we can.. Then create another issue that expand the coverage to be done later.. I don't want tasks stuck in this week lane too long.

**Comment by RFSH** [comment]
Since I created this issue, I made sure to add unit test cases to features that envolved changing the reference URL. I am going to close this issue but we should be cautious about always adding appropriate encoding test cases for the new features.
