### ISSUE TITLE
deeper substring search

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#353]
Currently, the sub-string search only applies to the column values of the primary table. We want to be able to extend the search to _referenced_ tables. However, in this context, we might not want to apply the search to all columns in the referenced tables to avoid confusing matches.

In the meeting, we discussed both ermrest extension and annotation to provide this flexbility. @karlcz, @robes Can you guys sketch out a solution in this issue? 

- [ ] ermrestjs api to apply a `::ciregexp::` search filter and have it expanded into a disjunctive filter that also considers one or more of the denormalized records referenced by foreign keys in the base record...
- [ ] chaise config to turn on deep search behaviors, and way to pass that setting into ermrestjs
- [ ] annotations to control the deep search behavior with more specificity
    - referenced schema defaults
    - referenced table defaults (override previous)
    - referencing schema defaults (override previous)
    - referencing table defaults (override previous)
    - foreign key settings (most specific controls)
    - annotations not only enable/disable deep search but specify the search column to use, e.g. `*`, or a specific single column like `term` in some vocabulary, or some new ERMrest search column TBD.

**Comment by robes** [comment]
@karlcz has sketched out the first part of the solution in https://github.com/informatics-isi-edu/ermrest/issues/133. Of the options given there I lean toward the extensible option which after Karl's last update seems like it would provide backward compatibility to existing clients so we can avoid flag days.

**Comment by karlcz** [comment]
The first work needs to be front-end changes driven by chaise-config and annotations.  The possible ermrest changes would just enhance that by allowing more than one kind of wildcard search to be used in ermrest (multiple short-hand notations for matching a set of columns at once).

**Comment by hongsudt** [comment]
@robes @karlcz Is there still a need for this given that we have faceting?

**Comment by karlcz** [comment]
@hongsudt  I think this old issue is relevant to more recent discussions I've heard about desires to customize the search-box behavior via annotations.
