### ISSUE TITLE
validate proper context for Reference.create and update

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#361]
If the context is incorrect, we should throw an exception.. 

@RFSH since you are reviewing canCreate and canUpdate, can you work on this as well?

**Comment by RFSH** [comment]
@hongsudt Because of amount of change that is required on chaise, I decided to [fix it in ermrestjs side](https://github.com/informatics-isi-edu/ermrestjs/issues/360).
