### ISSUE TITLE
Sort control broken when FK references PK of same table

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#364]
@robes commented on [Tue Feb 28 2017](https://github.com/informatics-isi-edu/chaise/issues/1003)

On a table with a "self reference" (a FK that references its own PK), the sort control is broken on that column. The sort controls work for other columns still. See the "Derived From" column on the Imaging nested table on this record.

https://dev.facebase.org/data/record/#1/isa:sample/id=6

---

@RFSH commented on [Thu Mar 02 2017](https://github.com/informatics-isi-edu/chaise/issues/1003#issuecomment-283771207)

@robes 
It seems like the "Derived Form" column has been removed from the table.
I created [this sample table](https://dev.isrd.isi.edu/chaise/recordset/#18723/reference_schema_2:table_w_self_fk) with a fk to itself (`col_1` is a foreign key to `id` column). The sorting is working for all the columns of this table. 

---

@robes commented on [Thu Mar 09 2017](https://github.com/informatics-isi-edu/chaise/issues/1003#issuecomment-285492391)

@RFSH I can't follow the link to the sample. That catalog no longer exists. 

---

@RFSH commented on [Thu Mar 09 2017](https://github.com/informatics-isi-edu/chaise/issues/1003#issuecomment-285503693)

@robes Please use [this link](https://dev.isrd.isi.edu/chaise/recordset/#19085/reference_schema_2:table_w_self_link) (fk_col is foreign key to the table).

---

@robes commented on [Thu Mar 09 2017](https://github.com/informatics-isi-edu/chaise/issues/1003#issuecomment-285509979)

sample link works

---

@robes commented on [Mon Mar 13 2017](https://github.com/informatics-isi-edu/chaise/issues/1003#issuecomment-286314206)

@RFSH this issue is back, or so it seems to me...

See:
https://dev.facebase.org/data/record/#5/isa:sample/id=6

---

@robes commented on [Mon Mar 13 2017](https://github.com/informatics-isi-edu/chaise/issues/1003#issuecomment-286324438)

and another example on the dev isrd server.
https://dev.isrd.isi.edu/chaise/record/#1/isa:dataset/id=14084

**Comment by RFSH** [comment]
@robes The issue wasn't related to just FK reference to same table. The internal function that I was using for getting the annotation wasn't checking if the annotation is available or not. I added a sanity check to that function and a test case for that.

Since the change was simple, I [pushed it to master](https://github.com/informatics-isi-edu/ermrestjs/commit/850093a5702f1dc28a0807398167ec2ba18191d3).

**Comment by robes** [comment]
thanks
