### ISSUE TITLE
Add Unformatted Attribute to Displayname

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#372]
Currently the `Reference`, `Tuple`, `Schema`, `Table`, and `Column`have a displayname attribute which has `value` and `isHTML` in it. We should add a new attribute to these displayname objects that will return the unformatted (without any HTML tags) value. If `isHTML` is false, the `value` and `unformatted` value should be the same.

**Comment by hongsudt** [comment]
@RFSH are you working on this issue or is this one done? Please update the issue status..

**Comment by RFSH** [comment]
Yes, It's done as part of #376. I am closing this issue.
