### ISSUE TITLE
tag:isrd.isi.edu,2016:visible-foreign-keys is not working properly

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/ermrestjs#377]
On `cirm-dev`, I have the `Experiment` table with the following references to it:
```
Referenced by:
    TABLE ""Scan"" CONSTRAINT "Scan_Experiment ID_fkey" FOREIGN KEY ("Experiment ID") REFERENCES "Experiment"("ID")
    TABLE ""Slide"" CONSTRAINT "Slide_Experiment ID_fkey" FOREIGN KEY ("Experiment ID") REFERENCES "Experiment"("ID") ON DELETE SET DEFAULT
    TABLE "experiment_comments" CONSTRAINT "experiment_comments_Experiment ID_fkey" FOREIGN KEY ("Experiment ID") REFERENCES "Experiment"("ID")
    TABLE "experiment_probe" CONSTRAINT "experiment_probe_Experiment ID_fkey" FOREIGN KEY ("Experiment ID") REFERENCES "Experiment"("ID") ON DELETE CASCADE
```
I have defined the following annotation:
```
INSERT INTO _ermrest.model_table_annotation (schema_name, table_name, annotation_uri, annotation_value) VALUES

('Microscopy', 'Experiment', 'tag:isrd.isi.edu,2016:visible-columns', 
'{
	"detailed": ["Initials", "Experiment Date", ["Microscopy", "Experiment_Experiment Type_fkey"], "Number of Slides", "Number of Scans"],
	"compact": ["ID", "Initials", "Experiment Date", ["Microscopy", "Experiment_Experiment Type_fkey"], "Probe", "Number of Slides", "Number of Scans"],
	"entry": [["Microscopy", "Experiment_Initials_fkey"], "Experiment Date", ["Microscopy", "Experiment_Experiment Type_fkey"], ["Microscopy", "Experiment_Probe_fkey"]]
}'),

('Microscopy', 'Experiment', 'tag:isrd.isi.edu,2016:visible-foreign-keys', 
'{
	"detailed": [
		["Microscopy", "experiment_probe_Experiment ID_fkey"],
		["Microscopy", "experiment_comments_Experiment ID_fkey"],
		["Microscopy", "Scan_Experiment ID_fkey"],
		["Microscopy", "Slide_Experiment ID_fkey"]
	]
}')

```
When I create a new `Experiment`, I can not see the `Add` link for the `experiment_probe` table, and not at all the `Slide`, `experiment_comments` and `Scan` foreign tables.
You can see the screenshot in the attached `Experiment_without_comment.png` file.

What is more strange, is that if I add the `Comment` column in the `entry` of the `Experiment` `tag:isrd.isi.edu,2016:visible-columns`:
```
INSERT INTO _ermrest.model_table_annotation (schema_name, table_name, annotation_uri, annotation_value) VALUES

('Microscopy', 'Experiment', 'tag:isrd.isi.edu,2016:visible-columns', 
'{
	"detailed": ["Initials", "Experiment Date", ["Microscopy", "Experiment_Experiment Type_fkey"], "Number of Slides", "Number of Scans"],
	"compact": ["ID", "Initials", "Experiment Date", ["Microscopy", "Experiment_Experiment Type_fkey"], "Probe", "Number of Slides", "Number of Scans"],
	"entry": [["Microscopy", "Experiment_Initials_fkey"], "Experiment Date", ["Microscopy", "Experiment_Experiment Type_fkey"], ["Microscopy", "Experiment_Probe_fkey"], "Comment"]
}'),
```
then the `Slide`, `Scan` and `experiment_comments` foreign tables appear.
You can see it in the attached `Experiment_with_comment.png` file.

The `Slide`, `Scan` and `experiment_comments` tables have each of them defined the `Comment` column.
![experiment_with_comment](https://cloud.githubusercontent.com/assets/1609577/24679593/7fb03e34-1942-11e7-88eb-d5307a952423.png)
![experiment_without_comment](https://cloud.githubusercontent.com/assets/1609577/24679594/7fb16264-1942-11e7-9d4a-4e226aa5370c.png)

**Comment by RFSH** [comment]
Can you please give me a link to this record so I can investigate it?

**Comment by svoinea** [comment]
The link is https://cirm-dev.isrd.isi.edu/
From the `Search` menu, select `Experiment`
Click on the first listed experiment (that one was created by me).
You can also create a new experiment for investigation.

The current annotation for the `Experiment tag:isrd.isi.edu,2016:visible-columns` does not include the `Comment` column.

Our goal is to drop that column as it will be "replaced" by the `experiment_comments` table (i.e. an experiment might have multiple comments).

**Comment by karlcz** [comment]
If I'm not mistaken, the only valid, inbound foreign key in that list
is ["Microscopy", "Slide_Experiment ID_fkey"].

The outbound foreign keys are only applicable in the visible-columns
list and just affect how the column display value is denormalized to
include content from the referenced record.

**Comment by svoinea** [comment]
@karlcz I think you were on `cirm-dev.misd.isi.edu`. There:
```
_ermrest_tIgp7mD8QAeNLWPzmSDhZA=# \d "Experiment"
               Table "Microscopy.Experiment"
         Column         |         Type          | Modifiers 
------------------------+-----------------------+-----------
 ID                     | character varying(30) | not null
 Experiment Date        | date                  | not null
 Experiment Description | character varying(15) | not null
 Initials               | character varying(3)  | not null
 Disambiguator          | character(1)          | not null
 Comment                | text                  | 
 Tags                   | text                  | 
 Experiment Type        | text                  | 
 Probe                  | text                  | 
Indexes:
    "Experiment_pkey" PRIMARY KEY, btree ("ID")
    "Experiment_to_tsvector_idx" gin (to_tsvector('english'::regconfig, (((((((((COALESCE("ID"::text, ''::text) || ' '::text) || COALESCE("Experiment Description"::text, ''::text)) || ' '::text) || COALESCE("Initials"::text, ''::text)) || ' '::text) || COALESCE("Disambiguator"::text, ''::text)) || ' '::text) || COALESCE("Comment", ''::text)) || ' '::text) || COALESCE("Tags", ''::text)))
Foreign-key constraints:
    "Experiment_Experiment Type_fkey" FOREIGN KEY ("Experiment Type") REFERENCES "Experiment Type"("ID")
    "Experiment_Probe_fkey" FOREIGN KEY ("Probe") REFERENCES "Probe"("ID")
Referenced by:
    TABLE ""Slide"" CONSTRAINT "Slide_Experiment ID_fkey" FOREIGN KEY ("Experiment ID") REFERENCES "Experiment"("ID") ON DELETE SET DEFAULT

```
On `cirm-dev.isrd.isi.edu`:
```
microscopy=# \d "Experiment"
            Table "Microscopy.Experiment"
      Column      |         Type          | Modifiers 
------------------+-----------------------+-----------
 ID               | character varying(30) | not null
 Experiment Date  | date                  | not null
 Initials         | text                  | not null
 Disambiguator    | character(1)          | not null
 Comment          | text                  | 
 Experiment Type  | text                  | not null
 Probe            | text                  | not null
 Number of Slides | bigint                | 
 Number of Scans  | bigint                | 
 Probes           | text[]                | not null
Indexes:
    "Experiment_pkey" PRIMARY KEY, btree ("ID")
Foreign-key constraints:
    "Experiment_Experiment Type_fkey" FOREIGN KEY ("Experiment Type") REFERENCES experiment_type(term)
    "Experiment_Initials_fkey" FOREIGN KEY ("Initials") REFERENCES "User"("Full Name")
    "Experiment_Probe_fkey" FOREIGN KEY ("Probe") REFERENCES probe(term)
Referenced by:
    TABLE ""Scan"" CONSTRAINT "Scan_Experiment ID_fkey" FOREIGN KEY ("Experiment ID") REFERENCES "Experiment"("ID")
    TABLE ""Slide"" CONSTRAINT "Slide_Experiment ID_fkey" FOREIGN KEY ("Experiment ID") REFERENCES "Experiment"("ID") ON DELETE SET DEFAULT
    TABLE "experiment_comments" CONSTRAINT "experiment_comments_Experiment ID_fkey" FOREIGN KEY ("Experiment ID") REFERENCES "Experiment"("ID")
    TABLE "experiment_probe" CONSTRAINT "experiment_probe_Experiment ID_fkey" FOREIGN KEY ("Experiment ID") REFERENCES "Experiment"("ID") ON DELETE CASCADE
Triggers:
    experiment_trigger_after AFTER INSERT OR UPDATE ON "Experiment" FOR EACH ROW EXECUTE PROCEDURE experiment_trigger_after()
    experiment_trigger_before BEFORE INSERT OR UPDATE ON "Experiment" FOR EACH ROW EXECUTE PROCEDURE experiment_trigger_before()
```

**Comment by karlcz** [comment]
When I go to the record page you described, and click "Show All Related Records" I see the empty categories for each of the foreign keys.  If you want this toggled by default, I think there is a chaise-config setting that controls whether empty sections start off hidden or expanded.

**Comment by svoinea** [comment]
It seems that the problem is related to the initial presence of the `Show All Related Records` link instead of the `Hide Empty Related Records` one, and that might be due to a race condition.

**Comment by robes** [comment]
I'm looking at the schema for `Experiment` and based on the visible columns and visible foreign keys annotations, I'm seeing what I would expect on the record page.

here:
https://cirm-dev.isrd.isi.edu/ermrest/catalog/1/schema/Microscopy/table/Experiment

and here:
https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:Experiment/ID=20170404-H%26EACE-SV-1

**Comment by robes** [comment]
Okay, returning to that page I see what you are reporting that the empty tables are not shown by default.

https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:Experiment/ID=20170404-H%26EACE-SV-1

Ironically, I'm not a fan of this UX of showing empty records by default for authenticated and authorized (to edit) users. But we should be consistent at least.

So as far as I understand this was a real bug, albeit the description should be updated now?

**Comment by robes** [comment]
@karlcz I don't see such a config option but it would probably be good to have. alternately I wonder if we should extend the visible FKs annotation with a show when empty boolean flag. instead of FKs listed as pairs `[ schema, keyname ]` maybe it could be extended to `[ schema, keyname, options ]` where `options` is a JSON object with extensible parameters beginning with this one...

**Comment by hongsudt** [comment]
@RFSH if @jrchudy has fixed this problem, please refer to the specific issue in chaise and close this issue.

**Comment by RFSH** [comment]
- [This PR](https://github.com/informatics-isi-edu/chaise/pull/1058) changed the heuristics for "show related" button.
- [This PR](https://github.com/informatics-isi-edu/chaise/pull/1062) changed the "Link" button to "Add".
