### ISSUE TITLE
shortest key should take not null constraint into account

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#378]
So the precedence is
* not null
* integer column over text
* single column over multiple columns

@karlcz what if there is no not-null unique key constraint in the table. What should we do in that case?

**Comment by karlcz** [comment]
The answer for the DBA is to make sure they include a primary key,
i.e. unique and not-null.  The answer below is just how we should
attempt to cope in spite of this problem. (Other features like paging
may be broken w/o a primary key...)

The precedence means that everything that lacks not-null constraint
will tie, then you break the tie with the secondary preferences.

I'm not sure about the ordering you gave for integer versus simple
key.  Shouldn't we prefer a single column text key to a multi-column
integer key?
