### ISSUE TITLE
incorporate file asset annotation

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#379]
- incorporate the new asset annotation
- generate a new type of pseudo column 
  - In the read mode, display the column value
  - In the create/edit mode, all the columns (except the url) mentioned in the annotation should not be editable

@karlcz @robes anything else?

**Comment by robes** [comment]
In read mode we could have a prettier default display:
- generate markdown to display it as a link
- the link should use the `download` class
- the name of the link should conditionally be the asset `filename` if one is specified or the URL itself if not filename is specified.

I think that translate into something like this in markdown but we could do it programmatically in the pseudocolumn:
```
[{{{#filename_column}}}{{{filename_column}}}{{{/filename_column}}}{{{^filename_column}}}{{{this column}}}{{{/filename_column}}}]({{{this column}}}){download}
```

In create/edit mode, yes, I think you're right about that.

**Comment by RFSH** [comment]
```md
[{{{#filename_column}}}{{{filename_column}}}{{{/filename_column}}}{{{^filename_column}}}{{{this column}}}{{{/filename_column}}}]({{{this column}}}){download}
```
