### ISSUE TITLE
Add related entities link visible on SQL view

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#381]
I have a SQL view in my catalog but Chaise acts like it is writable and presents mutation controls.

1. Go to https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Subject/ID=ZfCza20170410A
2. See invalid mutation controls
    -  `Add` button on the `Pointclouds` related entity section
    - `Edit` or pencil icon on rows in `Pointclouds` related entity section

This is a view, so not writable.  The `Add` and row-level `Edit` buttons should not be showm in this case. The table description (https://synapse-dev.isrd.isi.edu/ermrest/catalog/1/schema/Zebrafish/table/Pointclouds) has the field `kind` which indicates this is a `view` rather than a `table`.

**Comment by karlcz** [comment]
I substantially revised this issue description after realizing it had nothing to do with table-alternatives.  It's just a plain view in the catalog.

**Comment by jrchudy** [comment]
The PR that fixes this issue has been merged. Assigning it to @karlcz for review.

**Comment by karlcz** [comment]
I confirmed that this is now working on my dev system. This is a functional review, not a code review.
