### ISSUE TITLE
acl is undefined 

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#383]
I have a test catalog which is getting errors on loading every table or view I try with recordset.

The page loads and displays content but then dies with the terminal error shown below.

Example URL: https://synapse-dev.isrd.isi.edu/chaise/recordset/#2/Chaise:Table%20Access

```
acl is undefined
   Reference.prototype._checkPermissions@https://synapse-dev.isrd.isi.edu/ermrestjs/ermrest.js?v=8c39d379cad4516e9dee24922f309321:6634:29
   get canCreate@https://synapse-dev.isrd.isi.edu/ermrestjs/ermrest.js?v=8c39d379cad4516e9dee24922f309321:6551:63
   anonymous/fn@https://synapse-dev.isrd.isi.edu/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84 line 14432 > Function:2:159
   $RootScopeProvider/this.$get</Scope.prototype.$digest@https://synapse-dev.isrd.isi.edu/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:17064:34
   $RootScopeProvider/this.$get</Scope.prototype.$apply@https://synapse-dev.isrd.isi.edu/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:17337:13
   done@https://synapse-dev.isrd.isi.edu/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:11572:36
   completeRequest@https://synapse-dev.isrd.isi.edu/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:11778:7
   requestLoaded@https://synapse-dev.isrd.isi.edu/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:11711:9

```

The only two things I think are unusual about this catalog are:
1. I use a new column type `inet` on some tables (but it also fails on views w/o this column)
2. I have fewer permissions set in the `/ermrest/meta` API

**Comment by jrchudy** [comment]
Without digging into the code too much for this issue (the _checkPermissions_ function), it looks like the permission that is being looked for is returning an empty set. If `._meta[permission]` is undefined, it will break the `_checkPermissions(permission)` function.

So if you are trying to check the `write_user` ACL and that ACL was not set, it will be trying to look through _undefined_ instead of an array. Maybe if the ACL is not set, we need to still populate the `_meta_` object properly at introspection.

**Comment by karlcz** [comment]
Right, the current ermrest/master will not return an empty list for
acl types in the /meta/ API.  It only has a list if at least one
member is configured.  It would be good to make the consumer more
defensive in this case.

This stuff will change when we finally merge the new fine-grained ACL
support, as we'll abandon the /meta/ API and check permissions on
individual tables via a different mechanism...

**Comment by jrchudy** [comment]
Reassigning this to @karlcz to verify it has been fixed.

**Comment by karlcz** [comment]
This looks like it is working now.
