### ISSUE TITLE
knowledge transfer from chirag in May

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#387]
- [x] markdown handling
- [x] test framework 
- [x] file upload

**Comment by hongsudt** [comment]
@jrchudy @RFSH should we close this issue?

**Comment by jrchudy** [comment]
We still need to go over the ErmrestDataUtils (part of test framework).

**Comment by hongsudt** [comment]
OK.. let's keep this opened until all bullets are checked.

**Comment by chiragsanghvi** [comment]
This is done.
