### ISSUE TITLE
API to retrieve aggregate group data (histogram, word frequency)

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#388]
These APIs rely on the [`attributeGroup` API in `ermrest`](https://github.com/informatics-isi-edu/ermrest/blob/master/api-doc/data/rest.md#attribute-group-retrieval). This means there needs to be a separate function used by the reference besides `getAggregates()`, maybe `getGroupAggreagte()`.

The following API for entity count returns `[{columnName: value, "alias": count}, {}, ...]`, where value is each possible value for that column across all available rows.
`entityCount`:
```
// using attributegroup/schema:table
// alias1 should be value
// alias2 should be freq
"/alias1:=columnName;alias2:=cnt_d(uniqueNotNullCol)";
```

The following API for histogram returns `[{columnName: [bucket#, min, max], "alias": cnt}, {}, ...]`, where the bucket # is the bucket number in the range beginning with 1. Anything in bucket 0 is below your min value for the interval, anything in bucket n+1 is above your max value for the interval.
`histogram`:
```
// must use attributegroup/schema:table
"/alias1:=bin(columnName;numberOfBuckets;min;max);alias2:=cnt_d(uniqueNotNullCol)
```

However, if the URL path prior to the bin specification contains a join statement, cnt(*) will return the wrong values (e.g. the rows corresponding to those values can be counted many times depending on the join results). To address this problem, we need to do an equivalent of `count distinct` of a not null unique key. This method is safe but is expensive. This is can be done by: 

If the uniqueNotNullCol doesn't exist, throw an error. A histogram cannot be derived..  

[HT] I don't think we need distinctHistogram v.s. histogram. There is only one definition of a histogram.. However, if there is a way to detect whether a `join` is present or not, we can use this to toggle between cnt_d(uniqueNotNullCol) v.s. cnt(*). 

Constructor: 
```
ColumnGroupAggregateFN.prototype = {
  get wordFrequency() {},
  histogram: function(min, max, #buckets, uniqueNotNullCol) {},
  search: function(str) {}
}
```

In ReferenceColumn:
```
get groupAggregate() {
  if (this._groupAggregate === undefined) {
    this._groupAggregate = new ColumnGroupAggregateFn(this);
  }
  return this._groupAggregate;
}
```

In Reference:
```
getGroupAggregate: function(aggregate, sort, paging) {
  baseuri = "ermrest/catalog/cat#/attributegroup/compactPath/"

  // NOTE: Aggregate functions for both entity count and histogram should error out if no single column primary key is available to aggregate count over

  http.get(baseuri + agg + sort + paging).then(function (response) {

    // when histogram comes back, the response needs to be adjusted from [index, min, max] 
    // to just [min, max] where the index is used as the index in the histogram set
    var histogramValues = []
    for each bucket in histogram {
      // bucket.alias1[0] is the index
      // bucket.alias1[1] is the min of the bucket
      // bucket.alias1[2] is the max of the bucket
      histogramValues[bucket.alias1[0]] = { alias1: [bucket.alias1[1], bucket.alias1[2]], alias2: bucket.alias2}
    }

    // return an array of objects
    // the array is a list of objects in the form of {value: val, freq: cnt}
    // value: for entity count, value is the column value
    //        for histogram, value is an array of the bounds [lowerInclusiveBound, upperExclusiveBound]
    // freq: the total number of entities in the current bucket
    return [
      {alias1: '', alias2: ''},
      {}, ...
    ]
  });
}
```

entity count response:
```
// alias1 should be value
// alias2 should be freq
[{alias1: val, alias2: cnt},
 {alias1: val, alias2: cnt}]
```

histogram response:
```
// alias1 should be value
// alias2 should be freq
[{alias1: [bucketIndex, minInclusiveValue, maxExclusiveValue], alias2: cnt},
 {alias1: [bucketIndex, minInclusiveValue, maxExclusiveValue], alias2: cnt}]
```

**Comment by jrchudy** [comment]
@RFSH, @robes, @karlcz:
This is the current proposed API for the group aggregate functions. The return object of the `getGroupAggregates()` request is currently a list of histogram and frequency responses (both are lists of each value/bucket and it's corresponding counts).

**Comment by RFSH** [comment]
1. I don't think we should have different APIs for `disctincHistogram` and `histogram`. The implementation of `histogram` itself must be smart about it and when there's a join in url, it should use `cnt_d(keys)` (keys is list of shortest key columns appended by `,`).
2. I think `wordFrequency` should return paged results, not all the available results. [Example](https://dev.isrd.isi.edu/ermrest/catalog/1/attributegroup/isa:dataset/value:=accession;cnt:=cnt(*)@sort(value)@after(FB00000107)?limit=5)

**Comment by jrchudy** [comment]
Signal when there isn't a primary key.

**Comment by jrchudy** [comment]
@RFSH, @hongsudt: 
 I updated the API sketch above from what we discussed in scrum this morning.

**Comment by RFSH** [comment]
@jrchudy It seems like we need another group aggregate api. There should be an api that returns list of values without the frequencies (just `"/alias1:=columnName"` without the `cnt_d`). The reason that we needs this other mode is that in some cases we don't care about count and asking for count is going to make the request more expensive.
