### ISSUE TITLE
incorporate faceting in the Reference

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#389]
@robes can you work on potential APIs for this? 
This is probably related to #66.

**Comment by robes** [comment]
I have a design in mind for this. I can work on this after the FB annual meeting, unless Carl wants me to first work on the viewer refactoring.

**Comment by hongsudt** [comment]
We will need to have this soon..

**Comment by hongsudt** [comment]
This is duplicated with #450.
