### ISSUE TITLE
alternate tables annotation not inherited by subcontexts

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#391]
I created an alternate table/view `alt_x` on table `x`. On table `x` I set the alternate table for the `compact` context to be the `alt_x`. I only see the `alt_x` displayed on the recordset but not in the nested tables. Explicitly specifying `compact/brief` fixed this.

**Comment by hongsudt** [comment]
@RFSH If this is fixed, please assign @robes to review and close the issue..

**Comment by RFSH** [comment]
@hongsudt I just merged the PR.

**Comment by robes** [comment]
appears to work in my test
