### ISSUE TITLE
ermrestjs should implement the isUnique api

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#399]
Its time for this. It should be a simple matter of introspecting and validating against the filter in the URL.

**Comment by hongsudt** [comment]
this is related to informatics-isi-edu/chaise#1098, informatics-isi-edu/chaise#685.

**Comment by hongsudt** [comment]
We already have a mechanism to detect uniqueness for the record page. I am tagging this as a wishlist and close the issue. If there is a need for this functionality later, we can reopen it.
