### ISSUE TITLE
Add filename and lineno to the errors

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#41]
I think we can get this by inheriting from the standard error constructor in javascript.

**Comment by robes** [comment]
Sorry @howdyjessie ... as far as I can tell getting the lineno and filename is a mess of non-standard hacks. The only reason we get these on the native `Error` class is because of browser-specific features.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

I'll label this as `wontfix` but I'll leave it open so that we avoid duplicates if someone else asks.

**Comment by howdyjessie** [comment]
@robes -shakes fist- Mozilla got my hopes up! Thanks for checking it out.

**Comment by robes** [comment]
And there’s a lot of crazy ideas floating out on stackoverflow, but I don’t think we should get into it. All of the ideas look fragile.
