### ISSUE TITLE
Update and Create Return Uncontextualized Page object

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#415]
The `update` and `create` functions return `Page` object. But the returned object is uncontexualized. This can cause problem, because it will result in having `page.tuples` and `reference.columns` to not be in-sync.

**Comment by jrchudy** [comment]
I didn't consider this before. This should be trivial to fix and it currently only affects the `resultset` view of `recordedit` when the user creates/updates 2 or more entities. In other cases we redirect to record page which contextualizes properly before showing the data.

One thing to think about is what context should these references be in after create/update returns? I imagine we want it to be in the `detailed` context or `compact`. Those contexts are used for `record` and `recordset` respectively. The `resultset` view is more similar to `recordset`, but maybe we want to introduce a new context.

**Comment by RFSH** [comment]
I actually found this problem when I was changing the multi edit result page. 

We are using the returned page to show which tuples are updated. Currently we are using `compact` context for that page. It make sense for it to be compact, because we are showing the compact view. But then again, you might have changed something and in the result page that column might not be visible (by having different visible columns for `entry/edit` and `compact`). That's why I think having a new context might make more sense.

**Comment by jrchudy** [comment]
I talked to @hongsudt about this a few minutes ago while asking her about other tasks, and she said to keep it relative to the context that the data was manipulated in. If it was create, contextualize to `entry/create`, and `entry/edit` for edit. 

This way the user will see only the columns that they added values for or updated values for.

**Comment by RFSH** [comment]
After discussing it with @hongsudt and @jrchudy, we decide to use `compact` context for both of them for now. We might need to introduce a new context in the future.
