### ISSUE TITLE
Delete Uploaded Files

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#420]
We should remove all the files that we upload during upload test cases.

**Comment by hongsudt** [comment]
@karlcz do we have a solution for this already?

**Comment by karlcz** [comment]
Not sure what you're asking...  hatrac supports the DELETE operation on data urls.

Right now, a once-deleted URL cannot be reused in hatrac.  The test suite should choose a new, unique namespace name for each test run and put all temporary objects under that, then at the end it could just delete that namespace which I believe will recursively delete everything under it.  E.g. use a path like `/ermrestjs-test-isotimestamp/` where the timestamp might be to millisecond precision or something

**Comment by hongsudt** [comment]
I thought you already have a script that we can use to clean up a
namespace..

**Comment by karlcz** [comment]
The terrible script to cleanup hatrac behind the scenes was for a
different purpose: DBAs who wanted to wipe the slate and reuse the
same names on a sandbox server, e.g. when they revised their data
processing rules and wanted to rebuild the world.

It's not reasonable for a test suite to use a fixed prefix like that.
Can multiple people run the test suite?  The runs would collide with
each other... each run needs a distinct namespace.

So, the test suite should clean up after itself. The rest api is
sufficient for this.  If you use a timestamp scheme like I mentioned,
a secondary cron job could also clean up old stuff that has leaked out
on a shared test server, just by pattern-matching to find the test
runs and sorting by timestamp to decide which are stale...
