### ISSUE TITLE
Expose Other File Attributes in url_pattern

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#423]
Apart from table columns, currently `filename`, `size`, `md5_hex`, `md5_base65`, and `sha256` are accessible in url_pattern of asset annotation. We should expose other file related attributes as well.

Since we are using javascript [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File) API, apart from the attributes that are currently used we have access to "MIME type" and "last modified date", which we can expose.

**Comment by chiragsanghvi** [comment]
`last modified date` cannot be added as it is being deprecated and not supported https://developer.mozilla.org/en-US/docs/Web/API/File/lastModifiedDate.
