### ISSUE TITLE
ErmrestJS does not allow values like (false or 0) to be passed to ermrest.

### ISSUE THREAD

**Issue by nitishksahu** [informatics-isi-edu/ermrestjs#430]
ErmrestJS does not allow values like ("**false**" and **0**) to be passed as 'data' to ermrest api calls. Any data with these values are converted to "**null**" before passing it to ermrest.

**Comment by jrchudy** [comment]
@nitish, if the code to fix this issue has been merged into master, please close it.

**Comment by nitishksahu** [comment]
A fix has been merged to master in PR#436, closing the issue.
