### ISSUE TITLE
Better File Structure

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#439]
With addition of new features our source code is getting bigger and bigger. We currently have `reference.js` (4k lines of code) which uses `core.js` (3k) and `utilities.js` (1.5k). We don't have a good structure for our files.

We could break them into more files. Each one responsible for one part of the API. For instance putting all the `ReferenceColumn` logic into its own file. Since we are not exposing classes, then they will not have access to the classes of other files. To solve this problem, we can change our build step to put all the content of files into a single module. Instead of extending the module in each file. 

We should investigate for potential solutions.

**Comment by hongsudt** [comment]
@RFSH @jrchudy If I am not mistaken, you guys have already done this correct? If so, should we close this issue?

**Comment by jrchudy** [comment]
We have not yet. We only created a mechanism to allow for easily merging all the code into one single module at build time. We have yet to reduce the content of some of the js files. For instance, `reference.js` still contains ~1500 lines worth of code specific to `ReferenceColumns` and it's sub types.

**Comment by RFSH** [comment]
I am going to close this issue. This can be done as part of any task that includes changing a lot of the code  and I don't think we need a separate issue for it.
