### ISSUE TITLE
ACL check interfaces on object model elements

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/ermrestjs#44]
See #61 as a prerequisite for this feature. We will then add `canPERMISSION` getter properties at the appropriate object model element, where `PERMISSION` is `Create | Update | Delete` at this point.

We have 2 use cases:

1. putting the "create new entry" link to a recordedit page to add a new record
2. putting the "edit" link to a recordedit page to edit an existing record
3. putting a "delete" link on an existing record page

```
.Catalog
  .canCreate => boolean
  .canUpdate => boolean
  .canDelete => boolean
  ...

.Table
  .canCreate => boolean /* NEW (1) */
  ...

Rows /* per issue #61 */
  .data  /* RAW array of json objects return from ermrest */
  .length()
  ._table /* don't put in prototype; set in the constructor; don't document in jsdoc */
  .get( i ) => Row  /* NEW */

Row /* NEW per issue #61 */
  .data /* RAW json object for the ith result in the Rows.data */
  .names()
  .get(name)  /* where 'name' is column name */
  ._rows /* private */
  .canUpdate => boolean /* (2) */
  .canDelete => boolean /* (3) */
```

These `canX` functions should be getter functions and should cache in a private local variable. For example:

```
Catalog = {
  ...

  get canCreate() {
    if ( ! this.hasOwnProperty('_can_create') )
       this._can_create = /* determine if can create is allowed for this client */
    }
    return this._can_create;
  }
};
```

The variable `_canCreate` in the above example _should not_ be added to the `Catalog`'s prototype.

**Comment by robes** [comment]
Is this still pending?

**Comment by hongsudt** [comment]
Yeah.. Jessie is working on it to support the ACL of the edit button and
the recordedit page.

**Comment by robes** [comment]
This is something that should be sketched out and discussed tomorrow.

**Comment by robes** [comment]
We have 2 use cases:

1. putting the "create new entry" link to a recordedit page to add a new record
2. putting the "edit" link to a recordedit page to edit an existing record
3. putting a "delete" link on an existing record page

```
.Catalog
  ...

.Table
  .canCreate() /* NEW (1) */
  ...

RowSet
  .data  /* RAW array of json objects return from ermrest */
  .length()
  .get( i ) => Row  /* NEW */

Row /* NEW */
  .data /* RAW json object for the ith result in the RowSet.data */
  .names()
  .get(name)  /* where 'name' is column name */
  .canUpdate() /* (2) */
  .canDelete() /* (3) */
  .delete() /* in scope? */
  .update() /* in scope? */
```

**Comment by hongsudt** [comment]
I would like to defer this issue until we have a better idea of how to deal with ACL. For now, let's just use chaise config.

**Comment by hongsudt** [comment]
After the discussion with @robes and @karlcz, we decided to implement APIs described above but with simple logic by referring the decision to the schema ACL e.g. 
```
Row.canEdit() 
  return this._rows._table.schema.catalog.canEdit();
```

**Comment by robes** [comment]
Based on suggestion from @hongsudt, I'm going to revise the sketch above (1) to make the function a getter, and (2) to cache the results so that the evaluation is one time. There could be issues with caching in long running sessions and future row level policy changes, but I'm going to ignore that for the time being.

**Comment by robes** [comment]
Use the getter function style like this:

```
Row.prototype = {
  /* other methods */

  get canUpdate () {
    if ( ! this.hasOwnProperty('_can_update') ) {
      /* detemine whether this client can write */
      this._can_update = this._rows._table.schema.catalog.canEdit();
    }
    return this._can_update;
  }
};
```

Note that `_can_update` should _not_ be added to the `Catalog`'s prototype. It is not a part of its interface, does not need to be documented (in jsdocs), and only exists when needed. Also, I would recommend

**Comment by hongsudt** [comment]
De-prioritize this issue since this is not applicable in record 1.

**Comment by robes** [comment]
This issue needs to be revised for the reference api.

**Comment by hongsudt** [comment]
I am closing this as it is no longer relevant. Will create another one for ACL.
