### ISSUE TITLE
jsonb column edit context issues

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#452]
I've noticed the following 2 problems with jsonb column types when editing:

- if annotated as 'generated', the display should indicate "Automatically generated" but does not (not sure if this is an ermrestjs or chaise bug)
- if annotated with a 'display' annotation and 'markdown_pattern', the value will be changed per the markdown pattern and therefore no longer is (likely to be) a proper jsonb value. Really just the presentation should be changed not the underlying raw tuple value.

**Comment by robes** [comment]
An example can be seen here:

https://cirm-dev.isrd.isi.edu/chaise/recordedit/#2/Microscopy:Collection/ID=4@sort(ID)

**Comment by RFSH** [comment]
- The first issue is related to chaise. In [textarea that is used for json](https://github.com/informatics-isi-edu/chaise/blob/master/recordedit/index.html.in#L228) the placeholder (`placeholder="{{::form.getDisabledInputValue(column, form.recordEditModel.rows[rowIndex][column.name]);}}"`) is missing.
- The second issue is related to ermrestjs. Basically we're calling the function that takes care of formatting json column (which does "markdown_pattern" manipulation) in entry contexts.

**Comment by hongsudt** [comment]
@nitishksahu this one has you as a reviewer. If you want to ask @robes to review, please assign the appropriate assignee to the task.

**Comment by nitishksahu** [comment]
@hongsudt this issue needed some code changes in chaise as well, the PR for this change is still open in chaise and the code has not been merged to master, so it is still in my queue.

**Comment by nitishksahu** [comment]
The changes for this issue have been merged to master, assigning this to @robes to verify.
