### ISSUE TITLE
Regression in JSON value formatting in templates

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#457]
I have a table with a JSON column, say `Status`.

I have a mustache template generating a markdown presentation like  `... Status: {{{Status}}} ...`.

My actual column value is JSON such as `"processed"` and I expect to see something like: `Status: "processed"` on the rendered web page.

Instead, I am seeing something like `Status: <pre> "processed" </pre>` i.e. it seems like some HTML tags are sneaking into the formatted value and then getting rendered as plain text.

**Comment by nitishksahu** [comment]
The changes for this issue has been merged with master, assigning this to @karlcz to verify.

**Comment by karlcz** [comment]
Hmm, that is weird.  The expansion `{{{_thumbnails}}}` and `{{{#_thumbnails}}}` should be using the raw column value which should be already decoded into a Javascript object (an array in this case).

Only the expansion `{{{thumbnails}}}` (without the underscore) should ever get converted into a presentation value as pretty-printed JSON.

**Comment by karlcz** [comment]
@nitishksahu  I verified that the literal `<pre>` and `</pre>` no longer appear in my rendered markdown.  It seems like this other issue described above by @robes might deserve to be a separate bug filing since it relates to the raw column value (with underscore) rather than the formatted column value as in this original bug report...

**Comment by nitishksahu** [comment]
As the regression issue for the JSON column is resolved, am closing this issue.

A separate issue has been created #468 with @robes comment and will be worked on separately.
