### ISSUE TITLE
Add fallback heuristics for domain types

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#461]
When a column has a domain type like `markdown` there is also a base type like `text`.

When we don't have a presentation preference for the domain type, we should fall back to using any presentation preference for the base type.  When all else fails, we should continue to use a basic text presentation as we do now.

In upcoming changes to deployments, there will be several new domains with base types of `int8` and `timestamptz` and we want to get the appropriate display formatting for those rather than treating these as plain text.

**Comment by jrchudy** [comment]
Another piece of this PR is to add a case in `ermrestJS` in `Column.formatvalue` to handle this.

**Comment by jrchudy** [comment]
The changes for this issue have been merged into master. When a column has a domain defined and we don't know how to format data for that domain type, we check what it's base type is for formatting.

Reassigning to @karlcz to verify the changes are working as he expected for the synapse deployment.

**Comment by karlcz** [comment]
I think this is working now.
