### ISSUE TITLE
Collection annotion suggestions

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#465]
On the collection edit page, I find "Collection (member of)" a little bit confusing. It took me a while to realize that this is the collection id field. Should we rename this to "Collection ID"? 

The same comment for "Scan ID"

After adding a few scans, it returns to a table with "Collection:Scan" header. It might be better if we split those to their own columns.. 

Apart from those UX, I think it is good to go.

**Comment by robes** [comment]
This issue has been addressed by https://github.com/informatics-isi-edu/microscopy/issues/30
