### ISSUE TITLE
a function to retrieve 'row name'

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#49]
The row-name is derived from:
* 2015:display.row_name annotation
* Otherwise, look for a column with title, name, or label (case insensitive) 

It should be implemented as a dynamic property (i.e., using the getter approach) on the `Tuple` class.

```
Tuple.prototype = {
  /* other methods here */

  get displayName() {
    if (!this._displayName) {
      ...compute the row name based on the annotations and heuristics
      this._displayName = ...computed row name
    }
    return this._displayName;
  }
}
```

Clients will use it like a normal property.
And it will only be computed at the time of use, and only once.

@robes @karlcz I am assuming that we will be using displayName for the row name.

**Comment by shinyichen** [comment]
It wasn't clear to me what 'rowname' meant. How about 'value' or 'displayValue'?

**Comment by hongsudt** [comment]
@shinyichen I am sorry.. This description is out of date. I will update the issue with the Reference API..
