### ISSUE TITLE
Change Default Display of inline inbound foreignkey to a list

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#493]
What needs to be done:
1. You need to define a new context for the inbound references that are being shown inline, you should use the `compact/brief/inline` context for those. This includes:
    -  Defining the context in utilities.js
    -  Adding a new function (`compactBriefInline`) to the `Contextualize` prototype.
2. Change the default value for the reference.display.type to `markdown` i n case of `compact/brief/inline`
3. If the page.content is null, use this logic:
  - Create an unordered list of tuples with 
    - `<prefix>` if the prefix is specified in the annotation 
    - `[tuple.displayname](tuple.reference) <line separator>` format. Omit `<line separator>` if it is not defined.
    - `<suffix>` if the suffix is specified in the annotation 
4. Make sure that inbound related references are contextualized in the chaise.

**Comment by amitjha21** [comment]
Create compactBriefInline context and use it in the inbound fk display. if this is not available then the `chaise` application should follow the standard hierarchy.

**Comment by amitjha21** [comment]
Assigning to @hongsudt for reviewing this change. Corresponding `chaise` changes are under code review and should be merged early next week.
