### ISSUE TITLE
URL rewrite applies extra encoding of catalog ID

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#494]
I tested out Chaise on an experimental system with a branch of ermrest that supports a new URL feature. In addition to the typical numeric catalog ID, e.g. `1`, it can have a qualifier that is an encoded catalog version, e.g. `1@version` where _version_ already has percent-encoded parts in it and the `@` must remain unencoded.

For a basic table, it worked already since Chaise and ermrestjs don't care much about the catalog ID.  I just used a Chaise fragment ID in the browser like `#1@version/...`

Edited issue text:

Whenever Chaise or ermrestjs rebuild a new URL or pass around catalog ID, they should retain the original form of the ID and not perform any additional decoding or URL escaping.

Original (obsolete) issue text:

However, if the initial fragment ID is to a table that has a table-alternatives annotation, the browser location changed to have an invalid fragment ID where the `@` became percent-encoded and the _version_ looked like it got percent-encoded again (so original `%` chars turned into `%25`.

If this extra encoding could be removed, Chaise and ermrest would be more useful with future ermrest features that have to do with repeatable/historic content presentation.

**Comment by jrchudy** [comment]
@karlcz I noticed that the encoding is working fine in the general case as well. I can't reproduce the other scenario you are talking about (if the fragment ID is to a table with a table-alternative annotation). I'm not sure what the annotated model you tested this against looked like.

Could you provide some more information about the model you tested this against (a link to the model if it exists on one of the servers)? Or the way that you defined the annotation and what type of model I would need to reproduce it?

**Comment by karlcz** [comment]
I think this is an example...

1. Go to https://synapse-dev.isrd.isi.edu/chaise/record/#1@2NZ-7DP6-DDG8/Zebrafish:Image%20Region/RID=ZW
2. Look at Source Image column's outbound link URL: `https://synapse-dev.isrd.isi.edu/chaise/record/#1%402NZ-7DP6-DDG8/Zebrafish:Image/RID=3MY`  this has `%40` instead of `@`

**Comment by karlcz** [comment]
I guess that's not actually an example of table-alternatives but it is an example of the same class of double-encoding bug...

I actually don't think the table-alternatives part will be very common since this almost always involves a SQL view and these won't even be present for historical queries on the history-tracking branch of ermrest.

**Comment by RFSH** [comment]
@karlcz 
Does this mean that we should not apply any decode/encoding to the given catalog id? Should we use it as is without decoding it?

**Comment by jrchudy** [comment]
This has been fixed and merged into master. Changes were made in both `chaise` and `ermrestJS`. Reassigning to @karlcz for review.

**Comment by karlcz** [comment]
I confirmed that chaise-generated links now preserve the version-qualified catalog ID between pages and no longer corrupts it with unexpected escaping.
