### ISSUE TITLE
a library to convert a list of filters to facet url fragment

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#506]
We have a static site that provides links to the recordset pages with pre-defined filters. These URLs will no longer work once we deploy the new recordset with facet. 

We also have a search box on some static pages that will call the recordset based on the specified keywords. 

Maybe there should be a function that takes catalog number, table names, facet list (the same syntax that we use in the annotation) and turns that into a proper URL.

**Comment by RFSH** [comment]
I [created a function](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/parser.js#L38) that will take `catalogId`, `schemaName`, `tableName`, and `facets` as its parameters and will return a path that ermrestjs/chaise will understand.

**Comment by RFSH** [comment]
I am going to change the current function in rbk, to use this new API. Then we can use that as an example for other static websites.

**Comment by RFSH** [comment]
I created a [PR](https://github.com/informatics-isi-edu/rbk-www/pull/2) in rbk-www repository.
