### ISSUE TITLE
Update Columns to return visible ordered column list

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#51]
The function should integrate the column order and ignore annotations
* If a 2016:visible-columns annotation exists, show the columns in the annotation's specified order.
  * If the column name in the list is unknown (e.g. mis-spell), ignore that column. 
* Default: Show columns in the order defined in the database

API update.

```
Columns
 ...
 .byContext(contextstring) => Columns
```

The `Columns` returned `byContext()` should in the appropriate order per heuristics or annotations.
Use the same guideline as #68 for declaring contextstring.

**Comment by howdyjessie** [comment]
To expand on determining the visibility of a column: The absence of the `2016:ignore` annotation on a column doesn't necessarily mean the column should be visible. See #59 for more details on the hierarchical scoping of `2016:ignore` annotations.

**Comment by hongsudt** [comment]
if the table or schema is invisible, we should throw an error message. Maybe, this check is can be part of the ACL.

**Comment by robes** [comment]
I'm guessing this was reassigned to me and karl because we had a discussion in the afternoon that may change this column order annotation significantly. I think we agreed in principle to the change but @hongsudt might be the one (?) to define her proposed annotation and then share that.

**Comment by karlcz** [comment]
@robes @hongsudt  I went ahead and drafted 2016:visible-columns annotation in the ermrest annotations doc.

**Comment by RFSH** [comment]
@robes 

Since the visible columns annotation is defined on table, isn't it better if we add the `byContext(context)` function to the `Table` class and rename it to something like `getColumns(context)`?

From what I understood, `Columns` may include columns from different tables and order doesn't make sense in this case (since it's defined for columns of each table individually). Unless `Columns` object is used just for columns of a single table.

**Comment by RFSH** [comment]
@robes I think the main purpose of `Columns` class was to store columns of a single table. Therefore we can add a private attribute (`_table`) to this class. This way, I can get the order from the `Columns` class and the `byContext(context)` function can be defined in this class.
