### ISSUE TITLE
The "height" and "width" attributes are not working for the Video markdown 

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/ermrestjs#514]
I have defined the following `markdown_pattern`:
```
{"markdown_pattern" : "[{{{Name}}}]({{{MP4_URI}}})\n\n::: video []({{{MP4_URI}}}){width=400 height=300}\n:::"}
```

No matter what values I provide for the `height` and `width` attributes, they are ignored.

The `html` generated is:
```
<video controls=""><source src="/hatrac/resources/immunofluorescence/videos/2017/b876d547e35b724eae5b19f829855698" type="video/mp4"></video>
```

**Comment by RFSH** [comment]
It seems like you need to have a space between the last `\n` and `}`. This space is missing from all the examples in the wiki and I am going to add that.

What I mean is that the following won't work:
```
   ::: video [This is sample video](http://techslides.com/demos/sample-videos/small.mp4){width=300 height=300}\n:::
```
But this will work:
```
::: video [This is sample video](http://techslides.com/demos/sample-videos/small.mp4){width=300 height=300} \n:::
```

Notice the space between `\` and `n:::` at the end of the markdown.

**Comment by RFSH** [comment]
Assigning the issue to @svoinea to review.

**Comment by svoinea** [comment]
The space fixed the problem.
