### ISSUE TITLE
Support Array Column Type in recordset

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#516]
APIs that are dealing with representing data can easily support array data type (They're returning `toString` of the array which is the expected behavior). But the apis that are doing more with data (filter, create, update, etc.) need more logic to specifically handle array data types. 

This issue came up while working on array data types in faceting related APIs. We're showing the data as we expect, but cannot filter based on those columns.

**Comment by RFSH** [comment]
The reason that we cannot facet array types is that the `col=value` is not equality check but rather whether the col array column has `value` in it. But the aggregate function that we are using is just returning the array values and not individual acceptable values.

For example having these two rows

| id | array_col        |
|----|------------------|
| 1  | [ "a", "b"]      |
| 2  | [ "a", "b", "c"] |

We expect to see `a`, `b`, and `c` in the list of possible values for `array_col`. But currently we are showing `[a, b]` and `[a, b, c]`.

**Comment by RFSH** [comment]
Yeah, sure. This issue is more like a feature request from ermrest. An API that actually returns the unique values that are in the array column.

**Comment by hongsudt** [comment]
I am closing this issue..
