### ISSUE TITLE
Format column values according to type and/or annotations

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#52]
- [x] boolean 
- [x] integer (e.g. using thousands separators)
- [x] float (e.g. # of decimals)
- [x] date
- [x] timestamp
- [x] text: deal with html tags within the text value appropriately
- [x] markdown 
- [ ] ~~units specifier for numbers~~ Move to Part2
- [ ] ~~json/jsonb (e.g. some kind of hierarchy or pretty-printed view)~~ Move to Part2

We probably need deployment wide configuration, schema-level annotations and table-level annotations. Assigning this to @robes @karlcz to first update the annotation to cover this case. 

I am putting this under ermrestjs now. We can move to chaise if this is supposed to be done the a common module.

**Comment by karlcz** [comment]
This is going to be an optional function/method for formatting outputs as in `printf`, right?  I assume we'll defer any input decoding as in `scanf`?

**Comment by robes** [comment]
@hongsudt I am not sure this is an ermrestjs feature we should implement. This seems more like a chaise feature.

**Comment by hongsudt** [comment]
@robes shouldn't we have a consistent format through all chaise apps? If so, shouldn't this be done at the Row object?

**Comment by hongsudt** [comment]
@howdyjessie Apparently, I updated the function signature at the wrong issue. This issue is when you hook up the utility function to the column format. Can you move the description to #83?

**Comment by howdyjessie** [comment]
@hongsudt Just moved them!

**Comment by howdyjessie** [comment]
PR #147 has been created for this issue.

**Comment by howdyjessie** [comment]
PR #147 has been reviewed and merged into master.
