### ISSUE TITLE
Make attribute date available to Mustache

### ISSUE THREAD

**Issue by chiragsanghvi** [informatics-isi-edu/ermrestjs#522]
Add date object to Mustache template variables. This object can be access as `$moment` in Mustache template.

It will contain following properties for date Thu Oct 19 2017 16:04:46 GMT-0700 (PDT)

* date: 19
* day: 4
* month: 10
* year: 2017
* dateString: Thu Oct 19 2017
* hours: 16
* minutes: 4
* seconds: 14
* milliseconds: 873
* timeString: 16:04:46 GMT-0700 (PDT)
* ISOString: 2017-10-19T23:04:46.873Z
* GTMString: Thu, 19 Oct 2017 23:04:46 GMT
* UTCString: Thu, 19 Oct 2017 23:04:46 GMT
* LocaleDateString: 10/19/2017
* LocaleTimeString: 4:04:46 PM
* LocalString: 10/19/2017, 4:04:46 PM

We discussed about exposing date values in `$moment` object to the Mustache template, which can be referred to as `{{$moment.month}}` for month in the template.

**Comment by hongsudt** [comment]
Can you add this to the markdown template document?
