### ISSUE TITLE
markdown extension to support inline display

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#524]
of the following:
- glyph icons
- classes with different texts and colors

@karlcz what else? 

Note: I want to use this feature to present status summary succinctly.

**Comment by hongsudt** [comment]
@RFSH I moved this here since it is relevant to the div and inline issue..  If this is now a duplicate, please close it.

**Comment by RFSH** [comment]
This has been implemented with the addition of `:span:` tag. You can find some examples of it in [here](https://github.com/informatics-isi-edu/ermrestjs/wiki/Template-and-Markdown-Guide#12-span-attach-attributes-to-text)
