### ISSUE TITLE
Count in AttributeGroup Reference

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#525]
Since we're using `cnt_d` it will ignore `null` values. This is causing count function in `AttributeGroupReference` to not return the correct value.

**Comment by hongsudt** [comment]
There is no cheap way to address since count distinct ignore null values. So we decided to a simple work around which is if the total matches is smaller than what's currently shown, set the total matches to be the same as.. 

@RFSH should we close this issue?
