### ISSUE TITLE
Update faceting heuristics

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrestjs#530]
Faceting needs to consider 3 more column types:
 - boolean - include as part of heuristic and visible facets
 - json - never include this column type
 - jsonb:
     - only include if this column is part of the visible facets annotation. 
     - make sure that we are serializing it correctly.

**Comment by RFSH** [comment]
[This commit](https://github.com/informatics-isi-edu/ermrestjs/commit/8dc15da7c3d49ef32efa124b37a1b1db09564d06) has fixed these issues.
