### ISSUE TITLE
Unable to use a facet projecting a base table that has alternatives

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#531]
I have a facet definition whose source path projecting a key column for a table that has table-alternatives defined. This facet seems to get discarded from the visible column list.

If I append the inbound pseudo foreign key from the compact alternative table to the base table, then I can get it to work in both entity and scalar mode.

I think that projection of the base table should work too, and optionally Chaise can add the table-alternative for entity-mode facets.  For scalar facets it should project whatever column the DBA requested.

**Comment by RFSH** [comment]
Moved to wish list.
