### ISSUE TITLE
Move client id `cid` from query option to http header

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#535]
Putting the `cid` in query option causes http cache misses at least on every app that has a different client id. To avoid this we need the `cid` to be send as a http header field.

@hongsudt can we prioritize this?
@karlcz getting this (as an http header field) into the derivalogs probably involves changes to the recipes rather than to ermrest, right?

**Comment by karlcz** [comment]
I didn't see this when I created other issues for this topic. See #536
