### ISSUE TITLE
Add client context header for logging

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#536]
See informatics-isi-edu/ermrest#177 for more discussion.

We want to replace our previous bag of query parameters for logging properties with a header containing a bag of attribute-value pairs.

1. Have some mechanism to collect the bag of parameters as an object
2. Encode the object in JSON w/o any pretty-printing (compact out all optional whitespace).
3. Encode the JSON string with a modified version of url-encoding to make it safe for HTTP headers
4. Send the encoded string as the body of a new `Deriva-Client-Context` header

The url-encoding will be similar to that in RFC 3986 except we can leave some "reserved" characters in their native ASCII form.  Consider these char classes safe to pass unescaped:
- alpha: `A` - `Z` and `a` - `z`
- digit: `0` - `9`
- non-reserved punctuation: `-`, `_`, `.`, `~`
- JSON and HTTP safe reserved chars: `{`, `}`, `"`, `,`, `:`

Everything else will be encoded byte-by-byte into the `%hh` hex representation, including any existing `%` character in the original JSON string.

It is OK to use a regular url-encoding function in a pinch.  The server will decode it all correctly and end up with the same JSON. However, the intermediate HTTP header will be much uglier and longer due to changing the frequently occuring JSON syntax characters into 3-byte `%hh` forms when it isn't necessary.

**Comment by karlcz** [comment]
The initial properties for the client context would be what we had before in the query URL:
- cid
- pid

We may over time want to add more app-specific context parameters, e.g. for Chaise recordset to distinguish different kinds of query it is using in one app. We should deal with those as future extensions rather than trying to do everything at once.

**Comment by karlcz** [comment]
The small change in ermrest, hatrac, and webauthn to include this header in its log output is already pushed to each of those respective repos.

So, once dev servers have updated, it should be possible to dev and test the client-side mechanism. You'll see the new header content logged into a field called `dcctx` in the existing JSON-formatted request log events we emit in `/var/log/messages` etc.

**Comment by chiragsanghvi** [comment]
This task is divided into 3 phases:

- [x] Add support to http.js in ermrestjs to send headers as sent by user
- [ ] Change methods in ermrestjs that're exposed to user to start accepting header parameters.
- [ ] Make changes in Chaise to start sending logging headers to ermrestjs methods.
