### ISSUE TITLE
double encoded url in search query

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#550]
1. go to https://www.facebase.org/data/recordset/#1/isa:clinical_assay/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM6JHQBcAjdafEASyTBABoQsAbKiKrMZgfTCVoCe3KGCJ8cRbgDMA1jgEgAugF9GVGIsZYAFig44k+AIwAWAAwBOAGwqVQA@sort(id)?subset=Dataset%3A%20Developing%203D%20Craniofacial%20Morphometry%20Data%20and%20Tools%20to%20Transform%20Dysmorphology
2. expand "Syndrome Subtype"
3. click "show more"
4. in the search field on the modal popup, type "control" (or probably anything)

Error: 409 Conflict from the following URL that was generated:

`https://www.facebase.org/ermrest/catalog/1/attributegroup/M:=isa:clinical_assay/(dataset)=(isa:dataset:id)/id=14096/$M/Syndrome%2520Subtype::ciregexp::control/value:=Syndrome%20Subtype;count:=cnt(*)@sort(count::desc::,value)?limit=26&cid=recordset`

**Comment by RFSH** [comment]
#547 should have solved this. Described scenario works without throwing any errors in the dev server.

**Comment by hongsudt** [comment]
@robes please review.
