### ISSUE TITLE
Add RID in the display name/key heuristics

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#551]
We should incorporate RID into our heuristics in determining display name or shortest keys, etc. 

@karlcz When multiple keys exist, should we prefer RID?

**Comment by jrchudy** [comment]
The decision was made to support RID as the preferred key when multiple keys exist. 

RID is being indexed in ermrest and RID is implemented as type text in ermrest (and the DB) but is exposed as a column of type text.
