### ISSUE TITLE
Refactor parser to convert filters to facets

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrestjs#558]
Change ermrestjs parser to convert filter into a facet. In the process we should remove all the filter related APIs.

This requires making changes to the `_processSingleFilterString` and `_processMultiFilterString` functions in `parser.js`.

**Comment by RFSH** [comment]
A function has been added to filter that will turn it into facet. But we might not be able to use this facet, therefore this issue should still remain open. That function is now only being used for log purposes only.

**Comment by RFSH** [comment]
I implemented this in #598. We don't want to always change filter to facet. Only in case of faceting APIs this change has uses. Therefore it has been added to the `Reference.facetColumns`. If facet equivalent of filter was understandable by current implementation of faceting, we will change the filters to facet.
