### ISSUE TITLE
Handle RID default function

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#562]
In RBK, all the RID columns have the following value as default:
`_ermrest.urlb32_encode(nextval('_ermrest.rid_seq'::regclass))`

I think this is true for all deployments that use RID. 

When we see `/_ermrest.*\(\.)*/`, maybe we can treat that as a function and not pass that to the default value.

**Comment by jrchudy** [comment]
My thoughts were that if we know a column of domain type RID will always be generated, then we can ignore setting the "default value" for that column.

**Comment by hongsudt** [comment]
Yes, that works.. RID will always be generated by the server.. So we can mark that as "auto-generated" and ignore default.
