### ISSUE TITLE
API to get all tables that this table has a FKR to

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#57]
All the tables that this table has a foreign key to (I can find this using the memberofForeignKyes that is available in Column class.).

**Comment by robes** [comment]
@RFSH I'm not sure I understand the API proposal. Can you explain more? We currently have a clumsy way to get this information (for the _i_th FK of the table):

```
atable.foreignKeys.all()[i].colset.columns[0].table
```

That's kind of hideous... But is that the information you are trying to get?

**Comment by RFSH** [comment]
@robes 
This call returns the `atable` again. I need the table this FKR is referring to and also the columns of FKR. For instance if `owner` in `dataset` is a FK to `person`, I would need `person` table and `owner` column. Therefore:

- `atable.foreignKeys.all()[i].key.table` returns the table that I want.
- `atable.foreignKeys.all()[i].colset.columns` returns the columns.

I am not sure about the data structure that I should return. Should I create a wrapper object for that and return a list of objects? or just a list of dictionaries that contains `table` and `columns`?

**Comment by robes** [comment]
@RFSH Ah, right, of course. Thanks for pointing that out.

Do you have an example you can point me to in your code where you make use of this? An example, might help me understand better.

**Comment by RFSH** [comment]
@robes 
This is how I am doing this actually:
```javascript

function findChildren(node) {
   var result = [];
   if(!node.folder) return result; // if node is not a table

   var table = node.data.table;
 
   //find columns
  ...

  // find tables that this table has FK to
  angular.forEach(table.foreignKeys.all(), function(fk, index){
    var colNames = [];
    angular.forEach(fk.colset.columns, function(col, colIndex){
      colNames.push(col.displayname);
    });
    result.push(getTable(fk.key.table, colNames.join(",")));
  });
  
  // find tables that have FK to this table
  ...

  return result;
}
```
`findChildren` is the function that finds all the related tables and candidate columns of a specified table. the `getTable` function creates the required object for FancyTreeNode.

The output would be something like this (notice how `person` table is displayed):

![screen shot 2016-06-23 at 7 28 49 pm](https://cloud.githubusercontent.com/assets/2129750/16326090/befc52e4-3978-11e6-8b1e-ead1b980a3fc.png)

**Comment by hongsudt** [comment]
This functionality is implemented in Table.referredBy. @robes  Should we close this issue?

**Comment by RFSH** [comment]
@hongsudt It's actually the other way around and this is about outbound FKRs. It was just to make the process of getting related outbound Tables easier. Which I think it's not relevant anymore.

**Comment by hongsudt** [comment]
you are right.. If this is no longer relevant, let's close the issue.
