### ISSUE TITLE
recordedit doesn't use pre_format value for boolean

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#582]
It uses the raw true/false values as options. 
https://dev.rebuildingakidney.org/chaise/recordedit/#2/Common:Collection/RID=Q-1FFE@sort(RID)

**Comment by jrchudy** [comment]
This is being fixed in PR [#2031](https://github.com/informatics-isi-edu/chaise/pull/2031) in chaise.
