### ISSUE TITLE
Merge Handlebar PR

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#587]
We should investigate whether it is safe to use handlebar with user data. Based on my knowledge, it is mainly used by developers and therefore they have control over variables that they pass to handlebars. We should take a look at the security concerns, and if it seems safe then we can merge it.

We can write testcases for it later.

**Comment by jrchudy** [comment]
This issue is associated with `ermrestJS` PR #566. This issue is also related to `chaise` [issue #1408](https://github.com/informatics-isi-edu/chaise/issues/1408).
