### ISSUE TITLE
Add <resource instance>.ignore property

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/ermrestjs#59]
The [doc on the `2016:ignore` annotation](https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2016-ignore) says that `ignore` can be applied to schemas, tables, columns, or foreign key references. It also says that there's a hierarchical scope to its application. For example, when deciding whether a column should be ignored or not, clients need to check whether the column has an `ignore`. If an applicable one doesn't exist, then clients go up to the table level, then the schema level.

It would be nice if ermrestjs could handle this hierarchical checking and return the result in a `.ignore` property. The result could be an array of contexts, `true`/`null`, or `false`/`[]` (empty array).

**Comment by robes** [comment]
Given that `ignore` is context dependent I have an alternative idea here. We might want a function `.isIgnored(context=null)` that lets you pass in a `context` optionally or assumes any context if `null` is passed (or the parameter isn't passed). That function would then check the annotations (possibly precomputed) at various levels to respond with whether the `schema | table | column | fk` is ignored within the given context.

**Comment by hongsudt** [comment]
There is another ermrestjs issue that is supposed to return visible ordered
column list. That issue will take care of the ignore annotation and the app
shouldn't have to access this function at the column level directly.

**Comment by robes** [comment]
So as @hongsudt points out, issue #51 may obviate the need for this issue, so let's drop this to the backlog and hold off on it for now. We may decide while implementing #51 that it helps to have each model element decorated with the more direct `.ignore` property that @howdyjessie initially proposed.

**Comment by hongsudt** [comment]
close this issue since it is no longer relevant.
