### ISSUE TITLE
Multi-picker ignores page-size annotation on domain table

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#594]
I have a table with binary associations.  When I click the "add" button to add associations, the multi-picker modal seems to be using a default page size 25 when the domain table being associated with the parent record has a custom page-size annotation setting it to 4 on the `*` context, which means it should also apply to the `compact/select` context relevant here.

Example record: https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Cohort%20Analysis/RID=172Y

Try the "Add" button for the `Cohort` related entity section which is associating members of the `Synaptic Pair Study` table, which has this table-display annotation:
https://synapse-dev.isrd.isi.edu/ermrest/catalog/1/schema/Zebrafish/table/Synaptic%20Pair%20Study/annotation/tag%3Aisrd.isi.edu%2C2016%3Atable-display

```
{
  "*": {
    "row_order": [
      {
        "column": "RID", 
        "descending": true
      }
    ], 
    "page_size": 4
  }, 
  "row_name": {
    "row_markdown_pattern": "{{{ID}}}"
  }
}
```
I need to restrict the page-size because of the embedded plotly iframes which really choke some browsers when there are too many on one page.

**Comment by amitjha21** [comment]
This requires changes in `chaise`.

**Comment by amitjha21** [comment]
This has been merged into the `chaise` master. Assigning to @karlcz and @hongsudt  to verify and close it.
