### ISSUE TITLE
Display name hueristics for table and columns

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#60]
Use display name hueristics annotation to determine the display name transformation e.g. "My_Table" -> "My Table" or "my_table" -> "My Table". 

We probably need to define a chaise config, a new annotation at the schema and table level on how to derive the display name instead of annotating every columns.. Assigning this to @robes and @karlcz to come up with the annotation syntax.

**Comment by karlcz** [comment]
@robes I've drafted annotation support for this in 2015:display.name_style

**Comment by robes** [comment]
@karlcz The only issue I can see is that the concept of a "title case" or at least the implementation of a title case may be language dependent. That is, is this an English only feature? Would we know how to implement this for any other language? We have a couple options, either we say this is a feature that works for model element names that are use the Latin-1 charset. Other option, we deprecate this feature and have all our databases updated to use a column name exactly as they want it to be displayed. Personally, (although I think I created this monster) I am not fond of this behavior in our apps... :(

I would actually prefer to deprecate this feature. (I think)

Since we've now added so much to this annotation why don't be just update it from `tag:misd.isi.edu,2015:display` to `tag:isrd.isi.edu,2016:display` too?

**Comment by hongsudt** [comment]
@robes Let's assume that this feature will only work for Latin-1 charset (which is pretty much all our deployments).

**Comment by karlcz** [comment]
I think the spec should be open-ended.  We should **not** have to talk about something like Latin1 here. The concept of word-splitting and casing are language specific but well understood.  Our implementation may be best effort.  It is OK to ignore an annotation if an implementation doesn't know how to handle it...
- I expect we'll split words on whitespace, hyphen, and underscore.  A better implementation might apply language-specific heuristics.
- I expect we'll call `toUpperCase()` or `toLocaleUpperCase()` on the first codepoint in each word after splitting.  I think these methods are supposed to be quite general and should do no harm, right?

**Comment by RFSH** [comment]
Does the `underline_space` mean just simply convert each underline to a space? 
Or it means split string on whitespace, hyphen, and underscore? So `a__-_b` would become `a b`.

**Comment by karlcz** [comment]
I think it means the Javascript behavior `"string".replace(/_/g, " ")`

**Comment by RFSH** [comment]
So shouldn't it be something like `str.replace(/[_\-]/g, ' ').replace(/\s\s+/g,' ')` to include multiple spaces and hyphens too?

**Comment by karlcz** [comment]
No we are not replacing anything except `_` -> ` ` for the
`underscore_space` mode.

Word-splitting is for the purpose of identifying word boundaries to
apply title-casing.  You do not replace or modify the word separators
but use them to identify the beginning-of-word characters that should
have toUpperCase() applied.

**Comment by robes** [comment]
A couple comments on `module._determineDisplayName` ands its usage, as it stands now.

- the display name's for all model elements will be precomputed. In most of our scenarios where we are only displaying a subset of model elements that means that we are doing preprocessing that could be avoided.
- does this function belong in utils and attached to `module` or could it just be a local function within the ermrest.js script? the answer depends on whether it ever gets used outside of ermrest.js.

**Comment by RFSH** [comment]
This function is used in `Schema`, `Table`, and `Column` class. It is called in their constructors to determine their display names. 

I thought the purpose of utilities.js is to extract the functions that are used in multiple places in ermrest.js file. If this is not the purpose, it can just be a local function in ermrest.js. `_toTitleCase` and `_underlineToSpace` should be local functions in ermrest.js too.

**Comment by RFSH** [comment]
#73 implemented this and #82 added the unit tests for it.
