### ISSUE TITLE
(inbound) pseudo-column support for filters in the path

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#614]
I would like to see the pseudo-column support filters in the path.

I.e., I would like to filter a nested table so that only some of the rows appear. However, this is _not_ an ACL situation, it is really a context situation. The same user can see the row in anther context.

This would be _very_ useful for the FaceBase deployment.

**Comment by robes** [comment]
FYI. I'm going to explore a work-around that might be suitable enough so that this issue might be unnecessary.

**Comment by hongsudt** [comment]
@robes which context are you referring to? Write or read? Can you be concrete on the usecase?

**Comment by RFSH** [comment]
@hongsudt I think this is the same as [chaise#1355](https://github.com/informatics-isi-edu/chaise/issues/1355) issue.
