### ISSUE TITLE
Versioned hatrac URL not supported

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#616]
I'm told that our implementation of the asset annotation does not include support for versioned URLs returned from hatrac.

**Comment by hongsudt** [comment]
Can you clarify on what's not supported?

The URL stored in hatrac through chaise should be versioned and
downloadable. I don't think we are aware of any problems in RBK.

**Comment by jrchudy** [comment]
This issue has been fixed. Re-assigning to @robes to verify it is working properly now.
