### ISSUE TITLE
Inconsistent visible columns processing

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#625]
We need to use a single, common visible column parsing routine that can handle all the syntactic variants and convert them (or reject if invalid) for the given application context.  A DBA should be able to set a single `*` context visible column list that functions correctly for all applications, if they don't want to bother customizing each context:

-  `"Column"`, `{"source": "Column"}`, and `{"source": ["Column"]}` are semantically equivalent and should be supported everywhere that regular columns are supported.  There should be no difference in ermrest query formulation regardless of which notation is used.
- `["S", "FK"]` and `{"source": [{"outbound": ["S", "FK"]}, "RID"]}` are semantically equivalent and should be supported everywhere that a single outbound foreign key is supported. There should be no difference in ermrest query formulation regardless of which notation is used.
- The generalized pseudo column syntax should be acceptable everywhere. If the path is too complex for the individual context, that pseudo column should be discarded. It should never cause an application failure.  (Right now, the "entry" contexts violate this rule.)
- The `"markdown_name"` and `"comment"` features of the pseudo column notation should be accepted and used for point-of-use customization in every application context, overriding any other column or foreign key annotation preference, even for the simple column and foreign key cases.

**Comment by RFSH** [comment]
The only contexts that are treated differently are `entry` (`entry/edit`, `entry/create`), and `filter`.

The reason that I'm not allowing the pseudo-columns in `entry` context is because I wasn't sure to what extend we actually want to support this. Only pseudo-columns that have a source without any foreignkey or just one outbound foreignkey? Anything other than that should be ignored? Or do we actually want to support the all-outbound pseudo-columns too?

And for `filter`, currently the way it works is that if you haven't defined the specific context, we're creating facets based on visible-columns in `compact` and related entities in `detailed`. Which we can change obviously. But I think the reason behind having specific `filter` context was to make sure that those are specifically defined for facet. There are some extra attributes that facet objects can have that are not applicable to columns (`choices`, `ranges`, etc.).

**Comment by karlcz** [comment]
I'm not suggesting any changes to the core functionality as far as
which pseudo-column types work in each app context. I'm only
requesting that we treat the different annotation variants as
equivalent where they have the same semantic meaning:

1. a local column
   - `"Column Name"`
   - `{"source": "Column Name"}`
   - `{"source": ["Column Name"]}`
2. a single outbound foreign key
   - `["Schema", "Constraint"]`
   - `{"source": [{"outbound": ["Schema", "Constraint"]}, "RID"]}`

These are not different kinds of pseudo column, but just different
notations for the same two core concepts. The DBA shouldn't have to be
intimately aware of implementation issues nor have to repeat
themselves just to put the same list into different "normal forms".

The only behavior change I am suggesting is that we accept all
equivalent notations in all contexts and include support for whatever
extra display options are possible in the more explicit
syntax. E.g. `"markdown_name"` or `"comment"` fields on a pseudo
column should override any other column or table display annotation
that would otherwise be applied in their absence.

We would still have the restriction that more general source paths
are not supported in some contexts, and those should be filtered out
rather than having the app fail with an exception.  Data-entry of
course can only handle editable fields of the record (scalar columns
and single-hop outbound foreign keys), so it should discard any other
more complex pseudo columns in the list.

If a pseudo column includes initial filter state, I think that state
should just be ignored in non-filtering contexts rather than discarding
the whole pseudo column.

A general principle should be that a single master visible-column list
on the "*" context should be technically possible to exercise all
available functions in all app contexts.  Each app context should
consume the subset that is meaningful and skip the rest, without
causing app failures.  A DBA should only have to configure specific
sub-contexts when they actually want to choose a different subset of
the available features.

**Comment by karlcz** [comment]
I forgot to mention, the filter app context should discard pseudo
columns that use aggregation, since ermrest does not allow you to
express filters over aggregate results.

I don't think it would be appropriate to just discard the aggregate
function while keeping the pseudo column. Aggregation is an important
part of the pseudo column semantics (unlike filter state which is just
more of an initial/default controller state which the user can change
at runtime).

**Comment by RFSH** [comment]
I changed the logic of pseudo-columns so they are the same in all the contexts of visible-columns list. Since `filter` context is used to define an actual filter and not just list of columns, it remains as before and different from other contexts.
