### ISSUE TITLE
Navbar on top of error modal

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrestjs#628]
If the application throws a terminal error that is unrelated to fetching the session or displaying the navbar, the navbar should remain on top of the modal overlay. This will allow users to navigate away from broken links or sign in.

**Comment by RFSH** [comment]
Issue moved to [informatics-isi-edu/chaise #1555](https://github.com/informatics-isi-edu/chaise/issues/1555) via [**ZenHub**](https://www.zenhub.com/)
