### ISSUE TITLE
Filter broken for json/jsonb column type

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#632]
When an ERMrest filter predicate is being formed for a json or jsonb column, the value literal must be a URL encoded JSON value.

For example, go to the [Image table](https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Image)
and select the first item `"ready"` in the "Status" facet at the bottom of the facet list.  You'll get a 400 Bad Request terminal error.

The problem is that the ERMrest URL sent to the server has `Status=ready` as a filter rather than `Status=%22ready%22` which would be the proper representation of the JSON value `"ready"`.

**Comment by RFSH** [comment]
This should be fixed now. I [made sure](https://github.com/informatics-isi-edu/ermrestjs/commit/af4d0a1ac3b65dfd4c446410efc70a3216dadd41) the filter that we're passing is JSON parsable.
