### ISSUE TITLE
Buggy Logic in Read And SetSamePaging

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#635]
## Summary

In `read` we have a logic of adding shortestkey to the sort modifiers. This bug is related to the case of not having any sort modifiers in the url, and having a `row_order` on the table. In that case we were using the sortObject that is defined on `row_order` without applying any extra logics. Which was inconsistence with other parts of the code (paging and sorting).

Also the `setSamePaging` should be updated to be aligned with other parts of the code.

## Original Discussion

@karlcz commented on [Tue May 15 2018](https://github.com/informatics-isi-edu/chaise/issues/1523)

1. Start at [this synapse-dev record page](https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Cohort%20Analysis/RID=10DG)
2. Click the "Add" button on top of the "Cohort" related entity section.
3. See an error instead of expected modal picker

    Invalid Page Criteria
    sort and before should have the same number of columns
    Click OK to reload this page without Invalid Page Criteria

In the network console of the browser, I don't see any corresponding ermrest request that generates an error. This seems to be an error being synthesized on the front-end.

In this use case, the `Cohort Analysis` record is being linked to `Synaptic Study Pair` records via the binary association table `Cohort Analysis_Synaptic Study Pair`.

---

@karlcz commented on [Wed May 16 2018](https://github.com/informatics-isi-edu/chaise/issues/1523#issuecomment-389619023)

This is triggered when the linked table's row_order annotation ends with `{"column": "RID"}` rather than just plain `"RID"`.

---

@RFSH commented on [Wed May 16 2018](https://github.com/informatics-isi-edu/chaise/issues/1523#issuecomment-389623138)

@karlcz The issue is related to the logic of adding shortestkey to the sort modifier. This is only happening when you have a `row-order` defined and no sort modifier is given to the reference. We were getting the sort modifiers from the `row-order`, and we were appending the shortestkey without checking if it exists in the `row-order` or not.

By the way you have to define your _sortkey_ in the `{"column": COL_NAME}` format. Plain column name will be ignored.

---

@karlcz commented on [Wed May 16 2018](https://github.com/informatics-isi-edu/chaise/issues/1523#issuecomment-389627594)

Hmm, does the column_order support bare column names in the list?  I
thought I had many of these annotations and thought they were working
at some point w/ bare column names...

---

@RFSH commented on [Wed May 16 2018](https://github.com/informatics-isi-edu/chaise/issues/1523#issuecomment-389630885)

The syntax for `column_order` is different from `row_order`. We might want to change this, but based on the annotation document the `column_order` is a list of column names, while the `row_order` is a list of objects.

**Comment by RFSH** [comment]
This has been resolved. Going to the given url is not throwing error anymore.

**Comment by RFSH** [comment]
@karlcz Can you please verify this? This is related the issue that you created in chaise and I moved it to here (The issue of clicking on add in the related entities would throw terminal error).

**Comment by karlcz** [comment]
It's not crashing, but I see a funny behavior from the row_order logic.  I have annotations like:

```
{
  "*": {
    "row_order": [
      {
        "column": "RCT", 
        "descending": true
      }, 
      {
        "column": "RID"
      }
    ], 
...
}
```

But Chaise is choosing a sort like:

`@sort(RCT::desc::,RID::desc::,RID)`

This has a descending-mode RID sort that shouldn't be there and a duplicate RID which is also pointless.

The sort configured in Chaise  via annotation should follow the descending/ascending flags independently for each sort column, not propagate a descending flag between columns.  And when deciding to add the shortest key to the sort, you need to disregard descending/ascending mode.  If either is present, that is sufficient to avoid requiring a shortest key to be appended.

**Comment by RFSH** [comment]
There was a bug in the logic of adding shortestkey which I fixed and added to master. I'm going to close this issue and create another one for reverting the `row_order` changes that I made.
