### ISSUE TITLE
support filename_ext_filter

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#636]
Reference: https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2017-asset

This is important for enforcing data standard rules. I.e., if I only want jpeg and png in a "thumbnail" table and want to safeguard against tiff (which don't render online) that an unknowing user might upload. We have many more examples beyond this simple one.

**Comment by jrchudy** [comment]
This is already supported in `ermrestJS`. Closing this issue. There is a corresponding issue in `chaise` [here](https://github.com/informatics-isi-edu/chaise/issues/1463).
