### ISSUE TITLE
Indicator for associative tables

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#64]
For background, see the discussion here:
https://en.wikipedia.org/wiki/Associative_entity

It seems like it would be useful to add a property to the `Table` class to indicate if it is an "associative table" (i.e., a table that serves as the data structure for associative entities, per the background discussion). We could also indicate the arity of the associative table, but that's not strictly necessary as its anyway based on the length of the foreign key references container.

Simple proposal:

```
Table
  .associative /* true or false */
```

It could be implemented as a getter property so that it is computed on demand (and should be computed only once at that). It doesn't need to be a getter property if its trivial to detect during the introspection routine.

This issues comes up a lot with UI layers because the user often does not need to see the associative tables in the display.

**Comment by hongsudt** [comment]
This issue is related to #139. Instead of general association, #139 will be more specific and set a flag for pure binary association.

**Comment by hongsudt** [comment]
@RFSH why is this issued blocked?

**Comment by RFSH** [comment]
@hongsudt The PR is under review, that's why I changed the pipeline to Blocked.

**Comment by RFSH** [comment]
We currently have an indicator for "pure and binary association" tables (`Table._isPureBinaryAssociation()`).  It's a restricted version of what this issue describes. 
@hongsudt  Should we keep this issue open or close it?

**Comment by hongsudt** [comment]
I will close this issue for now.
