### ISSUE TITLE
Upload the same file content to the same hatrac namespace generate multiple files on server

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#649]
I updated a file to "Protocol.Figure" and then delete then re-uploaded. I would expect to see only one file on hatrac, but it seemed like multiple files were created on hatrac most of them have 0 byte but with the same filename. 

https://staging.gudmap.org/chaise/record/#2/Protocol:Figure/RID=W-R0BC

**Comment by hongsudt** [comment]
@karlcz confirmed that it is the frontend that started an upload job that got aborted or never got cleaned up.. I could see this consistently  on rbk-staging. However, staging doesn't have the latest code.

**Comment by jrchudy** [comment]
The changes to fix this issue have been merged into master. Reassigning to @hongsudt  to verify it no longer happens and close this issue.
