### ISSUE TITLE
Support non-trivial paths in DataPath with ability to specify final projection

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#65]
Currently, the `DataPath` only supports linear paths. However, an ERMrest query is really a tree not a linear path. We need to be able to construct these non-linear paths in order to support interfaces such as faceting and matrix views which depends on them.
### Background

A data path like this:

```
...a:=A/B/C/$a/D/E...
```

Could be visualized as a tree like this:

```
A--B--C
 \-D--E
```

The URL being a linear hierarchical path forces us to serialize this tree into a path.
### Revised interface

This issue proposes the following changes to the API to (1) accommodate the actual tree like structure and (2) to be more explicit about the _join_.

First, remove the `extend` method from `DataPath` and add a `root` to it, which is the pathtable for the table it is initialized with. Second, introduce a `join` method on the `PathTable`.

```
DataPath(table)
 .root /* path table corresponding to table in constructor */

PathTable(...)
 .join(joinspec) : returns a new PathTable per the joinspec
```

In the simplest form the `joinspec` is a `Table` instance. This corresponds to the _implicit join_ mode of an ERMrest path. The `joinspec` will also allow for the explicit join specification of either a foreign key of the current PathTable or a foreign key of another table that references the PathTable.
### Example usage

The following example uses A - E as table definition instances and a - e as path table instances, respectively.

```
var path = DataPath(A); /* path -> A */
var a = path.root;
a.join(B).join(C); /* path -> A/B/C */
a.join(D).join(E); /* path -> a:=A/B/C/$a/D/E */
```

Note that the call `a.join(B)` essentially returned the path table `b` corresponding to the join with `B` thus the chaining of the `.join(C)`. Also, `var a` was unnecessary as we could have used `path.root.join(...)` in its place.

**Comment by hongsudt** [comment]
@robes is this issue still relevant?

**Comment by robes** [comment]
It might be. And I may need to start working on this next in fact.

**Comment by robes** [comment]
Since faceting has been implemented without need for this issue, we should close this unless some other use case requires that we revisit it.

FWIW, this functionality has been implemented in the python deriva-py API, where the use case for ad hoc path building remains valid.
