### ISSUE TITLE
File upload: Filenames with whitespace are versioned when identical

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrestjs#658]
When a file already exists in hatrac with the same content, name, and size, we shouldn't upload that file again. If a filename includes a whitespace character, [this check fails](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/hatrac.js#L429) because `ermrestJS` changes the filename from something like `file name.jpg` to `file_name.jpg`.

The immediate thought is that we should only rely on the checksum (`md5`) and `size` of the file.

**Comment by hongsudt** [comment]
@jrchudy is this still an issue?

**Comment by jrchudy** [comment]
Nope. We changed the "check" in `ermrestJS` to only verify the file's md5 and size.
