### ISSUE TITLE
Custom Span Markdown Inline Block

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#659]
Originally I created the #653 because we wanted to be able to define a block to be used in row-name. We wanted to apply some styles to the row-name text. And when we're using this row-name for foreignkey value, we can attach the link to this styled value. I assumed that we can have a block in row-name. But then I realized that we're using inline markdown in row-name. Therefore all the custom blocks that we have defined won't work in row-name.

Only inline markdown tags will work for row-name. I don't exactly remember why we're using the inline rendering, but it seems like the right thing to do.

To be able to achieve what we wanted, we should define a new custom tag `:::span :::`. This should be added to the `inline` rules in the markdown-it. This requires some changes to the plugin (markdown-it-container) that we are using since that plugin is only creating custom blocks (not inline).

**Comment by RFSH** [comment]
I realized we can simply add the span the same way we're adding subscript and superscript. This is the current syntax for these two tags:

- subscript: `~text~ another` which will be `<sub>text</sub> another` (`~test~{.class-name}` for adding attributes).
- superscript: `^text^ another` which will be `<sup>text</sup> another` (`~test~{.class-name}` for adding attributes).

Now we just need to define what should be the opening and closing tag for `span`. These are the suggestions:

1.  `:` for both opening or closing, but it might collide with other existing tags that we have. 

2. `{:` for opening and `:}` for closing tags. 

~3.~ We could follow the same routine for other custom tags that we have which is `:::span` for opening and `\n:::` for closing. But having newline in the tag implies a block and not inline tag. While span should be inline tag. Also it's going to be confusing when we want to attach attributes, since the attributes for inline go outside the definition and not inside.

4. Other suggestions?

@hongsudt

**Comment by hongsudt** [comment]
I like option 2 but @karlcz has a point that we use a lot of that with mustache.. Do we have a better character? If not, let's go with 2..

**Comment by RFSH** [comment]
We decided to go with the more explicit `:span:` for opening and `:/span:` for closing tag.

**Comment by RFSH** [comment]
This has been merged with master. 
@hongsudt Can you please try having span in your row-name? I modified one of our row-name test cases and it works as expected. You can have empty spans too. You can use something like `:span:{{{col_val}}}:/span:{.class-name}`.
