### ISSUE TITLE
default asset presentation should only render the filename not the entire path

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#665]
Currently, we only apply this rule for hatrac URL. I would like to apply the rule to any URL path, so that the asset can be presented succinctly.. 

For example: on the data commons demo site, the URL paths are quite long and not nice presented especially in the compact context. https://nih-commons.derivacloud.org/chaise/recordset/#1/public:KC7%20Search%20Demo

**Comment by karlcz** [comment]
On Jun 19, Hongsuda modulated:
> Currently, we only apply this rule for hatrac URL. I would like to
> apply the rule to any URL path, so that the asset can be presented
> succinctly..
>

However, for off-site download URLs, I think it is bad practice to
completely hide the remote site info.  Often, you'll see something
like the following markdown:

    [foo (example.org)](https://example.org/path/foo)

**Comment by hongsudt** [comment]
We could leave the full URL in the detailed context..

**Comment by RFSH** [comment]
The change is. In compact contexts if the filename column doesn't exist and it's not from hatract, we're returning whatever comes after the last `/`.
