### ISSUE TITLE
Change title-casing feature slightly

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#669]
I think the title-case function, when enabled, should only mangle the case of strings that are all lower-case, but preserve case when the model name is already using capitalization.  This would cover cases like `RID` and other acronyms as well as any funkier values.  It won't handle a situation where a modeler has retained capitalization that they didn't want to show to users.

I don't know if anybody will disagree with this or think we need to keep two modes.  I can imagine using some other truthy string to enable a second mode.  E.g. `"force"` to force title-casing if we want to make the default weaker like I propose.

**Comment by hongsudt** [comment]
Instead of this general rule, can we be more specific and only handle all
capitals or just the system columns?

**Comment by karlcz** [comment]
I can't see any good reason for limiting it like that.  If you really think someone depends on title-casing of arbitrarily-cased inputs, I think that argues for having a config option to enable the two levels of strength.  If you also think that the default has to remain as it is today, then leave `true` doing what I proposed above as `"force"` and instead introduce a flag for the weaker form like `"safe"` or `"from_lower"`.

**Comment by RFSH** [comment]
Moved to wishlist.
