### ISSUE TITLE
add .comment to all relevant model elements

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#67]
Add .comment to 
- [ ] table
- [ ] schema
- [ ] key
- [ ] foreign key

**Comment by karlcz** [comment]
ERMrest supports comment on schema, table, column, key, and foreign key.

**Comment by hongsudt** [comment]
What's the difference between column comment and key/foreign key comments?
When should key/foreign key comments be displayed to the user?

**Comment by robes** [comment]
Let's expand the scope of this to all the relevant model elements that don't already have the `.comment`. Karl listed them above.

**Comment by howdyjessie** [comment]
I opened PR #95 for review.

**Comment by howdyjessie** [comment]
The PR has been merged but I should write some unit tests with Chirag's new unit testing setup.

**Comment by howdyjessie** [comment]
I was sidetracked with work on #83, but now the tests are available for review on PR #125.
