### ISSUE TITLE
Disable Name Style Inheritence For System Columns

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#675]
You could use [display annotation](https://github.com/informatics-isi-edu/ermrest/blob/master/docs/user-doc/annotation.md#2015-display) to define name style for the displayname of schema, table, and columns.

Most deployments are setting these on the schema level, and we don't want the system columns to inherit those. Although if `name_style` is defined on any of the system columns, it should be honored.

**Comment by carlkesselman** [comment]
I probably don’t understand this fully, but it seems to me that system columns should display in caps without requiring annotations.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Jul 16, 2018, at 11:34 AM, Aref Shafaei <notifications@github.com<mailto:notifications@github.com>> wrote:


You could use display annotation<https://github.com/informatics-isi-edu/ermrest/blob/master/docs/user-doc/annotation.md#2015-display> to define name style for the displayname of schema, table, and columns.

Most deployments are setting these on the schema level, and we don't want the system columns to inherit those. Although if name_style is defined on any of the system columns, it should be honored.

**Comment by karlcz** [comment]
The problem being described by Aref is that a catalog, schema, or
table-level display annotation is "inherited" by unadorned columns and
this changes system column presentation in a way you don't like. If it
weren't for those annotations, the columns would present correctly as
the default behavior in Chaise is to preserve the raw column name.

So, by suppressing this inheritence behavior for system columns, an
admin can still use global title-case settings to conveniently
customize their non-system columns without having to explicitly
override each system column to put it back into an unmodified state.

**Comment by carlkesselman** [comment]
Got it.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Jul 16, 2018, at 1:32 PM, Karl Czajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:

The problem being described by Aref is that a catalog, schema, or
table-level display annotation is "inherited" by unadorned columns and
this changes system column presentation in a way you don't like. If it
weren't for those annotations, the columns would present correctly as
the default behavior in Chaise is to preserve the raw column name.

So, by suppressing this inheritence behavior for system columns, an
admin can still use global title-case settings to conveniently
customize their non-system columns without having to explicitly
override each system column to put it back into an unmodified state.

**Comment by RFSH** [comment]
This has been [merged with master](https://github.com/informatics-isi-edu/ermrestjs/pull/680)
