### ISSUE TITLE
Create an enumeration of possible annotation uris

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#68]
I am not sure whether we already have this, if not, we should have an equivalent of enum type to list annotation tags. 

I adapted the js example I found online to demonstrate the concept. 

```
var ANNOTATION = {
  DISPLAY : "tag:misd.isi.edu,2015:facets, 
  DEFAULT: "tag:misd.isi.edu,2015:default 
};
```

We should do the same for context.

**Comment by robes** [comment]
We could roll this into the ermrestjs `Annotation` class or `Annotations` class. I would also rather see the keys be more explicit: `TAG_MISD_ISI_EDU_2015_DEFAULT` instead of just `DEFAULT`.

**Comment by robes** [comment]
I'll edit the issue description at time.

**Comment by robes** [comment]
I'm going to leave the original issue description just so we can capture the discussion here. Stepping back a bit, we have to ask "what code do we expect will make annotation lookups?" We actually would anticipate ermrestjs itself will consume most of the annotations and clients (such as Chaise) will use interfaces defined in the `ERMrest` object model _rather than_ checking for annotations. So first decision is at this point _we do not_ need to introduce an enumeration as a public api, but rather this is used only for internal operations within ermrestjs. Second question, "what then is the purpose of these enumerations?" It is to avoid rewriting (or copy-and-pasting) the same string in multiple places. So if we only use the annotation string in a lookup in exactly one location, we do not need a variable for it, just use the string in that one location. Third question, "where should we define these variables for the annotation name strings?" The ERMrest module is separated into multiple files (.js scripts) following a JavaScript pattern for writing such modules. Once such file is called `utility.js` which can be used for this purpose. Here's a simple rule to follow:

1. if you need to make a lookup based on a tag name only in one call site, simply use a string (e.g., `"tag:isrd..."`)
2. if you have more than one use for the tag name string, but only in one script comprising ERMrest, then define it toward the top of the closure, and keep it local to that closure (e.g., `var _tag_default = "tag:...default"`)
3. if you have more than one call site in more than one script, then define the variable in the `utility.js` script and add it to the module (e.g., `module._tag_default = "tag:...default"`) and it may then be used by code in different ermrestjs scripts (e.g., referencing `module._tag_default` somewhere)

Note that this is not being added to the _public_ interface. Code outside of the various ermrestjs scripts are not intended to use these variables. Hence we follow the underscore prefix convention `_variableName`, which by convention indicates that the variable should be considered private to the module and clients are at least warned not to use it.

Finally, there are a variety of more sophisticated ways of emulating enumerations in object oriented languages, that don't natively support enumerations, however we advocate keeping things simple. There is no reason to follow one of the more sophisticated patterns for enums here. Simply using a variable in place of the literal string is sufficient for our use here. If in the future we realize we do need this enum for the _public_ api then we can revisit the topic.

**Comment by robes** [comment]
Maybe the above comment belongs in a ermrestjs developer guide.

**Comment by RFSH** [comment]
It's true that one purpose of creating this enumeration is to avoid rewriting and copy-pasting. However I can see other benefits to that:
- To change each of the annotations, we just have to just change one variable that is defined in one place. We don't need to search for that string in several files.
- We can easily figure out which annotations are currently supported application-wide. We don't need to search in different files to see if they have the annotations or not.

Based on these, I think it's useful to have a variable in the `utilities.js` file, like this:
```javascript
module._annotations = {
     DISPLAY : "tag:misd.isi.edu,2015:facets", 
     DEFAULT: "tag:misd.isi.edu,2015:default" 
};
```

**Comment by jrchudy** [comment]
Going with what @RFSH mentioned, I think it could actually be defined as an angular `constant` on the module, which would then have it behave like any other angular `service`, `factory`, or `provider`. Meaning you could very easily inject the Annotations constant anywhere it's needed in angular.

**Comment by robes** [comment]
@RFSH I agree with your second bullet, and that's good enough for me to be on board with your proposal.

**Comment by hongsudt** [comment]
@RFSH if you are doing this as @robes suggested, maybe we can now close this issue?

**Comment by hongsudt** [comment]
Actually, @shinyichen can you please review and close this issue?

**Comment by RFSH** [comment]
@hongsudt I was waiting for the Column order issue to be closed and then work on this issue.
