### ISSUE TITLE
Change System Columns "Not Allowed" Message Back

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#689]
Change it back to "Automatically generated" because that's the more appropriate term. This is happening because users don't have "insert" access to those columns.

**Comment by hongsudt** [comment]
Why is "Not Allowed" appropriate for the columns that they can't insert?

**Comment by RFSH** [comment]
This is what [we decided](https://github.com/informatics-isi-edu/chaise/issues/1609) to change it to. If user doesn't have "insert" access we're saying "Not Allowed" for the column.

Now the issue is that for system columns the "insert" access is missing too. So even for those columns we're saying "Not Allowed" which as we discussed "Automatically generated" would be more appropriate.

**Comment by hongsudt** [comment]
should we then handle the system-columns explicitly then?


________________________________

**Comment by RFSH** [comment]
Yes, and it should be very simple.
