### ISSUE TITLE
Bug Fixes in ERMrestJS

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#691]
- Make sure we're hiding the foreignkey from related table to the main, in `compact/breif/inline` too (we're doing it only for `compact/inline`). 
- Add `numeric` column type to use facet range picker by default.
- Add `$fkeys` support to `page.content`

**Comment by RFSH** [comment]
[This commit](https://github.com/informatics-isi-edu/ermrestjs/commit/29250a5f816ea876713a5f6e878d61f672ad9262) fixes all these three bugs and adds test cases for them.

@hongsudt can you please verify these?

**Comment by hongsudt** [comment]
It is now working here:
https://dev.rebuildingakidney.org/chaise/record/#2/Cell_Line:Mouse_Strain/RID=Q-2CP0
