### ISSUE TITLE
default tooltip for system columns

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#695]
If the comments for the system columns are not present, we should automatically apply the following tooltips to them: 
* RID: Persistent, citable resource identifier
* RCB: Record creator
* RMB: Record last modifier
* RCT: Record creation timestamp
* RMT: Record last modified timestamp

**Comment by RFSH** [comment]
The changes for this issue have been merged into master, assigning to @hongsudt for verification.

**Comment by hongsudt** [comment]
@bugacov can you help review this issue?

**Comment by bugacov** [comment]
@hongsudt ... This seems to be ok. Here a page in fb dev w/ no comments defined for the system columns and the default comments mach the ones in the issue 

https://dev.facebase.org/chaise/record/#1/vocab:prefix/RID=1-4VVR

**Comment by hongsudt** [comment]
Thanks. I am closing the issue
