### ISSUE TITLE
Revise the datapath context and access interfaces

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#70]
From discussions with @karlcz, we have the following idea...

The datapath _context_ is identified by the last entity in a datapath like `entity/A/B/C` where `C` is the context or `entity/a:=A/B/C/$a` where `A` is the context, both of the _entity_ access interface.

The proposed change would drop `context` from the `DataPath` instance and move the access interfaces (entity, attribute, attributegroup,...) to the `PathTable` instance which therefore implicitly identifies the _context_ of the invocation.

See also #65 as a corequisite of this change.

### Revised interface
```
PathTable
 .entity
 .attribute
 ...

Entity
 .get()
 .delete()
 ...
```

### Example usage:
```
var dp = DataPath(A);
var a = dp.root;
a.join(B);
var promise = a.entity.get(); /* gets all entities for ...a:=A/B/$a */
```

**Comment by hongsudt** [comment]
@robes is this still relevant?

**Comment by robes** [comment]
no

**Comment by robes** [comment]
I think this issue is obviated by the revised reference api
