### ISSUE TITLE
hueristics for export 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#701]
If the export annotation doesn't exist, we should apply the following heuristics that generate a bag of files consisting of: 
- [x] csv file for the main entity
- [x] csv file for all the related tables (whether in-line or not)
  - single hop : the fk to the main entity should be there already
  - multi-hops: add fk to the main entity as an extra column
- [x] fetch output for all the columns that have asset annotation

**Comment by RFSH** [comment]
In the following I will try to explain how export is working and how I am generating the default export template.



Based on current definition of the annotation, you need to pass `api`, `table` (in "schema:table" format), and an optional `path`. This is how export is using these:

1. If the given table is the same as the current table that reference is representing:

```
<api>/<current_reference_path>/<path>
```

2. If the given table is not the same as the current table:

```
<api>/<current_reference_path>/X:=<table>/<path>
```

So it's assuming that the table that you're defining (X) has a direct relationship with the reference table (M). But for the inbound related tables that have longer path this is not true, so I ended up defining them this way:

```
{
  "table": "schema:main_table",
   "path": "the foreignkey path to the related table in ()=() format"
}
```

Another requirement was adding the main table's key to the projection list. To do so, I had to use the alias that I'm using in the parser logic. I think we should add this to the export documentation, I am always using the `M` alias for the table that is being projected. 


## Example

Having the following ERD, with the given annotation for the table.

![ERD](https://dev.isrd.isi.edu/~ashafaei/wiki-images/pseudo_col_erd.png)

```javascript
"tag:isrd.isi.edu,2016:visible-foreign-keys": {
  "*": [
    ["schema", "fk2_cons"], 
    ["schema", "fk3_cons"],
    {
      "source": [
        {"inbound": ["schema", "fk3_cons"]},
        {"outbound": ["schema", "main_f3_cons"]},
        {"inbound": ["schema", "f4_cons"]},
        "f4_id"
       ]
     }
  ]
}

```

This would be the generated default export template:


```javascript
{
  "name": "default_template",
  "format_name": "BAG",
  "format_type": "BAG",
  "outputs": [
    {
      "destination": {
        "name": "main",
        "type": "csv"
      },
      "source": {
         "api": "entity",
        "table": "schema:main"
      }
    },
    {
      "destination": {
        "name": "f2",
        "type": "csv"
      },
      "source": {
        "api": "entity",
        "table": "schema:f2"
      }
    },
    {
      "destination": {
        "name": "f3",
        "type": "csv"
      },
      "source": {
        "api": "attributegroup",
        "table": "schema:main",
        "path": "(id)=(main_f3:id_main)/(id_f3)=(f3:f3_id)/main_table_id_0:=M:id,f3_id;f3_text,f3_int"
      }
    },
    {
      "destination": {
        "name": "f4",
        "type": "csv"
      },
      "source": {
        "api": "attributegroup",
        "table": "schema:main",
        "path": "(id)=(main_f3:id_main)/(id_f3)=(f3:f3_id)/(f3_id)=(f4:fk_to_f3)/main_table_id_0:=M:id,f4_id;fk_to_f3,f4_text,f4_int"
       }
    }
  ]	
}
```


I'm not sure if what I did makes sense and we should encourage it or not. We should discuss about this.

**Comment by carlkesselman** [comment]
Can we set up a meeting with ythe entire team to discuss.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Sep 27, 2018, at 10:02 AM, Aref Shafaei <notifications@github.com<mailto:notifications@github.com>> wrote:


In the following I will try to explain how export is working and how I am generating the default export template.

Based on current definition of the annotation, you need to pass api, table (in "schema:table" format), and an optional path. This is how export is using these:

  1.  If the given table is the same as the current table that reference is representing:

<api>/<current_reference_path>/<path>


  1.  If the given table is not the same as the current table:

<api>/<current_reference_path>/X:=<table>/<path>


So it's assuming that the table that you're defining (X) has a direct relationship with the reference table (M). But for the inbound related tables that have longer path this is not true, so I ended up defining them this way:

{
  "table": "schema:main_table",
   "path": "the foreignkey path to the related table in ()=() format"
}


Another requirement was adding the main table's key to the projection list. To do so, I had to use the alias that I'm using in the parser logic. I think we should add this to the export documentation, I am always using the M alias for the table that is being projected.

Example

Having the following ERD, with the given annotation for the table.

[ERD]<https://camo.githubusercontent.com/d6d543a466b2d7ddaba685fcdbc2a34ceeec89b1/68747470733a2f2f6465762e697372642e6973692e6564752f25374561736861666165692f77696b692d696d616765732f70736575646f5f636f6c5f6572642e706e67>

"tag:isrd.isi.edu<http://isrd.isi.edu>,2016:visible-foreign-keys": {
  "*": [
    ["schema", "fk2_cons"],
    ["schema", "fk3_cons"],
    {
      "source": [
        {"inbound": ["schema", "fk3_cons"]},
        {"outbound": ["schema", "main_f3_cons"]},
        {"inbound": ["schema", "f4_cons"]},
        "f4_id"
       ]
     }
  ]
}


This would be the generated default export template:

{
  "name": "default_template",
  "format_name": "BAG",
  "format_type": "BAG",
  "outputs": [
    {
      "destination": {
        "name": "main",
        "type": "csv"
      },
      "source": {
         "api": "entity",
        "table": "schema:main"
      }
    },
    {
      "destination": {
        "name": "f2",
        "type": "csv"
      },
      "source": {
        "api": "entity",
        "table": "schema:f2"
      }
    },
    {
      "destination": {
        "name": "f3",
        "type": "csv"
      },
      "source": {
        "api": "attributegroup",
        "table": "schema:main",
        "path": "(id)=(main_f3:id_main)/(id_f3)=(f3:f3_id)/main_table_id_0:=M:id,f3_id;f3_text,f3_int"
      }
    },
    {
      "destination": {
        "name": "f4",
        "type": "csv"
      },
      "source": {
        "api": "attributegroup",
        "table": "schema:main",
        "path": "(id)=(main_f3:id_main)/(id_f3)=(f3:f3_id)/(f3_id)=(f4:fk_to_f3)/main_table_id_0:=M:id,f4_id;fk_to_f3,f4_text,f4_int"
       }
    }
  ]
}

I'm not sure if what I did makes sense and we should encourage it or not. We should discuss about this.

**Comment by carlkesselman** [comment]
BTW, here is my spec. Note I have fetch and nonfetch versions,


templates': [{'format_name': 'BDBag (Holey)',
                'format_type': 'BAG',
                'name': 'default',
                'outputs': [
                    {'destination':
                         {'name': 'Collection', 'type': 'csv'},
                     'source': {'api': 'entity', 'table': 'Common:Collection'}
                     },
                    {
                        'destination': { 'name': 'Biosample', 'type' : 'csv'},
                        'source': {'api': 'attributegroup',
                                   'table': 'Common:Collection',
                                    'path': '(RID)=(Collection_Biosample:Collection)/(Biosample)=(Biosample:RID)/CollectionRID:=M:RID;Capillary_Number,Sample_Position',
                                   }
                    },
                    {'destination': {'name': 'Processed_Tomography_Data',
                                     'type': 'csv'},
                     'source': {'api': 'attributegroup',
                                'table': 'Common:Collection',
                                'path': '(RID)=(Collection_Biosample:Collection)/(Biosample)=(Biosample:RID)/(RID)=(Processed_Tomography_Data:Biosample)/CollectionRID:=M:RID;Dataset,Biosample,Filename, url:=URL,length:=Byte_Count',
                                }
                     },
                    {'destination': {'name': 'Processed_Tomography_Data',
                                     'type': 'fetch'},
                     'source': {'api': 'attributegroup',
                                'table': 'Common:Collection',
                                'path': '(RID)=(Collection_Biosample:Collection)/(Biosample)=(Biosample:RID)/(RID)=(Processed_Tomography_Data:Biosample)/CollectionRID:=M:RID;url:=URL,md5:=MD5,length:=Byte_Count',
                                }
                     },
                    {'destination': {'name': 'XRay_Tomography_Data',
                                     'type': 'csv'},
                     'source': {'api': 'attributegroup',
                                'table': 'Common:Collection',
                                'path': '(RID)=(Collection_Biosample:Collection)/(Biosample)=(Biosample:RID)/(RID)=(Processed_Tomography_Data:Biosample)/CollectionRID:=M:RID;Dataset,Biosample,URL,Filename',
                                }
                     },
                    {'destination': {'name': 'XRay_Tomography_Data',
                                     'type': 'fetch'},
                     'source': {'api': 'attributegroup',
                                'table': 'Common:Collection',
                                'path': '(RID)=(Collection_Biosample:Collection)/(Biosample)=(Biosample:RID)/(RID)=(XRay_Tomography_Data:Biosample)/CollectionRID:=M:RID;url:=URL,md5:=MD5,length:=Byte_Count',
                                }
                     },
                    ]
                },
               {'format_name': 'BDBag',
                'format_type': 'BAG',
                'name': 'default',
                'outputs': [
                    {'destination':
                         {'name': 'Collection', 'type': 'csv'},
                     'source': {'api': 'entity', 'table': 'Common:Collection'}
                     },
                    {
                        'destination': {'name': 'Biosample', 'type': 'csv'},
                        'source': {'api': 'attributegroup',
                                   'table': 'Common:Collection',
                                   'path': '(RID)=(Collection_Biosample:Collection)/(Biosample)=(Biosample:RID)/CollectionRID:=M:RID;Capillary_Number,Sample_Position',
                                   }
                    },
                    {'destination': {'name': 'Processed_Tomography_Data',
                                     'type': 'download'},
                     'source': {'api': 'attributegroup',
                                'table': 'Common:Collection',
                                'path': '(RID)=(Collection_Biosample:Collection)/(Biosample)=(Biosample:RID)/(RID)=(Processed_Tomography_Data:Biosample)/CollectionRID:=M:RID;url:=URL,md5:=MD5,length:=Byte_Count',
                                }
                     },
                    {'destination': {'name': 'XRay_Tomography_Data',
                                     'type': 'download'},
                     'source': {'api': 'attributegroup',
                                'table': 'Common:Collection',
                                'path': '(RID)=(Collection_Biosample:Collection)/(Biosample)=(Biosample:RID)/(RID)=(XRay_Tomography_Data:Biosample)/CollectionRID:=M:RID;url:=URL,md5:=MD5,length:=Byte_Count',
                                }
                     },
                ]
               }

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Sep 29, 2018, at 9:21 AM, Carl Kesselman <carl@ads.isi.edu<mailto:carl@ads.isi.edu>> wrote:

Ok,
I have actually tried this for a collection and it works!  One thing that we will have to do is that if the object is an asset, we need to make the output a download, not a CSV.  We should also have the option of making it a fetch.

The notation is pretty dense.  Is there documentation for the path expressions?

We are really going to need to write up a tutorial on these.  Very important.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Sep 27, 2018, at 10:02 AM, Aref Shafaei <notifications@github.com<mailto:notifications@github.com>> wrote:


In the following I will try to explain how export is working and how I am generating the default export template.

Based on current definition of the annotation, you need to pass api, table (in "schema:table" format), and an optional path. This is how export is using these:

  1.  If the given table is the same as the current table that reference is representing:

<api>/<current_reference_path>/<path>


  1.  If the given table is not the same as the current table:

<api>/<current_reference_path>/X:=<table>/<path>


So it's assuming that the table that you're defining (X) has a direct relationship with the reference table (M). But for the inbound related tables that have longer path this is not true, so I ended up defining them this way:

{
  "table": "schema:main_table",
   "path": "the foreignkey path to the related table in ()=() format"
}


Another requirement was adding the main table's key to the projection list. To do so, I had to use the alias that I'm using in the parser logic. I think we should add this to the export documentation, I am always using the M alias for the table that is being projected.

Example

Having the following ERD, with the given annotation for the table.

[ERD]<https://camo.githubusercontent.com/d6d543a466b2d7ddaba685fcdbc2a34ceeec89b1/68747470733a2f2f6465762e697372642e6973692e6564752f25374561736861666165692f77696b692d696d616765732f70736575646f5f636f6c5f6572642e706e67>

"tag:isrd.isi.edu<http://isrd.isi.edu/>,2016:visible-foreign-keys": {
  "*": [
    ["schema", "fk2_cons"],
    ["schema", "fk3_cons"],
    {
      "source": [
        {"inbound": ["schema", "fk3_cons"]},
        {"outbound": ["schema", "main_f3_cons"]},
        {"inbound": ["schema", "f4_cons"]},
        "f4_id"
       ]
     }
  ]
}


This would be the generated default export template:

{
  "name": "default_template",
  "format_name": "BAG",
  "format_type": "BAG",
  "outputs": [
    {
      "destination": {
        "name": "main",
        "type": "csv"
      },
      "source": {
         "api": "entity",
        "table": "schema:main"
      }
    },
    {
      "destination": {
        "name": "f2",
        "type": "csv"
      },
      "source": {
        "api": "entity",
        "table": "schema:f2"
      }
    },
    {
      "destination": {
        "name": "f3",
        "type": "csv"
      },
      "source": {
        "api": "attributegroup",
        "table": "schema:main",
        "path": "(id)=(main_f3:id_main)/(id_f3)=(f3:f3_id)/main_table_id_0:=M:id,f3_id;f3_text,f3_int"
      }
    },
    {
      "destination": {
        "name": "f4",
        "type": "csv"
      },
      "source": {
        "api": "attributegroup",
        "table": "schema:main",
        "path": "(id)=(main_f3:id_main)/(id_f3)=(f3:f3_id)/(f3_id)=(f4:fk_to_f3)/main_table_id_0:=M:id,f4_id;fk_to_f3,f4_text,f4_int"
       }
    }
  ]
}

I'm not sure if what I did makes sense and we should encourage it or not. We should discuss about this.

**Comment by RFSH** [comment]
After reviewing the export annotation, we decided to make the following changes:

- Remove the `name` attribute since it's not used.
- Rename `format_name` to `displayname` and `format_type` to `type`.
- Remove the `table` attribute from the `outputs`, and make the `path` to be required. Then we're always going to create the path in the following format:

  ```
    <api>/<current reference path>/<path>
  ```
	
  So assuming you're writing export annotation for table `A` in schema `S`, If the old annotation was:
	
  ```
    "source": {
      "api": "entity",
      "table": "S:A"
    }
  ```
	It should be changed to
	
  ```
    "source": {
      "api": "entity",
      "path": "S:A"
    }
  ```
	
- Check whether path starts with `/` or not and handle it appropriately.
- Allow data modelers to define the export template in the schema level too and change how we're using the export annotation.  This is how we're processing the annotation:

  1. If the annotation is defined on table.

      1.1. There's no valid template (has type, displayname, and valid outputs) in the defined annotation: Don't show any export template to users.

      1.2. There's at least one valid template: Go through the list of valid templates and if they don't have `outputs`, use the default heuristics `outputs`.

  2. The annotation is missing on the table.

      2.1. The annotation is defined on schema: Do the same steps in 1.1 and 1.2.

      2.2. The annotation is missing from the schema: Create a default `bag` template with the default heuristics `outputs`.

When the changes are done, I will update the documentation to reflect these changes.

**Comment by RFSH** [comment]
The changes explained in the previous comment are ready to be merged. I am going to merge them by the end of this day unless there's an objection.

I also [updated the ioboxd documentation and raised a PR](https://github.com/informatics-isi-edu/ioboxd/pull/6) for it.

@carlkesselman @mikedarcy 
This is the list of what needs to be changed in the currently defined annotations:
- `name` attribute should be removed from each of the defined "template"s since it's not used.
- `format_name` must be renamed to `displayname`.
- `format_type` must be renamed to `type`.
-  Since we changed the way we're constructing the query, in `outputs` definition, you need to remove all the `table`s.  I added some examples to the ioboxd documentation on how `output` is going to generate the query.
   - If the table that is defined in the output is the same as the root table: you don't need to define any `path`.
   - Otherwise you have to define the `path`.

**Comment by RFSH** [comment]
The changes have been merged with master. I am going to close this issue. If we want further changes we should create a new issue, there are too many comments on this issue and it's hard to follow.
