### ISSUE TITLE
support required annotation

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#708]
We want a way to mark a column as required (e.g. same as not null), so that chaise can check for its mandatory entry. This should be a column level annotation (similar to immutable). 

The reason for this is that in the legacy repository such as gudmap that starts with bad data (e.g. rows will null value), we need a way to improve on data quality of new records.  

However, unless we fix the model, other clients will continue to supply bad records. 

@ljpearlman do I capture this correctly? 
@robes @karlcz @bugacov  thoughts?

**Comment by ljpearlman** [comment]
This looks good. The only thing is that I think this should apply only during record creation, not editing (since a person editing an old record might not know the correct value for the column).

**Comment by hongsudt** [comment]
I disagree on this though. If we don't enforce the mandatory fields in the editing mode, then we allow the data to be in the state where those (supposedly) mandatory fields are missing again (e.g. users could go to edit mode and then remove species, etc.). 

I think for the legacy data, if they want to edit them, they just have to deal with these missing values properly e.g. creating a unspecified or unknown values for those. Our ultimate goal should be to enforce the constraint checking anyway.

However, if we really want to accommodate for your use case above, we will probably need to use triggers instead of this feature.

**Comment by jrchudy** [comment]
@hongsudt support for the required annotation has been merged into master. Documentation can be found [here](https://github.com/informatics-isi-edu/ermrest/blob/master/docs/user-doc/annotation.md#tag-2018-required).

Reassigning to you for verification.

**Comment by RFSH** [comment]
I am going to close this issue due to inactivity. If there's any issue with this feature we can create another issue.
