### ISSUE TITLE
Support catalog annation for how to use resolver path in the shared link

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#711]
@karlcz can you please make a suggestion on the detail of the resolver config? Is this sufficient? 

tag: `tag:isrd.isi.edu,2018:resolver` 
```
  "catalog": 2
  "path": "/id/2/" or "/id/" for the default catalog?
```

**Comment by hongsudt** [comment]
@jrchudy We have already supported the default resolver, right? If so, then we should close this issue.

**Comment by hongsudt** [comment]
@jrchudy So when I click "Share", do we print out the link that looks like /id/2/<RID>?  If so, then this issue is done and we should close it.

**Comment by jrchudy** [comment]
There are 2 cases that can occur:
  1. When the `resolverImplicitConfig` property matches the catalog you are currently looking at, the link in the share dialog does **NOT** include the catalog number (`/id/<some-filter>`)
  2. When the above property does not match the current catalog, then the link will include the catalog number (`/id/2/<some-filter>`
