### ISSUE TITLE
Create Documentation for  Relationships

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/ermrestjs#713]
We need to have a section in the documents that talks about relationships.  Specifically it should address:

1) Using foreign key constraints to describe both inbound and outbound relationships
2) Pure binary association tables
3) Use of annotations to configure chaise in the above.

This should probably go before the annotations guide in the doc tree.

**Comment by hongsudt** [comment]
waiting for tech writer.

**Comment by RFSH** [comment]
Moved to wishlist.
