### ISSUE TITLE
support sorting and page size for array aggregate column

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#746]
There is a use case that want to have the content of aggregate array column sorted in a certain order. Ermrest doesn't support the sorting functionality but this can be done by chaise/ermrestjs. 

The table display annotation already have `page_size` and `row_order` defined as parameters. We want to extend the context to support the pseudo-column composing of entities. We decided to go with the `array_aggregate/context` pattern for its context. So for example if you want to change the order in recordset you have to use the `array_aggregate/compact` context, while the record page would be `array_aggregate/detailed`.

**Comment by RFSH** [comment]
We decided to not do this at the moment. Instead we are going to allow data-modelers to specify the page_size and row_order directly on the pseudo-column definition (#748).
