### ISSUE TITLE
hack to replace # with? in the chaise url

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#769]
Currently the chaise pages do not get indexed by google. This is either due to the chaise url is not crawable or the page itself is not indexable. 

 It seems like google truncate the URL after "#", which prevents it from getting to the chaise page. We want to do a simple hack that replace "#" with "?" so that we can test whether the URLs get crawled. It is ok to make this specific to only the record page to start with.  

Maybe we should create a branch for this, so laura or rob can just deployed it for testing?

**Comment by RFSH** [comment]
The change to support this has been already merged with master. We also added `cqp` to log the requests that are using `?` instead of `#`. This attribute is attached only to the main request of the page (main entity read in recordset, record, and viewer. create/edit request in recordedit).
