### ISSUE TITLE
Display Asset meta data columns (filename, bytecount, etc.) in entry

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#775]
Currently we're not allowing these extra columns and the asset column to co-exist in entry context. If the asset is not part of visible-columns, we're going to show these columns and mark them as generated. Otherwise, these columns will be completely removed from the visible-columns. We did this to avoid adding extra logic in chaise, to keep their values in sync with each other.

We should improve this. The selected file uri is not very meaningful to the users and showing the filename alongside the uri can be helpful. Although maybe just [improving the file-picker UI](https://github.com/informatics-isi-edu/chaise/issues/1755) might be enough.

If we decide to allow asset and its meta data columns to co-exist, we have to make sure chaise is keeping these two values in sync. This might require adding extra APIs in ermrestjs to expose the computed hash if there isn't one already.

**Comment by jrchudy** [comment]
I made changes in this [PR in chaise](https://github.com/informatics-isi-edu/chaise/pull/1766) to copy data from the metadata columns, if those values exist. I

**Comment by jrchudy** [comment]
@RFSH  does anything more need to be done for this issue?

**Comment by RFSH** [comment]
We should ask @hongsudt if she still thinks this is needed. The issue title is still not what we're doing and we've just done what I've described as an alternative to improve the UX. We're still removing the metadata columns in entry contexts.

**Comment by RFSH** [comment]
The improvements to the file picker are sufficient for now.
