### ISSUE TITLE
IE bug in _replaceDotWithUnderscore() function 

### ISSUE THREAD

**Issue by Divyata-Singh** [informatics-isi-edu/ermrestjs#776]
The _replaceDotWithUnderscore() function has a conditional check on the type of parameter on line 4433 in ermrest.js :  val.constructor.name !== "Object" . The JavaScript property Function.prototype.name is not supported in IE (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name#Browser_compatibility). This is preventing the treeview app from being loaded in IE. 

Possible Solution:
This check could be replaced by the condition: typeof(val) !== "object"

**Comment by RFSH** [comment]
Thanks for reporting this. I fixed and pushed it to master ([commit link](https://github.com/informatics-isi-edu/ermrestjs/commit/2a8d7822622ca39bcaef448906792140e10fbdca)). Please let me know if there are any other issues regarding IE support. I'm going to assign it to @Divyata-Singh  for verification.

**Comment by Divyata-Singh** [comment]
The treeview app is loading properly on Internet Explorer now. I added a list of things incompatible with IE under ermrestjs/docs/dev-docs/javascript-incompatible-with-IE.md .
