### ISSUE TITLE
Streamline angular integration

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#78]
`ngermrest.js` does this:

```
angular.module('ERMrest', [])

    .factory('ermrestServerFactory', ['$http', '$q', function($http, $q) {
        ERMrest.configure($http, $q);
        return ERMrest.ermrestFactory;
    }]);
```

We should make this more like the `node.js` script that @chiragsanghvi just added, so that the angular integration is automatic when running in an angular environment and just roll this script into the `ermrest.js` library package.

**Comment by hongsudt** [comment]
@jrchudy @RFSH is this suggestion still relevant?

**Comment by RFSH** [comment]
This is actually what we are doing. I think @robes did it after creating the issue.

https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/ng.js
