### ISSUE TITLE
Reference Skeleton to get Page and Tuple 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#79]
@hongsudt commented on [Tue Jul 12 2016](https://github.com/informatics-isi-edu/chaise/issues/501)

This task focuses on getting the Record2 data without any annotation (e.g. contextualization). Here is a list of methods that should be implemented:
```
module.resolve  /* use the existing parser */

.Reference
  .columns 
  .read
.Page  
  new Page(reference, data)
  ._data
  .tuples
.Tuple 
  new Tuple(reference,data)
  ._data
  .values
```

**Comment by jrchudy** [comment]
This issue is resolved with the changes in PR #100.
