### ISSUE TITLE
default system column display

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#796]
I would like to apply some heuristics for changing the order of the system columns in different context. We need to have a way to turn this heuristics on and off. 

For quick implementation, let's try this with chaise-config.. 

SystemColumnsDisplayCompact = true/false/[array of system columns]  
SystemColumnsDisplayDetailed = true/false/[array of system columns]

If true: then apply the heurstics to all columns
If false: don't apply huerictics
If non-empty array: only apply the heuristics to those columns; hide the rest 

Display:
A self-link RID should be shown first
The rest of the system columns are shown at the end of the non-system columns. 

@karlcz @robes @ljpearlman thoughts?

**Comment by jrchudy** [comment]
For clarification, if an array of system columns is defined, the order doesn't matter. The system columns heuristics will always be applied based on the above description below `Display:`.

The system columns order at the end of the list will always be `RCB, RMB, RCT, RMT`.

**Comment by jrchudy** [comment]
Changes for this have been merged into master. Assigning this to @hongsudt .

More info can be found in the [chaise config document](https://github.com/informatics-isi-edu/chaise/blob/master/docs/user-docs/chaise-config.md).
