### ISSUE TITLE
Add Inline Tables to Default Export Template

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#804]
We should create different `csv` outputs for inline tables. The same way that we're doing this for related tables.

**Comment by RFSH** [comment]
The changes for this are merged with master.

commit: https://github.com/informatics-isi-edu/ermrestjs/commit/0ff610a179a66e6b0a428693b3efa75f989f7793

**Comment by animesh-singh** [comment]
Hi @RFSH , I have verified the changes in dev and its looks good.
