### ISSUE TITLE
Support facets for array columns

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#807]
Currently we're not allowing facets for array columns. We did this because of the confusion that it might cause for users. We don't have a way to get the distinct members of arrays and then allow users to select those. 

For now we should do the same thing that we did for jsonb. Which will allow to do exact match of all the array values. We have to do the extra encoding that we did for jsonbs for array columns too.

**Comment by karlcz** [comment]
This is not possible in ermrest. There is no exact-match predicate for array-typed columns.
