### ISSUE TITLE
utility/library for formatting values of different data types

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#83]
These functions can take an optional format argument. 
- [x] Integer
```
function print_int(input_int, format) { 
  /* the input is an int or null */
  /* create a Number object and use its formatting method to format the output */
  /* Default: whole number with thousands separator. If null, return empty string */
}
```
- [x] Float
```
function print_float(input_float, format) {
  /* input is a float or null */
  /* create a Number object and use its formatting method to format the output */
  /* Default: thousands separator, 2 decimal number. If null, return empty string */
}
```
- [x] Date
```
function print_date(date_string, format) {
  /* input is a date string or null */
  /* create a javascript date object and use its formatting method to format the output */
}
```
- [x] Datetime/timestamp
```
function print_timestamp(ts_string, format) {
  /* input is a ts string or null */
  /* create a javascript Datetime object and use its formatting method to format the output */
}
```
- [x] Boolean
```
function print_boolean(input_int, format) {
  /* input: a boolean or null */
  /* Default: return "True", "False". If null, return empty string */
}
```
- [x] Markdown (Aref)

- [x]  Text

**Comment by robes** [comment]
Is this a duplicate of #52 ?

**Comment by howdyjessie** [comment]
@robes It's particularly clear here, but the difference is that this issue is basically `Column.formatvalue()` while #52 is meant to describe all the separate helper functions that would be used inside `Column.formatValue()`.

**Comment by howdyjessie** [comment]
A couple links that @chiragsanghvi passed to me that are relevant to this issue that we'll probably want to look at later:

- A JS printf library: https://github.com/alexei/sprintf.js
- Something to help determine the type of a value: https://isi-isrd.slack.com/files/chiragsanghvi/F1WGXNLQN/type.js

**Comment by howdyjessie** [comment]
Currently doing: Changes in Chaise to support display of Markdown.

**Comment by howdyjessie** [comment]
This issue is under review at PR #121.

**Comment by hongsudt** [comment]
Since #121 is merged, I am closing this issue.
