### ISSUE TITLE
Comment changes

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#832]
1. We should allow `comment` attribute defined in display annotation (and other places if applicable) to be contextualized. So the acceptable values for `comment` would be : 
  - string--- the comment string
  - `false`---turn off comment
  - {_context_: _value_}---contextualized comments 
2. We should allow `comment` in the foreign key annotation (e.g. currently this field is missing).

**Comment by hongsudt** [comment]
@jrchudy I think this is related to the current issue that you are working on.. I am dragging this to in-progress.
