### ISSUE TITLE
use prefix_markdown suffix_markdown in tabular format

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#833]
Currently, `prefix_markdown` and `suffix_markdown` are solely used in conjunction with `row_markdown_pattern` annotation. But we could broaden their scope and these values can be displayed in the non-tabular mode as well. 

The only issue is that in some cases you might want to show different values in tabular and non-tabular mode. There also should be a way to suppress it one way or another. To this extend, maybe we should introduce a new attribute for the tabular mode? or maybe we should leave these variables the way they are?

We're currently working on adding a way to support explicit comments in the related section. While reviewing the possible solutions, this came up.

**Comment by karlcz** [comment]
Should the tabular/non-tabular mode be configured via
context/subcontext of some kind...?

**Comment by RFSH** [comment]
Moved to wishlist.
