### ISSUE TITLE
modify hide_column_headers annotation

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#834]
This attribute is currently defined in the table-display annotation and can be used to hide the column headers on the record page. The changes that we should do regarding this attribute are:

- [x] Fix the documentation that is saying it's used in `compact` context (it's used in `detailed`).
- [ ] Rename it to `hide_column_header` to be consistent with the other annotations (namely `show_nulls` and `show_foreign_key_link`).
- [x] Allow it to be defined under column-display annotation as well. Then chaise should use this attribute to hide the specific column (instead of hiding all the columns). This will avoid the current custom-css changes that we're doing in rbk/gudmap to hide the column header for the treeview.

update:
  - column display contextualized?
    - apply to just record app

Implementing these changes will fix issue [#1993](https://github.com/informatics-isi-edu/chaise/issues/1993) in chaise.

**Comment by jrchudy** [comment]
PR #868 has been merged into master. In chaise, this is only implemented for the record app (detailed context).

**Comment by jrchudy** [comment]
@RFSH should we keep this issue open because of the 2nd bullet point?

**Comment by RFSH** [comment]
Yes, I think so. And it's a very small change (I don't think it's worth creating an extra issue for it)

**Comment by RFSH** [comment]
I renamed `hide_column_headers` to `hide_column_header` [in this commit](https://github.com/informatics-isi-edu/ermrestjs/commit/95dabcc9cb3f33962160bc797ff9b395806e9818). I didn't remove the old name and it should still work for backwards compatibility purposes.
