### ISSUE TITLE
New handlebars helper block to do string substitution

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#845]
A while ago we added `regexMatch` handlebars function that allows us to do regular expression matching. The returned value of this helper is a boolean, so it's only useful in combination with `if` block.  

We want a new helper that given a string value and a regular expression, returns the parts of a string that match a given regular expression. We could use [`exec` function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec) for this.

This came up because we wanted to be able to extract the filenames from the URL value.

**Comment by jrchudy** [comment]
Look up what python calls regular expression functions. Maybe it's `regexSearch`. 

Test `^\\(.+\\)*(.+)\.(.+)$` works for piking apart a url to show `path`, `filename`, and `file extension`.

**Comment by jrchudy** [comment]
This issue has been resolved with PR #859 being merged into master. Documentation changes and an example for extracting filename can be [found here](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/handlebars.md#findfirst-helper).
