### ISSUE TITLE
Support domain_filter_pattern in add pure and binary

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#854]
We should investigate whether it makes sense to support `domain_filter_pattern` in other places as well.  

With #491 we're going to fix some of the issues with the existing support. Also with #685, data-modelers should be able to filter the displayed values further. But still, they won't be able to do this dynamically and therefore we might want to see if this can be applied to record page (and potentially other apps.)

The following are the potential issues that I can think of that we need to discuss:
- The existing `domain_filter` feature is a property of `foreign-key` annotation. So if we want to use the same property, this annotation should be defined on the foreign key from association table to main table and therefore as part of the association table. So we only would be able to use the data from the association table (and not the main table).
- If `domain_filter` is defined on a foreign key, should it be used in both foreign key picker and also add pure & binary popup? Or should we add context to the annotation?

P.S. Given that this annotation is not easy to write and requires ERMrest knowledge we are thinking about extending #685 to possibly allow dynamic filters.

**Comment by robes** [comment]
My input. We have a scenario that I will try to explain this way:

`A <- AB -> B` where tables `A` and `B` are associated via the pure and binary table `AB`.

From table `A`, when associating a `B`, I would like to restrict the selection of `B` according to `B`'s property `x` where `x=<literal>` but only on this `A <- AB -> B` path. I.e., other relationships to `B` should not be affected. Note that the restriction `x=<literal>` can be defined during the specification of the annotation, it is not data dependent, it can be defined statically by the data modeler.

**Comment by robes** [comment]
The use case for this feature in FaceBase is that a user creates a "data access request" to request access to restricted human subjects "datasets". The tables `data_access_request` and `dataset` are associated via `dar_dataset` pure binary association. At present, when the user "adds" datasets to their data_access_request they get an unfiltered picker of all datasets. The usability issue here is that only "human subjects" data need to be requested (i.e., where `dataset.human_subjects == True`). Users are prone to make the mistake of requesting data that are not human subjects (and therefore do not require special approval). Ideally, when the user is creating their data_access_request and adding datasets to it, they should get a picker with the human_subjects == true preset to help them to avoid confusion.

**Comment by RFSH** [comment]
Given that the described behavior is achievable by using "filter in source feature" as described in [this issue](https://github.com/informatics-isi-edu/chaise/issues/1955), I'm going to close this issue.
