### ISSUE TITLE
Proper handling of CFDE: related entities with non-RID source definitions

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#874]
#### Summary
For the "explore" link in chaise, ermrestjs is creating a reverse path of the related entity where the main table's shortest key would be the selected facet. To make sure that the proper facet is selected when users click on "explore" button, data-modelers have to define their facet using the shortest key to align with this automatic process. So technically data-modelers cannot have any entity non-RID facets.

#### Example
Assume the `A (RID) <- B (fk_to_A_col)` relationship and that `B` is defined as a related entity in the table `A`:

```json
{
  "tag:isrd.isi.edu,2016:visible-foreign-keys": {
    "*": [
      {
        "source": [
          {"inbound": ["s", "fk_from_B_to_A_constraint"]}, 
          "RID"
        ],
        "entity": true
      }
    ]
  }
}
```
By navigating to a page with `S:A/RID=v1_rid`, users would be able to see the related entities in table `B` for this record. Clicking on "Explore" should navigate them to a recordset of table `B` where this relationship is defined as a facet. So ermrestjs would create a URL to `S:B` with the following facet:

```json
{
  "and": [
    {
      "source": [
        {"outbound": ["s", "fk_from_B_to_A_constraint"]},
        "RID"
      ],
      "choices": ["v1_rid"]
    }
  ]
}
```

And if the same exact facet definition is missing from the table's facet list, ermrestjs will append a temporary facet to the facet panel. This can be very confusing if your facet definition is based on the same path but different end column.

#### Proposed solution

After discussion we came up with a better solution which is documented in [this comment](https://github.com/informatics-isi-edu/ermrestjs/issues/874#issuecomment-824264390)

<details>

<summary>For the original proposed solution click here.</summary>

We should come up with a new annotation that would allow users to have control over this reverse path. 

> What to name the new property is not the main focus right now. We should first make sure what the new annotation/property should do and then we can improve the naming.

1. The most straightforward solution would be allowing data-modelers to define the whole reverse path. And then do the same heuristics if this reverse path is missing. So

  ```json
  {
    "source": [
      {"outbound": ["s", "fk_from_B_to_A_constraint"]},
      "RID"
    ],
    "entity": true,
    "parent_source": [
      {"inbound": ["s", "fk_from_B_to_A_constraint"]}, 
      "some_other_key_in_table_A"
    ]
  }
  ```
  > Other names that I can think of: `explore_source`, `source_to_parent`, `reverse_source`

2. We can easily figure out the reverse path and the only issue here is the end column. So maybe we just want to allow data-modelers to define the last column in the reversal path.

  ```json
  {
    "source": [
      {"outbound": ["s", "fk_from_B_to_A_constraint"]},
      "RID"
    ],
    "entity": true,
    "parent_key": ["some_other_key_in_table_A"]
  }
  ```
  > Other names that I can think of: `explore_key`, `reverse_source_key`

Assuming that we want to go with one of these solutions, the following would be the required tasks to achieve this:
- [ ] Finalize the annotation
- [ ] Modify ermrestjs code to use the annotation for reverse path.
- [ ] Add new test cases to ermrestjs
- [ ] Add new test cases to chaise

</details>

**Comment by karlcz** [comment]
Perhaps it should be something like `preferred_entity_key` as a table
annotation and affect all heuristics related to shortest-key.  Not
just explore links but any automatically generated entity-mode facets,
etc.

**Comment by RFSH** [comment]
We had another discussion about this issue and the following are the summary of changes that we want to work on:

- For the reverse path heuristics, instead of always using the shortest key we should be smart about it and try to find a better key. If we couldn't find any other keys, we would fallback to using `RID`. To find a better key, 
  - We should first look for the facet definition. If we can find a facet with the same path in entity mode, we should use the key defined in there. Our goal is to avoid adding a duplicated facet to facet panel, and by doing this, that issue is solved.
  - If we cannot a similar path in facet definitions, it means that we have to create that new facet when users navigate to recordset. So our goal would be making sure the name and other display related properties that will be generated by heuristics are accurate. So we might potentially look at related references in the detailed context. And in the end we should look for the source definitions. **This part requires more thought**
- As it was pointed out in the previous comment, in some deployments we still want to define the `preferred_entity_key`. So we should introduce a new annotation that can support this. The following are two proposed solutions:

  ```javascript
  "tag:isrd.isi.edu,2021:table": {
    "preferred_entity_key_cols": ["name1", "name2"],
    "preferred_entity_key": ["schema", "constraint"]
  },
  // or 
  "tag:isrd.isi.edu,2016:table-display": {
    "row_name": {
      "row_markdown_pattern": "{{{id}}}",
      "preferred_entity_key_cols": ["name1", "name2"]
    },
    "*": {
      "preferred_entity_key": ["schema", "constraint"]
    }
  }
  ```
  The first one would change the key for all the contexts, while the other one is context-based. I should mention that the initial reason for adding the second method was to avoid introducing new annotation. And since `table-display` is context-based, this new attribute must be contextualized as well. But we couldn't come up with a use case that would require using different keys in different contexts. While discussing this we also talk about potentially refactoring the `table-display` annotation and moving it into a `display` property under this new `table` annotation. But that won't be the focus on these changes for now. **Needs more thought into whether we actually want context or not**

**Comment by jrchudy** [comment]
Due to database changes, this is no longer a high priority for CFDE.

**Comment by RFSH** [comment]
Moved to wish list.
