### ISSUE TITLE
CFDE: Suppress Count request and display

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrestjs#883]
The CFDE catalog has grown very large after the recent data data release. The count query is becoming quite slow in some cases causing the page to hang and, if enough are running in parallel, can get the server locked up to the point that other users can't access the system.

We need a way to suppress the count requests from occurring for certain catalogs.

**Comment by RFSH** [comment]
As I mentioned in the #884 issue, we already allow data-modelers to suppress the count. The only other place that we're using `count` aggregate function by default, is the main count that is displayed in recordset app and popups. 

The table-header directive already allows suppression of count (we're not showing the count in related entity section), so we don't need to worry about UI changes and we just need to agree on the annotation that signals to chaise to hide the count.

For that, we could use [table-display](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2016-table-display) annotation and the same way that we have `collapse_toc_panel` and `hide_column_headers`, we could have a `hide_total_count` option. Personally I'm not a fan of how we added `collapse_toc_panel` and `hide_column_headers` here given that the table-display is context-based and these two options are not applicable to every context, but for consistency I think we should add the option to the same place and we can do the refactoring later. Or if we want to refactor this now, we could add the table annotation that we discussed about in [here](https://github.com/informatics-isi-edu/ermrestjs/issues/874#issuecomment-824264390) and then move these options to this new annotation.

**Comment by RFSH** [comment]
Given that we want to allow data-modelers to define this on catalog or schema, we decided to add this to `display` annotation. So we're going to add a `hide_row_count` which is contextualized just like `show_null`/`show_key_link`/etc. 

With this we're going to add a `Reference.display.hideRowCount` API to ermrestjs and then chaise should just consume it in the table directive.

**Comment by RFSH** [comment]
Both chaise and ERMrestJS changes related to this have been merged with master.
