### ISSUE TITLE
CFDE: Allow all-outbound pseudo-columns in the search box

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#885]
Currently the search box customization feature only allows columns of the same table to be defined in the `search-box` sourcekey. So in this issue we want to discuss the possibility of allowing all-outbound pseudo-columns.

After implementing the first iteration of this support, [in this comment](https://github.com/informatics-isi-edu/ermrestjs/issues/744#issuecomment-558302079), I explained the issues that we might have to allow all-outbound paths. And @karlcz made some suggestions on how we could achieve this. In the following I'm going to summarize the same comment and discussion:

- The current syntax for customizing search-box is as follows:
  ```
  "tag:isrd.isi.edu,2019:source-definitions": {
    "sources": {
      "search-box": {
        "or": [
          {"source": "col", "markdown_name": "column"},
          {"source": "col2", "markdown_name": "column 2"},
        ]
      }
    }
  }
  ```

- Since we're defining a disjunctive list of sources for the search-box with `"or"`, we need to do an outer join if the search-box has to match on more than one source and any of the sources requires a join. We can skip this (and use inner join) if there is only a single source. 

- We cannot even mix a single join with local columns of the table. A deployment using joins would have to build a term/indexing table for all entity content to be matched by the searchbox, including base row content. They cannot just build a table to link in auxiliary terms.

- Because of the same issues that we faced while parsing facets for the `null` check, we should not use left outer join. And since we cannot have multiple right outer joins, we cannot support more than one foreign key path in the search columns. 

- For the same reason above, If there are multiple search columns defined and one of them is a foreign key path, we cannot apply the `null` facet with search as they both would require right outer join.

- We might want to consider something like an "inner_join_safe: true" setting that a DBA can make on a source definition to allow Chaise to blindly do inner joins for the search-box disjunctive list of sources. It would be the DBA's job to ensure that the inner join will not in itself exclude rows relevant to the search, e.g. because they know that the path represents a 1-or-more relationship in practice for every row that the client is allowed to select. I.e. they need to think about their relational data and their policy environment when declaring this safety property.

**Comment by karlcz** [comment]
I am not sure I agree with the statements that we can never use inner
joins nor mix them with local columns.  However, the nullability test
for when an outbound-only path can be inner joined would have to
consider access rights to the foreign key columns and extra tables,
since a row-level policy (where static rights are "null") could
make a non-nullable fkey act like a nullable fkey.

**Comment by RFSH** [comment]
I'm going to close this issue in favor of #906 that is more accurate and has more information.
