### ISSUE TITLE
CFDE: Allow reusing path prefix in source definition

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#886]
## Description

By using source syntax, data-modelers can define complex paths. In some cases, the defined paths for different columns/facets are sharing the same prefix and by reusing these prefix we could increase the performance of chaise apps.

Ideally data-modelers should be able to define different path prefixs and then use these prefixes while defining a visible column or facet. 

## Solution

One proposed solution is reusing the source-definition syntax and then using a specific keyword (the same level as `inbound`/`outbound` to access these paths). For example assume the following ERD (I'm going to use the same ERD for all the examples in this issue):

![ERD](https://user-images.githubusercontent.com/2129750/125837938-f82ed88e-b2d0-49e7-b4f9-c1b40b05a7c5.png)

Then you should be able to do
```json
"tag:isrd.isi.edu,2019:source-definitions": {
  "sources": {
    "path_to_a": {
         "source": [
             {"outbound": ["s", "main_A_fk"]},
             "RID"
         ]
    },
    "path_to_b": {
         "source": [
            {"sourcekey": "path_to_a"},
            {"outbound": ["s", "A_B_fk"]},
            "RID"
        ]
    },
    "path_to_c": {
      "source": [
          {"sourcekey": "path_to_b"},
          {"outbound": ["s", "B_C_fk"]},
          "RID"
      ]
    }
  }
}
```

You can find more examples in [here](https://hackmd.io/r_tXuhmJS9yfVPihh7bklA?view). In the following I will summarize all the decisions that we made about this:

- As it is demonstrated in the example above, it should support recursive prefix paths. So it should also detect cycle and show an error.
- We are not going to allow path prefixes without any additional fks. So the following is not valid:
  ```json
  {
    "some_other_path": [
      {"sourcekey": "path_to_a"},
      "some_other_col"
    ]
  }
  ``` 
  (I'm not allowing this because of limitations in the code. We have a logic that optimizes facet paths by removing the last foreignkey relationship. The current code couldn't handle this case when this sort of syntax is used and required a lot of changes) 
- The generated hash for pseudo-columns should be based on the structure. So if you have two source definitions that are using the same structural path but their syntax is different (one is using path prefix while the other is not), they are going to produce the same hash (and therefore they will be marked as duplicates in visible-columns)
- Facets and visible all-outbound paths should be able to share the same path. That being said, facets that have `null` filter cannot share the same path with other parts of the url (since we're transforming the url to use right outer join).

While discussing this, the following also came up but we decided to just document and not take any action:

1. Currently we're always using `left` outer join for the all-outbound paths. But we could improve this. If all the columns involved in the foreign key relationships are `"nullok":false` and `"select": true` then we can be sure that if there's a main row, there will be a row corresponding to this relationship and therefore it's safe to use inner join. 

2. Technically we might be able to share joins between the facet with `null` and rest of the url. Assume `T` is the facet with null and `M` is the main table.
  - If T to M is all outbound, there's no sharing for M. M starts in its own space.
  - If M to T is all outbound,  we could share.

**Comment by karlcz** [comment]
I would suggest reusing our sourcekey reference current syntax:

  "path_to_B": { ... },
  "path_to_C": {
    "source": [
      {"sourcekey": "path_to_B"},
      {"outbound": ["s", "B_C_fk"},
      "RID"
    ]
  }
  ...
