### ISSUE TITLE
Review export annotation

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#917]
Export annotation was added as an experimental feature to be able to use `ioboxd` in Chaise apps. But now that the feature has been used and matured, we should take a step back and reevaluate the decisions that we made. 

In this issue, we should list the current attributes that are expected in the export annotation and how they are used. We should explain how the given attributes map to a configuration that is eventually sent to export service.

Our goal is to figure out whether we need to make any modifications to our process. Whether in some cases we should just allow data-modelers to define an object/property that is passed through without any modifications.

_Requires more thought and details. Created this issue as a placeholder for future_

**Comment by karlcz** [comment]
In our sketch of that acl_matching_alternatives, we said the FIRST
matching element would be chosen.  It wouldn't produce multiple
clauses for a single client.  The purpose of the ordered list is to
allow the author to prioritize this selection when there might
otherwise be multiple matches.

**Comment by RFSH** [comment]
@karlcz Yes, I forgot to include that. I modified the notes to mention this.

**Comment by RFSH** [comment]
Moved to wishlist.
