### ISSUE TITLE
Http feature for retry doesn't works for error codes other than 1

### ISSUE THREAD

**Issue by chiragsanghvi** [informatics-isi-edu/ermrestjs#98]
The issue is with the usage of `in` operator on an array to determine retryable error codes on this [line](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/http.js#L126).

`in` is used to determine the presence of a property in an object [Reference] or presence of a property at an index(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in).

**Comment by robes** [comment]
thanks
